### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by zyxcambridge** [open-mmlab/OpenPCDet#1010]
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray
            torch.onnx.export(model, (dummy_voxel_features, dummy_voxel_num_points, dummy_voxel_coordinates,dummy_grid_ind), "pointpillars_pp_cpseg.onnx" , verbose=True,
                              training=False,
                              operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=11,
                              input_names = ['input', 'voxel_num_points', 'coords','grid_ind'],
                              output_names=['hm', 'center'])

**Comment by samtisi** [comment]
I'm still having this issue. Just installed mmlab and mmdetection, as per instructions, then downloaded the FasterRCNN model and tried to convert to ONNX. 

mmlab's own model and function to convert to ONNX work on a simple install.
