### ISSUE TITLE
performance of pvrcnn++ on waymodataset

### ISSUE THREAD

**Issue by AndyYuan96** [open-mmlab/OpenPCDet#1013]
Hi, thanks for open source the code, I use default config to train, the performance of car ped are the same with readme, but cyclist's performance is lower than readme, which is 1.5point low, does it is normal?

**Comment by jihanyang** [comment]
Would you like to repeat the experiment again?

**Comment by AndyYuan96** [comment]
> Would you like to repeat the experiment again?

maybe cyclist's number is small compared to others, I try other config, the cyclist's ap is lower around 1 point.
