### ISSUE TITLE
Processing dependencies for pcdet==0.5.2+dadda9e error: llvmlite 0.38.1 is installed but llvmlite<0.38,>=0.37.0rc1 is required by {'numba'}

### ISSUE THREAD

**Issue by thom966** [open-mmlab/OpenPCDet#1018]
I am trying to install `pcdet` library with `python setup.py develop` command. 
However, I have met the following error:
 `Processing dependencies for pcdet==0.5.2+dadda9e
error: llvmlite 0.38.1 is installed but llvmlite<0.38,>=0.37.0rc1 is required by {'numba'}
`
My conda environment has numba==0.54.1 and llvmlite==0.37.0 version.
Any help would be highly appreciated.

**Comment by 20chase** [comment]
you can try `pip install numba` first, it may solve the dependence error.

**Comment by daeunni** [comment]
@20chase your answer will be helpful for me. thanks!
