### ISSUE TITLE
Question about HeightCompression

### ISSUE THREAD

**Issue by frogbam** [open-mmlab/OpenPCDet#1019]
Hi.

I have a question about code line In the height_compression.py : 
```
encoded_spconv_tensor = batch_dict['encoded_spconv_tensor']
spatial_features = encoded_spconv_tensor.dense()
N, C, D, H, W = spatial_features.shape
spatial_features = spatial_features.view(N, C * D, H, W)
```

What's the meaning of N, C, D, H, W?
Does it mean batch_num, Channel, Z-axis(height), X-axis, Y-axis respectively?

Thanks.

**Comment by jihanyang** [comment]
Yes.

**Comment by frogbam** [comment]
> Yes.

Thanks a lot.
