### ISSUE TITLE
How to visualize object bounding boxes of images in kitti datasets

### ISSUE THREAD

**Issue by strugglingguoguo** [open-mmlab/OpenPCDet#1020]
I want to visualize the point cloud data with bounding boxes and the corresponding image bounding boxes at the same time in order to better observe the quality of the bounding boxes. What should I do？
I would appreciate it if you could help me with it！

**Comment by OrangeSodahub** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/c233477a4a4bf2861a978794d6b9c047f64641f7/tools/demo.py#L100-L106
