### ISSUE TITLE
How to report FLOPS, Runtime and Model Size(model paramters) of the Model

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/OpenPCDet#1021]
Is there any method in the test or evaluation phase to measure the FLOPS, Runtime, and Model size or No of Parameters for the Model?

**Comment by jihanyang** [comment]
You can follow some repos such as pytorch-op-count or pycls to count them.

**Comment by M0NSTERCOCO** [comment]
The repos that you mentioned don't work. Can you give me a complete hint to solve this problem please?
