### ISSUE TITLE
Why annotations['index'] doesn't make correspondence to 'DontCare'

### ISSUE THREAD

**Issue by FantineFu** [open-mmlab/OpenPCDet#103]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/30807653/85941778-8a314700-b957-11ea-92ab-1bf14236230e.png">

Why the index with -1 doesn't corresponding to the object with 'DontCare' in order?

**Comment by sshaoshuai** [comment]
We ignore the `DontCare` objects in the KITTI dataset since it generally doesn't have valid 3D annotations.

**Comment by ltphy** [comment]
The 'DontCare' labels always lines at the end of label files, that's why the [-1] does correspond to the object 'DontCare'.
