### ISSUE TITLE
How to make the test result of KITTI test dataset into txt

### ISSUE THREAD

**Issue by KimMoon98** [open-mmlab/OpenPCDet#1031]
I hope to submit my test results to Kitti's official website for testing, but I don't know how to change the test result of KITTI test dataset into txt.If anyone knows, please tell me, thank you!

**Comment by KimMoon98** [comment]
This problem bothered me for a long time. I searched for it for a long time without results.I would appreciate it if someone could give me some tips.plz

**Comment by jihanyang** [comment]
Use `--save_to_file`. BTW, this problem has been discussed massive times in previous issues.
