### ISSUE TITLE
Different test results of the same weight？

### ISSUE THREAD

**Issue by Tongjiaxun** [open-mmlab/OpenPCDet#1038]
With the same Weight file, everytime I run test.py ,the result is different. Can anybody tell me the reason ？

**Comment by thptai** [comment]
What is the model you use to test ?

There is some models such as PV-RCNN use Furthest- Point-Sampling technique to query sampling keypoints. That technique contains a random factor, so that may be the reason.

**Comment by Tongjiaxun** [comment]
I use the pointpillar and pointrcnn. When I use the model provided in this repo (pointpillar) the result is consistent. So I think my result should be consistent too...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/OpenPCDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/OpenPCDet] Different test results of the same weight？ (Issue #1038)





 
What is the model you use to test ?
 
There is some models such as PV-RCNN use Furthest- Point-Sampling technique to query sampling keypoints. That technique contains a random factor, so that may be the reason.
