### ISSUE TITLE
When using nusc_trainval to train centerpoint, the GPU occupancy rate is not high, but the CPU occupancy rate is high

### ISSUE THREAD

**Issue by BoXingJinQiu** [open-mmlab/OpenPCDet#1046]
When I use nusc_trainval to train centerpoint, why is the GPU usage not high, but the CPU usage is high. CPU reached 70G. Parameter settings: gpu_num=4, num_workers=1, sweeps=10

**Comment by jihanyang** [comment]
I suppose that most time are token by data fetch and processing process.
