### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed 

### ISSUE THREAD

**Issue by baohaooo** [open-mmlab/OpenPCDet#1047]
hi ,could someone tell me how can i solve this problem?
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 65043) of binary: /home.............

**Comment by jihanyang** [comment]
We haven't met such problem. Hope other researchers can help you.

**Comment by aldipiroli** [comment]
Can you provide the full traceback? 
If the traceback does not provide anything meaningful it might be worth looking at your ram usage. It could be that you run out of memory and the training script stops.
