### ISSUE TITLE
Add annotation in tutorial of converting Waymo Open Dataset to avoid confusion

### ISSUE THREAD

**Issue by catshift** [open-mmlab/OpenPCDet#1052]
So in the original tutorial you will run this:
```
python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos \
    --cfg_file tools/cfgs/dataset_configs/waymo_dataset.yaml
```
And this will cause error:

> failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

Generating the dataset ignoring the error is OK, but I think this is a problem to be solved, as whether the process will succeed without gpu is unknown.

So I tried hard to solve the problem, and finally I found this in `OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py line 415`:
``` 
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```
Obviously, the process does not require gpu at all, so the error is not required to be solved.
Note that you cannot use gpu even if you set CUDA_VISIBLE_DEVICES to normal value, because this process uses multi_threads and huge batch_size, which is diffcult for gpu to handle.

So if some annotations could be added to the `OpenPCDet/blob/master/docs/GETTING_STARTED.md`, like:
```python
python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos \
    --cfg_file tools/cfgs/dataset_configs/waymo_dataset.yaml
# if 'CUDA_ERROR_NO_DEVICE' error occurs, it's OK because this process does not require gpu.
```
it would be a big help, as I wasted a lot of time in tracking the error.

And if my guess is wrong, please let me know the solution.

**Comment by jihanyang** [comment]
Yes, you are correct. We will add a notification in the `GETTING_STARTED.md`. BTW, this issue has been discussed in #350. If you meet other questions for OpenPCDet, maybe checking previous issues can be a good consideration.
