### ISSUE TITLE
gt_boxes key_error

### ISSUE THREAD

**Issue by SakuraRiven** [open-mmlab/OpenPCDet#1053]
https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/nuscenes/nuscenes_dataset.py#L143

Could we add ```'gt_boxes' in data_dict:``` in above line to avoid key_error? Because I want to just inference some middle sweep frames without annos.

**Comment by Raiden-cn** [comment]
Hi !Same question as yours, I had to set `SET_NAN_VELOCITY_TO_ZEROS: False`.
Did you resolve it?

**Comment by SakuraRiven** [comment]
@Raiden-cn  maybe just refer to https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/nuscenes/nuscenes_dataset.py#L148
