### ISSUE TITLE
problems about version switching

### ISSUE THREAD

**Issue by KevinDuBl** [open-mmlab/OpenPCDet#1061]
I run the experiments on Openpcdet0.2, now I need to make the code correct on version 0.5. If I directly change the OpenPCDet/pcdet from 0.2 to 0.5 and re-setup, will the network make mistakes? If so, what need I do to modify the code?

**Comment by sshaoshuai** [comment]
Sorry, we are not sure since there are so many commits from v0.2 to v0.5 and it depends on what model/dataset you are going to use. Maybe you can check the information at README about each update.
