### ISSUE TITLE
Adding new classes to a pre-trained model

### ISSUE THREAD

**Issue by d33dler** [open-mmlab/OpenPCDet#1066]
Assuming the model was trained on kitti/waymo dataset with 3 classes, can we add new classes and continue training with the addition of these new classes? (by changing the dataset & model configs, specifically for PVRCNN++) 
Thanks
@jihanyang

**Comment by jihanyang** [comment]
You can have a try. But as the cls head will change with more class, I am not sure how the performance will behave.

**Comment by d33dler** [comment]
> You can have a try. But as the cls head will change with more class, I am not sure how the performance will behave.

@jihanyang So it is preferred to train with all classes from the beginning? Approximately how many classes could be used until the performance begins to degrade?

**Comment by d33dler** [comment]
@jihanyang some insight would be greatly appreciated!
