### ISSUE TITLE
The storage to store the processed waymo dataset?

### ISSUE THREAD

**Issue by sjtuljw520** [open-mmlab/OpenPCDet#1067]
The raw waymo dataset is about 1 T, and how much storage needed to store the processed waymo dataset?

**Comment by d33dler** [comment]
Around ~500MB

**Comment by sjtuljw520** [comment]
Thank you! The number of samples of the processed dataset is 20% of the raw data, so the storage is reduced?

**Comment by sjtuljw520** [comment]
@d33dler

**Comment by d33dler** [comment]
It depends on the sampling fraction from the dataset config, also the clouds sizes are reduced to your own configs size afaik

**Comment by sshaoshuai** [comment]
It consumes about 630GB in my server (the directory `waymo_processed_data_v0_5_0`).

**Comment by sjtuljw520** [comment]
Thank you! Does the 630GB contain all point cloud samples or just a portion, for example, 20% ? @sshaoshuai

**Comment by sshaoshuai** [comment]
It contains 100% samples.
