### ISSUE TITLE
Does the cbgs_pp_multihead.yaml means PointPillars+ in Pointpainting paper?

### ISSUE THREAD

**Issue by Raiden-cn** [open-mmlab/OpenPCDet#1069]
The PP+ had achieve 40.1 mAP.
Can cbgs_pp_multihead.yaml do it or higher?
Does  the `cbgs_pp_multihead.yaml` means `PointPillars+` in Pointpainting paper?

**Comment by jihanyang** [comment]
No. Please refer to https://arxiv.org/pdf/1908.09492.pdf.
