### ISSUE TITLE
A question about Dataset Preparation

### ISSUE THREAD

**Issue by Blinjuan** [open-mmlab/OpenPCDet#107]
hi，thanks for your excellent work，however，when i try to prepare my dataset by command 
“python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml”
it always occur the error as follow：
“gt_database sample: 1/3712
Segmentation fault (core dumped)”
![图片](https://user-images.githubusercontent.com/66398813/86135059-eabdb100-bb1c-11ea-9cfb-b0ca4d2f2d2c.png)
i don't know the reason ，i try the command many times  and did't fix i

**Comment by Gus-Guo** [comment]
Hi, I see that you have already generated the kitti infos pickle file successfully and the problem comes out when it wanted to generate the groundtruth database. You can try to comment the codes for generating kitti infos,  only run the codes for generating database and see whether it can work.

**Comment by Blinjuan** [comment]
> 
> 
> Hi, I see that you have already generated the kitti infos pickle file successfully and the problem comes out when it wanted to generate the groundtruth database. You can try to comment the codes for generating kitti infos, only run the codes for generating database and see whether it can work.

Thanks for your reply，I try to  comment the codes for generating kitti infos。
![图片](https://user-images.githubusercontent.com/66398813/86209445-32881b00-bba5-11ea-85b1-b4cf22753419.png)
however,it does't work
![图片](https://user-images.githubusercontent.com/66398813/86209529-58adbb00-bba5-11ea-9a84-71908c94bbb7.png)

**Comment by sshaoshuai** [comment]
I guess the error occurs at `roiaware_pool3d_utils.points_in_boxes_cpu`. 
Maybe there are some problems in your compilation when you run `python setup.py develop`.  So could you post the compilation logs to see if there are some problems?

**Comment by Blinjuan** [comment]
> 
> 
> I guess the error occurs at `roiaware_pool3d_utils.points_in_boxes_cpu`.
> Maybe there are some problems in your compilation when you run `python setup.py develop`. So could you post the compilation logs to see if there are some problems?
After run command “python setup.py develop” i get this
![图片](https://user-images.githubusercontent.com/66398813/86228114-93711c80-bbc0-11ea-9a86-f3c470269532.png)
![图片](https://user-images.githubusercontent.com/66398813/86228070-80f6e300-bbc0-11ea-980a-4864243a303a.png)
![图片](https://user-images.githubusercontent.com/66398813/86228327-cfa47d00-bbc0-11ea-9af1-4f1a4e366365.png)

**Comment by Blinjuan** [comment]
> 
> 
> I guess the error occurs at `roiaware_pool3d_utils.points_in_boxes_cpu`.
> Maybe there are some problems in your compilation when you run `python setup.py develop`. So could you post the compilation logs to see if there are some problems?
after  run the command “python setup.py develop” 
![图片](https://user-images.githubusercontent.com/66398813/86228893-8dc80680-bbc1-11ea-93a5-ff0d75413c90.png)
![图片](https://user-images.githubusercontent.com/66398813/86228968-a46e5d80-bbc1-11ea-91eb-aab2e50b4c79.png)

my environment as follow：
![图片](https://user-images.githubusercontent.com/66398813/86229144-df709100-bbc1-11ea-8cc9-53d4fe22c6a9.png)

when i try to debug，i find  in the roiaware_pool3d_utils.py around 20 line "roiaware_pool3d_cuda.points_in_boxes_cpu(boxes.float().contiguous(), points.float().contiguous(), point_indices)" cause this problem

**Comment by sshaoshuai** [comment]
You should remove the `build` directory first in your root path of PCDet and then re-run `python setup.py develop`, since your current log doesn't have useful information for debugging. 
The error position shows that there are some problems in your compilation process, and you need to pay more attention to the errors or warnings of your compilation log.

**Comment by Blinjuan** [comment]
> 
> 
> You should remove the `build` directory first in your root path of PCDet and then re-run `python setup.py develop`, since your current log doesn't have useful information for debugging.
> The error position shows that there are some problems in your compilation process, and you need to pay more attention to the errors or warnings of your compilation log.
ouch~~~ Thank you very much. I understand the reason now，I change gcc4.8.5 to gcc5.4.0. It works!  it seems that we should use gcc5.4.0.
Thank you.
