### ISSUE TITLE
It keeps showing 'wait for 30 seconds' when testing

### ISSUE THREAD

**Issue by strugglingguoguo** [open-mmlab/OpenPCDet#1075]
I want to test the data with the weights I have trained myself, but it keeps showing 'wait for 30seconds'. I can't get the result, hope to get everyone's help and answer

**Comment by sshaoshuai** [comment]
You can use the `--ckpt` to specify which checkpoint you would like to evaluate, instead of using `--eval_all`: please refer to here: https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#test-and-evaluate-the-pretrained-models
