### ISSUE TITLE
Why does training and testing nusences dataset need those non-annotation sweeps?

### ISSUE THREAD

**Issue by Raiden-cn** [open-mmlab/OpenPCDet#1079]
All annotated file (camera and LiDAR) already be put into `samples` folder.But why testing need sweeps file?
![Snipaste_2022-08-29_13-22-11](https://user-images.githubusercontent.com/82763858/187128549-e407d853-f902-4e43-a2ab-88b50192bd9b.png)
Is it related to `MAX_SWEEPS: 10` ?

**Comment by sshaoshuai** [comment]
Yes, it is. We need to concatenate 10 sweeps to predict the boxes in latest frame, since a single frame is too sparse (Please refer to the original paper of NuScene dataset).

**Comment by Raiden-cn** [comment]
Oh!I get it now, thanks!
