### ISSUE TITLE
Issue modifying feature_map_stride in ANCHOR_GENERATOR_CONFIG

### ISSUE THREAD

**Issue by GBagley** [open-mmlab/OpenPCDet#1081]
I'm trying to better understand how to appropriately modify the feature_map_stride configuration within ANCHOR_GENERATOR_CONFIG.

For example in Voxel-RCNN, this is set to 8:
https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/voxel_rcnn_car.yaml#L70

I'd like to reduce this value, but any other value I try ends up giving an error such as:
`RuntimeError: shape '[2, 5600000, -1]' is invalid for input of size 5600000`

Within anchor head template, generate_predicted_boxes. I think that something in the backbone needs to change accordingly, but I'm not understanding how the feature map stride interacts with the backbone parameters.

**Comment by jihanyang** [comment]
The feature is still downsampled to 1/8 due to the design of `BACKBONE_3D`. So if you would like to change the feature_map_stride, you also need to modify the downsampling schema in backbone.
