### ISSUE TITLE
Problem about visualization, why do these point clouds appear in two directions？

### ISSUE THREAD

**Issue by eucww** [open-mmlab/OpenPCDet#1082]
![snapshot](https://user-images.githubusercontent.com/103309725/187331447-71c7a911-8f25-4e4c-94ba-940fcd286daf.png)

**Comment by eucww** [comment]
I got this problem when I use mayavi to do visualization. Why do these point clouds appear in two directions？

**Comment by sshaoshuai** [comment]
I guess it may be the problem with your data or you simply visualize two point clouds on the same figure.
