### ISSUE TITLE
I want to count TP, FP, FN

### ISSUE THREAD

**Issue by frogbam** [open-mmlab/OpenPCDet#1083]
Hi.
I want to know how to count true positive, false positive and false negative in the eval.py.

Thanks.

**Comment by sshaoshuai** [comment]
Sorry, currently we do not have such a function to explicitly print these metrics. Actually, it is counted within different evaluation codes.

**Comment by jihanyang** [comment]
Maybe you can refer to the evluation tools about count those metrics.
https://github.com/open-mmlab/OpenPCDet/blob/b61049fc6a7ec27442317bd04efc8e306d5e14b6/pcdet/datasets/kitti/kitti_object_eval_python/eval.py#L185
