### ISSUE TITLE
Fail to download the pretrained models

### ISSUE THREAD

**Issue by ausk** [open-mmlab/OpenPCDet#1094]
The first step of `Quick Demo` is : Download the provided pretrained models as shown in the [README.md](https://github.com/open-mmlab/OpenPCDet/blob/master/README.md).

Then all the pretrained models are stored in `gdriver`. But, `Hmmm… can't reach this page ` 。 

So，请问有没有国内可下载的预训练权重地址链接呀 ？

**Comment by sshaoshuai** [comment]
Sorry, currently we do not have a cloud space to store the pre-trained models within China. Maybe you can train it by yourself. If you only need a single model, you can also email me then I can send one to you.
