### ISSUE TITLE
SST support (Embracing Single Stride 3D Object Detector with Sparse Transformer)

### ISSUE THREAD

**Issue by jlqzzz** [open-mmlab/OpenPCDet#1109]
SST is an excellent 3D detection method based on transformer, but at present there is only implementation code based on mmdetection3d. (https://github.com/tusen-ai/SST)

Can you provide SST support based on OpenPCDet?

**Comment by sshaoshuai** [comment]
It should be easy to support SST in OpenPCDet, and the most important thing you need to pay attention is to check the coordinate system between these two repos. Currently we do not have much time to do experiments with SST, maybe we will consider to support it in Nov. or Dec. this year.

**Comment by jlqzzz** [comment]
> It should be easy to support SST in OpenPCDet, and the most important thing you need to pay attention is to check the coordinate system between these two repos. Currently we do not have much time to do experiments with SST, maybe we will consider to support it in Nov. or Dec. this year.

Thanks! 
Look forward to it!
