### ISSUE TITLE
How to run multi-gpus test without slurm

### ISSUE THREAD

**Issue by KPeng9510** [open-mmlab/OpenPCDet#111]
Hi, recently I have trained the model with multi GPUs but when testing I found there is no slurm on my server. And I have no access to install it.... So can you give me some suggestions on how to run multi-gpus test without slurm just like the dist_train.sh? Thank you very much!

**Comment by sshaoshuai** [comment]
I have just supported it in https://github.com/open-mmlab/OpenPCDet/pull/114.
