### ISSUE TITLE
Large RAM memory occupation for Waymo

### ISSUE THREAD

**Issue by zen-d** [open-mmlab/OpenPCDet#1130]
Hi, when training on the Waymo Open dataset (pointpillar_1x as a simple test), OOM in RAM occurs. I checked the memory increase when launching the training script. The memory usage keeps increasing until the maximum value (The RAM used is 256G), then the launching fails. Is it normal? The Waymo dataset I downloaded is 1.4.0, could this issue be relevant to Waymo dataset version?

**Comment by jihanyang** [comment]
I have try to run on 256G with Waymo 1.2.0, and it doesn't take place such error. Would you like to try to set `pin_memory=False` in dataloader and try to decrease the workers? I am not pretty sure whether these can help.

**Comment by jihanyang** [comment]
To the best of my knowledge, waymo v1.4.0 data doesn't have any updation for object detection task compare to v1.2.0. It seems that most work still use v1.2.0 data for 3D detection. Waymo v1.4.0 mainly updates for other tasks such as segmentation which is not supported in v1.2.0.
