### ISSUE TITLE
Supported in the latest verison with `--infer_time` keyword

### ISSUE THREAD

**Issue by konyul** [open-mmlab/OpenPCDet#1131]
Supported in the latest verison with `--infer_time` keyword

_Originally posted by @jihanyang in https://github.com/open-mmlab/OpenPCDet/issues/997#issuecomment-1221464059_
      
When I used this args, some digits come out. How can I interpret this digits??

**Comment by konyul** [comment]
![image](https://user-images.githubusercontent.com/70498916/192988707-be4ff233-604d-4713-935c-bc359f191cb3.png)

**Comment by jihanyang** [comment]
These two values indicates the latency in millisecond for current iteration and the average latency among all iterations (in bracket).

**Comment by konyul** [comment]
then 117.23 means 1/0.11723 = 8.53 img / s when batch size = 1??

**Comment by jihanyang** [comment]
Yes.

**Comment by konyul** [comment]
thank you
