### ISSUE TITLE
Some mistakes：pcdet/datasets/kitti/kitti_dataset.py

### ISSUE THREAD

**Issue by WesternTrail** [open-mmlab/OpenPCDet#1132]
I ran kitti_dataSet.py to debug, and found an error：    from . import kitti_utils ImportError: attempted relative import with no known parent package。Why can't I find this bag? How should I modify or ignore this error? In fact, the code can be trained and reasoned normally

**Comment by jihanyang** [comment]
what's your command, better to follow the style of generate_kitti_infos to ensure correct import path.
