### ISSUE TITLE
Voxel information

### ISSUE THREAD

**Issue by ahmedius2** [open-mmlab/OpenPCDet#1137]
Hello! I am trying to understand what the channels of the voxel and point data represent. For example, These are the sizes of the tensors of a point cloud data sampled from nuScenes dataset with 5 sweeps:
points : torch.Size([114638, 6])                                                                                     
voxels : torch.Size([12677, 10, 5])
voxel_coords : torch.Size([12677, 4])                                                                                 
voxel_num_points : torch.Size([12677])      

My questions are:
Why points has 6 channels? 3 of them are xyz, what about the rest? The code tells something about sweep time but I couldn't understand.
Why Voxels has 5 channels? I understand that 10 is the maximum number of points in the voxel. But why voxels has 5 features and what are they?
Why voxel_coords have 4 channels instead of 3 (xyz)?

UPDATE:
The six features of the points are: (batch_idx, x, y, z, intensity, elongation).

**Comment by jihanyang** [comment]
The six channels should be [batch_size, x, y, z, intensity, timestamp]
https://github.com/open-mmlab/OpenPCDet/blob/f221374a5cb9398fd089aa7194732c808c700355/tools/cfgs/dataset_configs/nuscenes_dataset.yaml#L57-L61
