### ISSUE TITLE
Inference with pretrained NuScenes model

### ISSUE THREAD

**Issue by naranjuelo** [open-mmlab/OpenPCDet#1138]
Hi, thanks for this great work! I've run the different Kitti models with the demo script and the results look correct. Now I'm trying to use any of the models trained on NuScenes. The problem is that the results don't make any sense. 

Things I needed to change for running the inference:
- Load 5 dimensional points (x,y,z,i,t)
- Change axis order (Kitti/NuScenes differences)

Is there anything else that I need to do? I've also tried accumulating multiple sweeps, but the results are the same. Thanks in advance!

Here some examples of the inference results:
![openPCdet](https://user-images.githubusercontent.com/14231593/194276243-12666c43-4c98-42a9-883d-881dad4db738.png)

![openPCdet2](https://user-images.githubusercontent.com/14231593/194276258-f63ee088-ea06-4ceb-b5d8-e6e5792b7632.png)

**Comment by jihanyang** [comment]
I think you can refer to a domain adaptation repo [ST3D](https://github.com/CVMI-Lab/ST3D). 
You also need to move the point cloud along z-axis, and remove intensity. ST3D++ also provide accumulate sweeps results for multi-sweeps nuscenes to KITTI.
