### ISSUE TITLE
Very large RAM occupation for MPPNET.

### ISSUE THREAD

**Issue by sjtuljw520** [open-mmlab/OpenPCDet#1142]
The RAM occupation seems very large for mppnet. When I set the num_of_workers as 2 and trained the model on 2 GPU (batch_size_per_gpu = 4), 480GiB RAM is work out, the program is killed as OOM. Is this normal? And, depend on your experience, how much RAM needed to train MPPNET.

**Comment by Cedarch** [comment]
Hi, we train MPPNet with batch_size_per_gpu = 2 and 512G RAM is enough.  You can try this setting.

**Comment by sjtuljw520** [comment]
Thanks for replying. I am doubt why the model cosume so much RAM. Does the dataloader load all the data at once, instead of batch by batch? @Cedarch

**Comment by xpyqiubai** [comment]
I train MPPNet with batch_size_per_gpu = 2 and 240G RAM is enough.

**Comment by sjtuljw520** [comment]
Thank you! What is the number of workers you set? I set batch_size_per_gpu =2, and num_of_workers = 1. However, 512G RAM is till not enough.  @xpyqiubai 
BTW, I trained the model in one GPU.

**Comment by Cedarch** [comment]
The dataloader just load data by batch and each item contains 4-frame concated point clouds. It actually cost larger RAM than single frame setting but, for our experience, 512G RAM is enough, @sjtuljw520.

**Comment by sjtuljw520** [comment]
I retrain the model with new version of waymo dataset (the dataset vesion I used before is v1.1). Now this problem has been solved. 120G RAM is enough. Thank you @Cedarch
