### ISSUE TITLE
220GB RAM cannot run 20%  waymo dataset.

### ISSUE THREAD

**Issue by laokuku** [open-mmlab/OpenPCDet#1144]
Hi,
Devices with 220GB RAM and 4*3090 cannot run CenterPoint even though each GPU has only one batch size of waymo dataset. 
My devices and environment  is as follows:
```
4 RTX 3090
220 GB RAM
Xeon E5 12
Ubuntu 18.04
torch 1.9
waymo-open-dataset-tf-2-0-0
```
When I run any model, the waymo dataloader will gradually fill up the memory (220GB) before running the training code,  as follows:
![1665490623545](https://user-images.githubusercontent.com/70059098/195087600-fa2be532-3b15-472a-9944-cdf12d7be01b.png)

However,  when we only train 5% of the dataset, the code can run.

**Comment by jihanyang** [comment]
whether issue #1130 can help?
