### ISSUE TITLE
mask_points_by_range not using z

### ISSUE THREAD

**Issue by ahmedius2** [open-mmlab/OpenPCDet#1145]
The method "def mask_points_by_range(points, limit_range)" in pcdet/utils/common_utils.py is only filtering with respect to X and Y point cloud range limits but not Z. Is this on purpose? The Z axis of point cloud ranges in configuration files appears ineffective.

**Comment by sshaoshuai** [comment]
I guess this will not affect the final performance much, and you can also filter the z-axis.
