### ISSUE TITLE
There are some errors when using the train.py

### ISSUE THREAD

**Issue by oneway3124** [open-mmlab/OpenPCDet#1151]
When I use the following command,
`python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml `

The error informations are as following,
`Traceback (most recent call last):
  File "train.py", line 221, in <module>
    main()
  File "train.py", line 111, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "../pcdet/datasets/__init__.py", line 53, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "../pcdet/datasets/kitti/kitti_dataset.py", line 23, in __init__
    super().__init__(
  File "../pcdet/datasets/dataset.py", line 30, in __init__
    self.data_augmentor = DataAugmentor(
  File "../pcdet/datasets/augmentor/data_augmentor.py", line 23, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "../pcdet/datasets/augmentor/data_augmentor.py", line 27, in gt_sampling
    db_sampler = database_sampler.DataBaseSampler(
  File "../pcdet/datasets/augmentor/database_sampler.py", line 35, in __init__
    sampler_cfg.DB_INFO_PATH[0] = sampler_cfg.BACKUP_DB_INFO['DB_INFO_PATH']
AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'
(OpenPCDet-ww) lijiadi@lijiadi-Z490-UD:~/wangwei/OpenPCDet/tools$ `

Can you help me with this error?

**Comment by Chris-ctrl123** [comment]
I have the same error

**Comment by Chris-ctrl123** [comment]
This error disappeared when I used ‘python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml’ to generate a dictionary of KITTI data

**Comment by oneway3124** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/1150  Please see this issue.

**Comment by xuchangjia** [comment]
I have same probelm as you,i just cd tools/ then run python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml.finally i fix it .

**Comment by oneway3124** [comment]
How to fix it? I cannot understand it.

**Comment by xuchangjia** [comment]
> 
应该是路径问题，我切到tools路径下运行不报错，运行python tools/train.py ××× 就报这个错。

**Comment by oneway3124** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/1150   @xuchangjia Did you have a smiliar issue?

**Comment by SkywalkerHe** [comment]
I have same question :AttributeError:` 'EasyDict' object has no attribute 'BACKUP_DB_INFO'`,when I run
`$  bash scripts/dist_train.sh ${NUM_GPUS} --cfg_file cfgs/waymo_models/centerpoint_4frames.yaml`

**Comment by Anutlet** [comment]
> > 
> 
> 应该是路径问题，我切到tools路径下运行不报错，运行python tools/train.py ××× 就报这个错。

我切到tools路径下，也还是报错，我跑的nuscense v1.0_mini
