### ISSUE TITLE
Unresolved reference 'pointnet2_stack_cuda' 

### ISSUE THREAD

**Issue by 910399614** [open-mmlab/OpenPCDet#1152]
I try to debug Voxel-RCNN and I find a unresolved reference 'pointnet2_stack_cuda' in the voxel_query_utils.py. But the method of this reference that 'voxel_query_wrapper()' was executed successfully.

![(5A~)2ZX_{2_3RNOMFKBY41](https://user-images.githubusercontent.com/60724761/196694167-bcd27919-2406-4132-8e2a-84a1f6e2dca9.png)
![G155({T$MT6E7@}_$P$ {57](https://user-images.githubusercontent.com/60724761/196694177-6c8062bb-0849-4c4c-b80c-49d97d33e6bf.png)

**Comment by 910399614** [comment]
> 

It’s difficult to say, but all commands I have run are following official steps

**Comment by jihanyang** [comment]
I mean whether you try to run any models and meet with errors?

**Comment by 910399614** [comment]
> I mean whether you try to run any models and meet with errors?

I have not met any errors, and the model 'Voxel_RCNN' was run successfully, but I want to know the details of method 'voxel_query_wrapper()'.

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/f221374a5cb9398fd089aa7194732c808c700355/pcdet/ops/pointnet2/pointnet2_stack/src/pointnet2_api.cpp#L14

**Comment by 910399614** [comment]
Thanks for your help
&nbsp;


姜仪东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/OpenPCDet] Unresolved reference &#39;pointnet2_stack_cuda&#39;  (Issue #1152)





 
https://github.com/open-mmlab/OpenPCDet/blob/f221374a5cb9398fd089aa7194732c808c700355/pcdet/ops/pointnet2/pointnet2_stack/src/pointnet2_api.cpp#L14
