### ISSUE TITLE
Can realize MOT by using this codebase? 

### ISSUE THREAD

**Issue by sjtuljw520** [open-mmlab/OpenPCDet#1155]
For example, realize the similar MOT (multi object tracking) results as in the centerpoint paper.
If can, any suggestion that how to use this codebase?

**Comment by jihanyang** [comment]
I haven't tried to realize MOT on pcdet, but I think https://github.com/tusen-ai/SimpleTrack is a good candidate heard from other researchers.

**Comment by sjtuljw520** [comment]
OK, thanks you! @jihanyang
