### ISSUE TITLE
image and pointcloud data alignment

### ISSUE THREAD

**Issue by bing0037** [open-mmlab/OpenPCDet#1159]
Using [kitti_object_vis](https://github.com/kuixu/kitti_object_vis), we can visualize pointcloud and image seperately. Is it possible to obtain pointcloud Frustum from 2D image label using calib infos?

**Comment by jihanyang** [comment]
Yes, you can refer to the code here https://github.com/open-mmlab/OpenPCDet/blob/f221374a5cb9398fd089aa7194732c808c700355/pcdet/datasets/kitti/kitti_dataset.py#L310-L315
