### ISSUE TITLE
Projection 3D BB from point cloud to image

### ISSUE THREAD

**Issue by Townjj** [open-mmlab/OpenPCDet#1167]
Hello,
thanks for excellent work.
I successfully run demo.py in PCDct, visuling the 3D Boundding box in point cloud scene. And I want to konw does PCDet implement the ability to project 3D Bounding Box from the point cloud scene into the image 3D Bounding Box? And how can i use it?
thanks.

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/1159 This might be helpful

**Comment by Townjj** [comment]
Thanks. Solved.
