### ISSUE TITLE
how to run demo with docker?

### ISSUE THREAD

**Issue by WuYanXingege** [open-mmlab/OpenPCDet#1168]
i find docker hasn't tools/demo.py

**Comment by jihanyang** [comment]
I haven't try to run openpcdet on docker. Hope others can help you.

**Comment by Townjj** [comment]
I have run demo.py in docker successfully. demo.py don't exist in docker may be the file sync proble between CONTAINER and LOCALHOST. Check your script when build your container:

-v /LocalDir:ContainerDir

**Comment by WuYanXingege** [comment]
thank you！



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 11, 2022 13:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/OpenPCDet] how to run demo with docker? (Issue #1168)




 
I have run demo.py in docker successfully. demo.py don't exist in docker may be the file sync proble between CONTAINER and LOCALHOST. Check your script when build your container:
 
-v /LocalDir:ContainerDir

**Comment by MooooNSC** [comment]
you need GUI setting

Try 

nvidia-docker run -it --gpus 'all,"capabilities=compute,utility,graphics"' --name &{name} -e DISPLAY=unix$DISPLAY --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" --volume="/etc/sudoers.d:/etc/sudoers.d:ro" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" &{IMAGE_ID}

**Comment by vikasnr** [comment]
> 
When I try to run demo.py it can't import pcdet

`from pcdet.config import cfg, cfg_from_yaml_file
ModuleNotFoundError: No module named 'pcdet'
`

In the [`installation guide`](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md) as per the note
pcdet needs to installed.
"NOTE: Please re-install` pcdet v0.5` by running `python setup.py develop` even if you have already installed previous version."

Did you install pcdet? How did you do it through Dockerfile?

**Comment by ShioHZY** [comment]
> > 
> 
> @Townjj @MooooNSC @WuYanXingege
> 
> When I try to run demo.py it can't import pcdet
> 
> `from pcdet.config import cfg, cfg_from_yaml_file ModuleNotFoundError: No module named 'pcdet' `
> 
> In the [`installation guide`](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md) as per the note pcdet needs to installed.
> 
> "NOTE: Please re-install `pcdet v0.5` by running `python setup.py develop` even if you have already installed previous version."
> 
> Did you install pcdet? How did you do it through Dockerfile?
> 
> Any idea how to run docker in non-interactive mode (installation of dependencies like pcdet has to be through Dockerfile)?

@vikasnr 
hi, i met the same problem. i pull the docker image directly, and i can't import pcdet. should i install it by myself? have you solved it? any reply is appreciated.
