### ISSUE TITLE
More configs and pre-trained models on nuScenes dataset?

### ISSUE THREAD

**Issue by Eaphan** [open-mmlab/OpenPCDet#1169]
Do you have any plan to provide configs and pre-trained models on nuScenes data, for the popular detectors like voxel r-cnn, and PV-RCNN? Is the configuration not released because the model is not enough on nuScenes data? It's mentioned in #1084 that the voxel-rcnn does not perform well on nuScenes dataset.
@jihanyang Thanks for your reply in advance.

**Comment by jihanyang** [comment]
Actually, one stage detectors are more popular and high-performance on nuscenes, so we don't suppot them on nuscenes.
