### ISSUE TITLE
Trouble with custom dataset evaluation, 3d and bev AP is 0

### ISSUE THREAD

**Issue by Encycloquandia** [open-mmlab/OpenPCDet#1178]
First I would like to thank you for this project, I had a query regarding training using our own dataset. 
My annotations are corresponding to the axis of the point cloud, and I use cenerpoint as my model. But when evaluation, the results of 3d and bev AP are ZERO, while bbox and aos are not zero, and i don't know why. The screenshot is below.

<img width="906" alt="9adc2fbbe75a5581a9a43f4759a513c" src="https://user-images.githubusercontent.com/50581572/201116640-fbd44918-98c5-4422-93ff-9d27bcec75bf.png">

And i use dmo.py to visualize the result, the blue boxs are the gt_boxes and the green boxes are the pred_boxes, I wonder why the green boxes are neat and well above the ground.

![3ac556169e306a53dce8a0c6e3eac18](https://user-images.githubusercontent.com/50581572/201116657-0ad0c0fd-1f3d-495a-bd4d-7a2fc2564238.jpg)

Is there anyone who could guide me as to how to do it,
Thanks for your  help!!!

**Comment by Encycloquandia** [comment]
有没有哪位大佬可以教教！使用官方提供的custom代码训练自己数据时候，在评估的时候发现3d和bev指标都是0，而2d的指标是有数值的，使用demo.py可视化的结果发现预测的框是整齐的一排，而且是远高于地面的，是因为我的标签设置有问题吗？但是模型参数不对呢？

**Comment by SweetBittErz** [comment]
Hello, I want to realize the evaluation of custom data set during training, but the program reports an error. I want to guide how to modify evaluation () function in custom_ dataset.py allows it to evaluate custom datasets. My dataset is labeled according to the kitti format, but I do not have calib, so you can understand that, except for xyzwhl class and angle, all other parameters are 0

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by S-kewen** [comment]
Hello, I have a similar problem, we try to label our dataset (KITTI-format) in Carla simulator for evaluation, but we found that the AP results are all 0.00

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by S-kewen** [comment]
> > First I would like to thank you for this project, I had a query regarding training using our own dataset. My annotations are corresponding to the axis of the point cloud, and I use cenerpoint as my model. But when evaluation, the results of 3d and bev AP are ZERO, while bbox and aos are not zero, and i don't know why. The screenshot is below.
> > <img alt="9adc2fbbe75a5581a9a43f4759a513c" width="906" src="https://user-images.githubusercontent.com/50581572/201116640-fbd44918-98c5-4422-93ff-9d27bcec75bf.png">
> > And i use dmo.py to visualize the result, the blue boxs are the gt_boxes and the green boxes are the pred_boxes, I wonder why the green boxes are neat and well above the ground.
> > ![3ac556169e306a53dce8a0c6e3eac18](https://user-images.githubusercontent.com/50581572/201116657-0ad0c0fd-1f3d-495a-bd4d-7a2fc2564238.jpg)
> > Is there anyone who could guide me as to how to do it, Thanks for your help!!!
> 
> 你成功了吗，我也想训练自己的点云数据。

没有，训练多次失败之后放弃了

**Comment by ghb0224** [comment]
> > > 首先，我要感谢您的这个项目，我有一个关于使用我们自己的数据集进行训练的查询。我的注释对应于点云的轴，我使用cenerpoint作为我的模型。但是在评估时，3d和bev AP的结果为零，而bbox和aos的结果不为零，我不知道为什么。截图如下。 <img alt="9adc2fbbe75a5581a9a43f4759a513c" width="906" src="https://user-images.githubusercontent.com/50581572/201116640-fbd44918-98c5-4422-93ff-9d27bcec75bf.png">我用 dmo.py 来可视化结果，蓝色的盒子是gt_boxes的，绿色的盒子是pred_boxes的，我想知道为什么绿色的盒子很整齐，远远高于地面。 ![3ac556169e306a53dce8a0c6e3eac18](https://user-images.githubusercontent.com/50581572/201116657-0ad0c0fd-1f3d-495a-bd4d-7a2fc2564238.jpg)有没有人可以指导我如何做，谢谢你的帮助!!!
> > 
> > 
> > 你成功了吗，我也想训练自己的点云数据。
> 
> 没有，训练多次失败之后放弃了
你好，我想查看我的评价指标，该如何操作？

**Comment by ghb0224** [comment]
> First I would like to thank you for this project, I had a query regarding training using our own dataset. My annotations are corresponding to the axis of the point cloud, and I use cenerpoint as my model. But when evaluation, the results of 3d and bev AP are ZERO, while bbox and aos are not zero, and i don't know why. The screenshot is below.
> 
> <img alt="9adc2fbbe75a5581a9a43f4759a513c" width="906" src="https://user-images.githubusercontent.com/50581572/201116640-fbd44918-98c5-4422-93ff-9d27bcec75bf.png">
> 
> And i use dmo.py to visualize the result, the blue boxs are the gt_boxes and the green boxes are the pred_boxes, I wonder why the green boxes are neat and well above the ground.
> 
> ![3ac556169e306a53dce8a0c6e3eac18](https://user-images.githubusercontent.com/50581572/201116657-0ad0c0fd-1f3d-495a-bd4d-7a2fc2564238.jpg)
> 
> Is there anyone who could guide me as to how to do it, Thanks for your help!!!

你好，我想查看我的评价指标，该如何操作？目前已经训练、验证完成

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
