### ISSUE TITLE
cur_gt[k].sum() == 0

### ISSUE THREAD

**Issue by hjfenghj** [open-mmlab/OpenPCDet#1182]
what the code "        while k > 0 and cur_gt[k].sum() == 0: # 找到cur_gt[k].sum() != 0的这一位 " means  in the file named "detector3d_template.py"?
![image](https://user-images.githubusercontent.com/72334253/201641235-e4678e78-a0e0-4ad4-92bb-deb59067d456.png)

**Comment by jihanyang** [comment]
This is to remove the padded gt_boxes in the collate batch
https://github.com/open-mmlab/OpenPCDet/blob/028ed72eb5df413cf33ca7091b1a977495cc700c/pcdet/datasets/dataset.py#L213-L219
