### ISSUE TITLE
pointpillars infer_time

### ISSUE THREAD

**Issue by cat722** [open-mmlab/OpenPCDet#1184]
Hello. When I test the pointpillars using "--infer_time", I find the average fps is only 9, it's very slow.  Can anyone help me? Thanks!
![2{AGJ15A(9DR5~)P5CPX4MJ](https://user-images.githubusercontent.com/58463987/201819501-fcda07d5-91cc-45c5-8214-ccfb5c1775a4.png)

**Comment by konyul** [comment]
when I run the following model, I get similar results.
