### ISSUE TITLE
About Voxel R-CNN to onnx

### ISSUE THREAD

**Issue by DZ2584793260** [open-mmlab/OpenPCDet#1186]
Hello, author! I am learning relevant content recently. I am currently trying to convert an Openpcdet-based model to onnx format, I refer to tools.test.py, but I am not sure how to write a few parameters.

model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=test_set)
model.load_params_from_file(filename=cur_ckpt, logger=logger, to_cpu=dist_test)
model.cuda()

so the dummy_input = ???
torch.onnx.export(model, dummy_input, "voxel_rcnn.onnx", opset_version=10, verbose=True, do_constant_folding=True)

**Comment by Manishpandey-0** [comment]
@DingZ0115 were you able to convert voxel R-CNN to onnx ?
