### ISSUE TITLE
Multi-GPU Training error that related "LOCAL_RANK"

### ISSUE THREAD

**Issue by lejk8104** [open-mmlab/OpenPCDet#1191]
Hello,
I'm trying to training PillarNet
I have same error during training 8 Nvidia Titan X GPUs

In my set-up
- OpenPCDet v0.6.0
- Batch size per gpu: 2
- Epochs: 36
- Cuda: 11.6
- cuDNN: 8.2.0
- pytorch: 1.13.0

Error message
![Screenshot from 2022-11-19 12-13-55](https://user-images.githubusercontent.com/41908895/202831565-636542ee-040e-4529-85cb-67b6071839f0.png)
 

Error message
![Screenshot from 2022-11-19 12-12-43](https://user-images.githubusercontent.com/41908895/202831531-a16a7327-679b-47fc-b799-4e56fbeba678.png)

Error message
![Screenshot from 2022-11-19 12-02-09](https://user-images.githubusercontent.com/41908895/202831495-a27be603-b36f-4dbe-9f7b-162d4eb01471.png)

Hope others can help you.

**Comment by Townjj** [comment]
What 's your train script? Did you use launch item?
