### ISSUE TITLE
Release of MPPNet checkpoint

### ISSUE THREAD

**Issue by kcyu2014** [open-mmlab/OpenPCDet#1205]
Hi,

Thanks for the amazing work and open-source the MPPNet! 

In the readme file of MPPNet, there is a section of evaluating the pretrained model. However, I have checked several places but haven't found the download link for this pretrained model. I am not sure if I miss something, but is there any chance that you could provide a pretrained model for quick evaluation?

Best regards,
Kaicheng

**Comment by jihanyang** [comment]
If you are asking for the waymo pretrained models, we cannot release them publicly according to Waymo license. You can directly email to xuesong @Cedarch for the pretrained model for academic purpose.

**Comment by Cedarch** [comment]
Hi kcyu2014, sorry for late reply. The eamil is correct and I will reorganize the ckpt to you as soon as possible (the released code is reorganized and my original ckpt can not be directly loaded).

**Comment by kcyu2014** [comment]
Thanks for the update! Sure I can wait until it's ready.



Cedarch ***@***.***> 于2022年12月6日周二 11:29写道：

**Comment by Cedarch** [comment]
Hi kcyu2014,  if you don't receive the model of MPPNet, you can email to me (chenxuesong@link.cuhk.edu.hk). I am not sure whether I have sent the link to  you  :).
