### ISSUE TITLE
data preprocessor 

### ISSUE THREAD

**Issue by konyul** [open-mmlab/OpenPCDet#1218]
when we use mask_points_and_boxes_outside_range in data_processor
why don't we mask points that exceed range of z-axis?? is there any reason for this??

![Screenshot from 2022-12-14 12-25-54](https://user-images.githubusercontent.com/70498916/207497926-830f9edf-13f4-486c-bace-2f4a69a5ef6a.png)

**Comment by jihanyang** [comment]
#1145 Check whether this can help.

**Comment by konyul** [comment]
thank you for the answer
