### ISSUE TITLE
train pvrcnn with custom_dataset generate error: helper_launch.h 17 N>0 assert failed. CUDA kernel launch blocks must be postive,but got N=0.

### ISSUE THREAD

**Issue by SweetBittErz** [open-mmlab/OpenPCDet#1219]
I want to train pvrcnn with custom_dataset，but it generate error follow this:
first，error: size mismatch -----> modify voxel_size make it can be div by 16/40
when i modified:
second, error: Expected more than 1 value per channel when training,got input size torch.size([1,256,1,1])
i want know how to solve it?

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BBAKY** [comment]
Did you find the solution?

**Comment by SweetBittErz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
