### ISSUE TITLE
Why execute the same code for the same frame of data but get different detection results?

### ISSUE THREAD

**Issue by wangxiyang2022** [open-mmlab/OpenPCDet#1221]
Thank you for your great work in making the OpenPCDet project available for 3D object detection.

When I used PointRCNN to test the same frame of data, I found that the detection results obtained in each run were different.

For example, the detection results I got when I executed the code for the first time are as follows:

![image](https://user-images.githubusercontent.com/71493146/208351723-6ab441e4-d2d0-464f-aeab-118054627268.png)

But when I re-execute the code, I get the following detection results:

![image](https://user-images.githubusercontent.com/71493146/208352224-1665269f-1308-4f26-80ec-8c86c9a660b3.png)

Why execute the same code for the same frame of data but get different detection results?

**Comment by jihanyang** [comment]
May I know the command you execute?

**Comment by wangxiyang2022** [comment]
Thanks for your reply, here is my command：

`python demo.py --cfg_file cfgs/kitti_models/pointrcnn.yaml --ckpt pointrcnn_7870.pth --data_path /home/wangxiyang/Desktop/code_test/DetMOT/data/KITTI/tracking/train/velodyne/0000/000000.bin
`

**Comment by jihanyang** [comment]
please try to fix the random seed of numpy in demo.py as test.py does.

**Comment by wangxiyang2022** [comment]
I found that a fixed number of point clouds were randomly selected during data preprocessing.

![image](https://user-images.githubusercontent.com/71493146/208562757-28100a8f-bdaa-430c-aa98-2d92c9aa92e7.png)

 Since the point clouds selected each time are random, the final detection results will also be different. Why is it needed in the testing phase?
