### ISSUE TITLE
Explanation needed for Evaluation

### ISSUE THREAD

**Issue by barzanisar** [open-mmlab/OpenPCDet#1226]
Hey,
I have a question concerning these lines of [code](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/utils/box_utils.py#L215-L216).

Why do we shift z coordinate of box center to the bottom before transforming it in camera frame?

After transforming in camera frame, does it mean xyz_cam has: 
[x coordinate of box center, y coordinate of the **bottom** of the box, and z coordinate of the center of the box]?

**Comment by qiutiantxwd** [comment]
I believe this issue open-mmlab/OpenPCDet#128 is about the conversion from kitti cam to unified coordinates for lidar in pcdet, which is in opposite direction to what you are asking
And xyz_cam should mean the [x, y, z] coordinates of the bottom center of the bounding box in camera coordinates.
