### ISSUE TITLE
Extract point cloud data from tfrecord and generate data infos but showed 'Killed'

### ISSUE THREAD

**Issue by XiaoyanQian** [open-mmlab/OpenPCDet#1240]
![image](https://user-images.githubusercontent.com/16057913/212546465-8946ba89-c376-48ed-89c6-1c1d4d10264b.png)

when run the" python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos \
    --cfg_file tools/cfgs/dataset_configs/waymo_dataset_multiframe.yaml", my server showed the "killed" in the pic. 

Anyone could tell me why it will be killed.

**Comment by adv010** [comment]
Must be running out of memory when data is being loaded

**Comment by XiaoyanQian** [comment]
> 

Thank you so much. Do you know how many memories it would be open to when loading the data?

**Comment by XiaoyanQian** [comment]
> Must be running out of memory when data is being loaded

I have more than 500G left； logically, there might be enough for loading data. 

![image](https://user-images.githubusercontent.com/16057913/212794779-81f738ff-ec3d-4fe5-b875-d36ce3bb51c3.png)

**Comment by qifeng22** [comment]
hello,do you know how many memories it would be open to when loading the data?

**Comment by HaoranZhuExplorer** [comment]
> > Must be running out of memory when data is being loaded
> 
> I have more than 500G left； logically, there might be enough for loading data.
> 
> ![image](https://user-images.githubusercontent.com/16057913/212794779-81f738ff-ec3d-4fe5-b875-d36ce3bb51c3.png)

actually it's 50GB. so maybe it's not enough.

**Comment by imy0ung** [comment]
@XiaoyanQian 
Hi, have you fixed this issue? I'm experiencing the same error. I'm using 32gb ram, and I'd like to ask if it's possible to experiment with that memory.
