### ISSUE TITLE
missing custom_dataset.yaml file under dataset_configs

### ISSUE THREAD

**Issue by Allamrahul** [open-mmlab/OpenPCDet#1246]
Hi, I am unable to spot the custom_dataset.yaml file in the repo. Could someone provide it? I have the raw point cloud data in npy format and the labels in the unified format.

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/custom_dataset.yaml

**Comment by Allamrahul** [comment]
Thanks. I was on the wrong branch.
