### ISSUE TITLE
How can I evaluate model based on test set of Once dataset?

### ISSUE THREAD

**Issue by Eaton2022** [open-mmlab/OpenPCDet#1248]
When I try to evaluate model based on test set of Once dataset, the log information shows that the total number of Once dataset is 0.  That is weird.

**Comment by dyzxzeng** [comment]
ONCE dataset has no annos in test split. According to ONCE official website(https://once-for-auto-driving.github.io/), the test results can be obtained from codalab. But codalab stops their old servers several months ago. Till now I have no idea where to submit result

**Comment by Eaton2022** [comment]
> ONCE dataset has no annos in test split. According to ONCE official website(https://once-for-auto-driving.github.io/), the test results can be obtained from codalab. But codalab stops their old servers several months ago. Till now I have no idea where to submit result

Thanks for your kindly reply.

**Comment by Eaton2022** [comment]
> ONCE dataset has no annos in test split. According to ONCE official website(https://once-for-auto-driving.github.io/), the test results can be obtained from codalab. But codalab stops their old servers several months ago. Till now I have no idea where to submit result

Thanks for your kind reply.
