### ISSUE TITLE
Train my own dataset with model pointpillars

### ISSUE THREAD

**Issue by JiyuanWANG12138** [open-mmlab/OpenPCDet#1249]
When I trained my own dataset, the result is poor, and I can detect some cars far from base but I can't detect the cars closed to the base... What I should change the config file to make the result better? My point cloud is bigger than kittis', so I used a bigger point cloud range.

**Comment by jihanyang** [comment]
You can set the point cloud range to you need. It will be good to make sure the annotation is correct first with visualization.
