### ISSUE TITLE
Why was generate_prediction_dicts removed?

### ISSUE THREAD

**Issue by demmerichs** [open-mmlab/OpenPCDet#1251]
This [commit](https://github.com/open-mmlab/OpenPCDet/pull/1072/commits/cb1ecefaa38a763ef7d3e0de22fb36c89f21509b#diff-5789607a7a6345aa13d6c317b67cf8b2d502a5b80e44eb51dc9e6847ec0c8c5b) cb1ecefaa38a763ef7d3e0de22fb36c89f21509b removed the generate_prediction_dicts from 3 dataset classes (Waymo, nuScenes and Lyft). What was the reason for this? It breaks the test.py trying to execute this function and instead calling the empty base Dataset class function returning None. @jihanyang this was your commit it seems, could you shed some light on this?

**Comment by jihanyang** [comment]
Check dataset.py
