### ISSUE TITLE
The purpose of taking max() on recall during KITTI evaluation?

### ISSUE THREAD

**Issue by qiutiantxwd** [open-mmlab/OpenPCDet#1254]
When computing the PR curve for KITTI evaluation, precision at each recall point is replaced with the maximum from this point onwards. 
My question is why is same operation done on recall? 
Also, I think throughout the code the returned `ret_dict['recall']` is never used. Can someone explain, thanks. 
https://github.com/open-mmlab/OpenPCDet/blob/31f6758af378c20e6200cd8e16307b1afa8c8a42/pcdet/datasets/kitti/kitti_object_eval_python/eval.py#L542-L560

**Comment by Kh-Hamed** [comment]
Have you found the answer? this is my question as well.
