### ISSUE TITLE
Projection of once dataset boxes3d to the unified frame of openpcdet

### ISSUE THREAD

**Issue by OrangeSodahub** [open-mmlab/OpenPCDet#1256]
I noticed that in `once_dataset` of openpcdet there is no operation on the `loc`, `yaw` of annotated boxes3d, which means their original coordinate system is identical with the openpcdet's.
But according to the following:

![2023-02-04 23-26-25屏幕截图](https://user-images.githubusercontent.com/54439582/216775582-6dd235f3-b5f2-4d38-adbb-9a1fe57030b5.png)

the vehicle heading is right, shouldn't the unified coordinate is:
```
y                           x
|                           |
|                           |
z-----------x    y----------z
(openpcdet)   (once lidar)
```
How could these two be the same?

**Comment by mx2013713828** [comment]
你好，请问你搞明白了吗？openpcdet和once的坐标系到底是什么样的呀？

**Comment by Petros626** [comment]
@mx2013713828 unified coordinate system of OpenPCDet is described, for the dataset the documentation of it should provide the information you need

**Comment by Petros626** [comment]
@OrangeSodahub that's strange, bc every dataset without the OpenPCDet coordinate system should be transformed. @sshaoshuai
