### ISSUE TITLE
Empty pred_dicts and ret_dicts after evaluating trained custom model (default pv_rcnn config)

### ISSUE THREAD

**Issue by WinckelData** [open-mmlab/OpenPCDet#1258]
Hey,

i am currently working on implementing a CARLA based dataset into your framework.

I think i created the custom dataset correctly, with unified coordinates in the correct format.

To confirm that everything works, i wanted to train some models from scratch and evaluate their performance.

The tensorboard graphs for the training-loss during the first 2 epochs look fine, but when i try evaluating models from the first or 2nd epoch i get empty pred_dicts and ret_dicts when forward passing in the data.

![image](https://user-images.githubusercontent.com/70024382/217026527-5ef2042f-6934-4193-90f3-3e095b9f470d.png)

Any idea what could cause that issue and how to fix this?

I would be glad to provide more useful information regarding my setup.

Best, Luis

**Comment by dansimaa** [comment]
Hi Luis, were you able to solve the problem?
