### ISSUE TITLE
Can I directly use the pretrained model to predict my own data?

### ISSUE THREAD

**Issue by tub-sgg** [open-mmlab/OpenPCDet#1260]
I want to direcltly use the pretrained model(i.e, the pretrained model is based on KITTI dataset), I also collected my own point cloud data( here only one frame maybe). Now i want check whether the model works or not.
if i directly use my own data, nothing could be detected.
So, what should I do to deal with my own data or some other configs
![Screenshot from 2023-02-08 14-12-17](https://user-images.githubusercontent.com/44619635/217539709-12c766ae-53be-4de5-a20a-26919b3c81c3.png)

**Comment by jihanyang** [comment]
Please refer to the source only results of UDA repo such as ST3D.

**Comment by aminzadenoori** [comment]
Also this is my question too.

can you please explain on more details how can I use pretrained model to extract bounding boxes of cars on 3d point clouds?
