### ISSUE TITLE
the evaluation result of my own dataset is strange

### ISSUE THREAD

**Issue by RouDanCongJii** [open-mmlab/OpenPCDet#1264]
i have only lidar info.
why me recall_riou = 0.
2023-02-13 19:02:19,210   INFO  recall_roi_0.3: 0.000000
2023-02-13 19:02:19,210   INFO  recall_rcnn_0.3: 0.909935
2023-02-13 19:02:19,211   INFO  recall_roi_0.5: 0.000000
2023-02-13 19:02:19,212   INFO  recall_rcnn_0.5: 0.845584
2023-02-13 19:02:19,212   INFO  recall_roi_0.7: 0.000000
2023-02-13 19:02:19,212   INFO  recall_rcnn_0.7: 0.648939

why there is part of value = 0 and some value of 3d is too low.
people AP@0.70, 0.70, 0.70:
bev  AP:74.3272, 74.3272, 74.3272
3d   AP:17.4228, 17.4228, 17.4228
people AP@0.70, 0.50, 0.50:
bev  AP:87.3524, 87.3524, 87.3524
3d   AP:75.9252, 75.9252, 75.9252
car AP@0.50, 0.50, 0.50:
bev  AP:0.1137, 0.1137, 0.1137
3d   AP:0.0000, 0.0000, 0.0000
car AP@0.50, 0.25, 0.25:
bev  AP:74.5911, 74.5911, 74.5911
3d   AP:1.5584, 1.5584, 1.5584
bicycle AP@0.50, 0.50, 0.50:
bev  AP:1.1097, 1.1097, 1.1097
3d   AP:0.0000, 0.0000, 0.0000
bicycle AP@0.50, 0.25, 0.25:
bev  AP:85.8572, 85.8572, 85.8572
3d   AP:39.7278, 39.7278, 39.7278
motorcycle AP@0.70, 0.70, 0.70:
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
motorcycle AP@0.70, 0.50, 0.50:
bev  AP:4.4343, 4.4343, 4.4343
3d   AP:0.0000, 0.0000, 0.0000
bus AP@0.50, 0.50, 0.50:
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
bus AP@0.50, 0.25, 0.25:
bev  AP:52.1141, 52.1141, 52.1141
3d   AP:30.3129, 30.3129, 30.3129
truck AP@0.70, 0.70, 0.70:
bev  AP:87.8465, 87.8465, 87.8465
3d   AP:54.8313, 54.8313, 54.8313
truck AP@0.50, 0.50, 0.50:
bev  AP:88.9068, 88.9068, 88.9068
3d   AP:87.7835, 87.7835, 87.7835

**Comment by ghb0224** [comment]
关于评价指标这里，我有些问题想咨询，可以留一下邮箱吗
