### ISSUE TITLE
Some errors occurred when run comand 'python setup.py develop'

### ISSUE THREAD

**Issue by jingyi-zhang** [open-mmlab/OpenPCDet#127]
Hi, Shaoshuai~
Thanks for your code~
When I wanna run  comand 'python setup.py develop', some errors occurred
Here attached the error
[error.txt](https://github.com/open-mmlab/OpenPCDet/files/4877557/error.txt)

**Comment by sshaoshuai** [comment]
What are your PyTorch version, GCC version and CUDA version?

**Comment by sshaoshuai** [comment]
I will close it now since there is no response. Feel free to re-open it.
