### ISSUE TITLE
if i want to evaluate the nuscenes test-dataset. Should i download the entire dataset or only the test-dataset

### ISSUE THREAD

**Issue by RouDanCongJii** [open-mmlab/OpenPCDet#1272]

**Comment by zbaishancha** [comment]
@RouDanCongJii Hi, do you know how to solve this problem? Also, I would like to ask if you know how to use own model to go about predicting and saving the results in the nuscenes test dataset? I would like to submit it to the official nuscenes website and look forward to your reply!
