### ISSUE TITLE
Compiling with different versions of PyTorch 

### ISSUE THREAD

**Issue by aminzadenoori** [open-mmlab/OpenPCDet#1275]
I have installed the pytroch 1.13.1 but I have  this error:

RuntimeError:
The detected CUDA version (11.8) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.

what can I do?

**Comment by XYX1998** [comment]
Hey, Can you please tell me how to sovle this error, I've encountered this problem too , Thanks
