### ISSUE TITLE
Can't find algo

### ISSUE THREAD

**Issue by aminzadenoori** [open-mmlab/OpenPCDet#1276]
I face this error during running the demo.py 

2023-02-20 11:54:32,397   INFO  -----------------Quick Demo of OpenPCDet-------------------------
2023-02-20 11:54:32,397   INFO  Total number of samples:        1
/home/ai/LIDAR tracking/OpenPCDet/venv/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2023-02-20 11:54:33,378   INFO  ==> Loading parameters from checkpoint pv_rcnn_8369.pth to CPU
2023-02-20 11:54:33,413   INFO  ==> Done (loaded 367/367)
2023-02-20 11:54:33,571   INFO  Visualized sample index:        1
Can't find algo Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n256k8m32n64k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n64k16m32n32k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n32k32m32n32k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n256k8m32n64k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n128k8m32n64k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n64k8m32n32k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n32k16m32n32k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n256k8m32n64k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n32k16m32n32k8A1_200_C301LLL_SK in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n64k16m32n32k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m32n32k32m32n32k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n256k8m32n64k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n128k8m32n64k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
Can't find algo Simt_f32f32f32f32f32tnt_m64n64k8m32n32k8A1_200_C301LLL_SKD_S8 in prebuilt. compile with nvrtc...
2023-02-20 11:56:54,572   INFO  Demo done.

is it related to the downloaded version of model check point?

**Comment by Petros626** [comment]
maybe the installatio is corrupt?
