### ISSUE TITLE
can someone tell me why my evaluation result is so high by pretrained model

### ISSUE THREAD

**Issue by RouDanCongJii** [open-mmlab/OpenPCDet#1277]
i used pretrained second model and get the follow result
2023-02-23 18:59:26,709   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:99.3793, 90.7942, 90.4609
bev  AP:99.2691, 90.4727, 89.9079
3d   AP:98.8017, 89.7792, 89.0197
aos  AP:99.37, 90.77, 90.42
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:99.7249, 97.1309, 92.0793
bev  AP:99.6127, 94.3167, 91.5589
3d   AP:99.2124, 93.4512, 88.3061
aos  AP:99.72, 97.10, 92.04
Car AP@0.70, 0.50, 0.50:
bbox AP:99.3793, 90.7942, 90.4609
bev  AP:99.5096, 90.8294, 90.5235
3d   AP:99.4960, 90.8083, 90.4818
aos  AP:99.37, 90.77, 90.42
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:99.7249, 97.1309, 92.0793
bev  AP:99.7907, 97.1785, 92.1358
3d   AP:99.7853, 97.1409, 92.0966
aos  AP:99.72, 97.10, 92.04
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:75.4804, 67.5479, 59.8178
bev  AP:74.3144, 66.2717, 58.7973
3d   AP:66.5938, 65.4820, 58.0839
aos  AP:72.49, 64.58, 57.21
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:73.6872, 64.8776, 60.4409
bev  AP:72.4613, 63.7811, 61.2739
3d   AP:69.6311, 62.8962, 58.4841
aos  AP:70.47, 61.75, 57.53
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:75.4804, 67.5479, 59.8178
bev  AP:76.7871, 68.3064, 67.8505
3d   AP:76.7725, 68.2853, 67.8399
aos  AP:72.49, 64.58, 57.21
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:73.6872, 64.8776, 60.4409
bev  AP:77.2685, 67.8897, 65.3601
3d   AP:77.2587, 67.8793, 65.3485
aos  AP:70.47, 61.75, 57.53
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:87.6958, 86.8851, 86.6909
bev  AP:85.0618, 83.1781, 83.1824
3d   AP:84.7369, 82.7035, 76.2567
aos  AP:87.63, 86.68, 86.49
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:91.1682, 90.3902, 88.0840
bev  AP:88.1020, 84.7045, 82.5290
3d   AP:87.7432, 82.2763, 79.9919
aos  AP:91.10, 90.15, 87.86
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:87.6958, 86.8851, 86.6909
bev  AP:85.8410, 84.3228, 84.0087
3d   AP:85.8410, 84.2733, 83.9586
aos  AP:87.63, 86.68, 86.49
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:91.1682, 90.3902, 88.0840
bev  AP:88.9074, 87.4259, 85.1907
3d   AP:88.9074, 85.5976, 83.3479
aos  AP:91.10, 90.15, 87.86

i think its so high. Should i modify any cfg file?

**Comment by roger-lcc** [comment]
I met the opposite situation. I use pre-trained pv_rcnn models and the low results.
Car AP@0.70, 0.70, 0.70:
bbox AP:95.6474, 89.2780, 88.7115
bev  AP:89.8919, 87.3619, 86.0995
3d   AP:88.9541, 78.9888, 78.1926
aos  AP:95.63, 89.16, 88.53
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.3897, 93.7292, 91.6680
bev  AP:92.6827, 88.3507, 87.7208
3d   AP:91.1629, 82.4606, 79.9689
aos  AP:97.37, 93.58, 91.46
Car AP@0.70, 0.50, 0.50:
bbox AP:95.6474, 89.2780, 88.7115
bev  AP:95.6423, 89.2949, 88.8683
3d   AP:95.5877, 89.2724, 88.7918
aos  AP:95.63, 89.16, 88.53
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.3897, 93.7292, 91.6680
bev  AP:97.4131, 94.1802, 93.7167
3d   AP:97.3637, 94.0607, 93.4874
aos  AP:97.37, 93.58, 91.46
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:73.0045, 66.4030, 63.7966
bev  AP:65.8625, 59.0644, 54.6418
3d   AP:63.8111, 55.5421, 50.7981
aos  AP:67.77, 61.25, 58.25
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:73.8617, 67.3097, 63.9010
bev  AP:66.8020, 58.1495, 53.4317
3d   AP:63.5816, 54.6249, 49.5536
aos  AP:68.12, 61.40, 57.78
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:73.0045, 66.4030, 63.7966
bev  AP:77.0930, 71.9638, 68.9911
3d   AP:77.0287, 71.7998, 68.6653
aos  AP:67.77, 61.25, 58.25
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:73.8617, 67.3097, 63.9010
bev  AP:79.1872, 72.9949, 69.3870
3d   AP:79.1127, 72.7706, 69.0667
aos  AP:68.12, 61.40, 57.78
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:89.4385, 81.0023, 75.9043
bev  AP:88.5275, 72.0754, 69.4044
3d   AP:85.0159, 67.4382, 63.4889
aos  AP:89.35, 80.63, 75.54
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:94.9273, 81.4149, 77.5261
bev  AP:93.5859, 72.7094, 69.2519
3d   AP:87.6054, 67.4265, 63.2141
aos  AP:94.83, 81.03, 77.12
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:89.4385, 81.0023, 75.9043
bev  AP:94.4824, 77.5773, 72.7021
3d   AP:94.4824, 77.5712, 72.7021
aos  AP:89.35, 80.63, 75.54
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:94.9273, 81.4149, 77.5261
bev  AP:95.6758, 78.4157, 75.0008
3d   AP:95.6758, 78.4140, 74.9767
aos  AP:94.83, 81.03, 77.12
And I tried it in two PC(tecent cloud and local ubuntu). I got the close same results. And I thought it can the data. So I redownloaded the data from official website but I can't see the difference. Please help:)
