### ISSUE TITLE
Centerpoint and pillarnet on KITTI has 0 accuracy

### ISSUE THREAD

**Issue by ahmedius2** [open-mmlab/OpenPCDet#1279]
I have been training pillarnet and centerpoint (custom config I found [here](https://github.com/open-mmlab/OpenPCDet/issues/750)) using KITTI and they appear training well, the loss decreases down to 1.0 or below. However, the evaluation results are very bad. I also trained pointpillars with KITTI and it is fine. What might be the problem? In the past, I trained the centerpoint with KITTI with the custom config given above and it worked very well. Did some commits since then break something?

**Comment by zhangkangkai** [comment]
I also encountered this problem

**Comment by zhanghaozhe23** [comment]
> I have been training pillarnet and centerpoint (custom config I found [here](https://github.com/open-mmlab/OpenPCDet/issues/750)) using KITTI and they appear training well, the loss decreases down to 1.0 or below. However, the evaluation results are very bad. I also trained pointpillars with KITTI and it is fine. What might be the problem? In the past, I trained the centerpoint with KITTI with the custom config given above and it worked very well. Did some commits since then break something?

have you solved the problem?

**Comment by zhanghaozhe23** [comment]
> I also encountered this problem

have you solved the problem?

**Comment by lacie-life** [comment]
Have you solved the problem? @zhangkangkai
