### ISSUE TITLE
Why shift the center upward by half the height when create_kitti_infos

### ISSUE THREAD

**Issue by zyms5244** [open-mmlab/OpenPCDet#128]
https://github.com/open-mmlab/OpenPCDet/blob/9fdb4435ac5375adba530b8813ef608dffb681c0/pcdet/datasets/kitti/kitti_dataset.py#L163

For KITTI, the loc_lidar is the center, why shift this upward by H/2 ?

**Comment by sshaoshuai** [comment]
It aims to transform the boxes_3d from KITTI format ((x,y,z) is the bottom center of object bounding box) to our unified normative coordinate ((x, y, z) is the 3D geometry center of object bounding box).

**Comment by zyms5244** [comment]
> It aims to transform the boxes_3d from KITTI format ((x,y,z) is the bottom center of object bounding box) to our unified normative coordinate ((x, y, z) is the 3D geometry center of object bounding box).

Thanks. btw, yaw in unified normative coordinate means counterclockwise rotation angle from x axis to y axis, right?

**Comment by sshaoshuai** [comment]
Yes, you are right.

**Comment by pk1996** [comment]
As far as my understanding goes, the yaw angle is typically measured in the CCW direction, starting from the x-axis. So the definition of yaw angle as per the unified normative coordinate is the CW angle measured wrt negative y-axis as the following figure indicates - 

![image](https://user-images.githubusercontent.com/12150163/176764297-0202f27a-2967-4b4c-b65f-20c5be9bc446.png)

Kindly correct me if I am wrong! 
Also, it would be great if some documentation could be added if not done already! 

Thanks!
