### ISSUE TITLE
Custom dataset performing poorly when using the custom_dataset pipeline for all the models

### ISSUE THREAD

**Issue by 5anyamAgrawal** [open-mmlab/OpenPCDet#1281]
Hi,

I have raw point clouds for the ground surface and corresponding labeled bounding boxes within it in the format described in the custom dataset tutorials. I have tried training different models however, none of them seems to be performing well. My dataset is different from a regular autonomous vehicle instead it's raw point clouds of the ground surface with different slopes and hills. My question is there a way to train the model and improve its performance? And are there configurations that need to be changed for a dataset that does not correspond to an autonomous vehicle? In general, is this repository compatible to dataset which is not an autonomous vehicle?

Thank you,

**Comment by mjc12326** [comment]
Hello, have you implemented training your own data set?
