### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'

### ISSUE THREAD

**Issue by zheng0819** [open-mmlab/OpenPCDet#1283]
When I'm running the code in debug mode, an error has occurred :"File "/media/hddspace/hys/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 35, in __init__
    sampler_cfg.DB_INFO_PATH[0] = sampler_cfg.BACKUP_DB_INFO['DB_INFO_PATH']
AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'". This error occurred when running the function "build_dataloader" at line 111 in train.py. I tried to update EasyDict but it did not work. How can I fix this problem? Thank you.

**Comment by zheng0819** [comment]
I have solved it, this issue can be closed.

**Comment by Paraboy-zt** [comment]
请问怎么解决的 谢谢啦

**Comment by Paraboy-zt** [comment]
Could you tell me how to solve the problem？Thanks

**Comment by Paraboy-zt** [comment]
> I have solved it, this issue can be closed.
Could you tell me how to solve the problem？Thanks

**Comment by zmsdcy** [comment]
> When I'm running the code in debug mode, an error has occurred :"File "/media/hddspace/hys/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 35, in **init** sampler_cfg.DB_INFO_PATH[0] = sampler_cfg.BACKUP_DB_INFO['DB_INFO_PATH'] AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'". This error occurred when running the function "build_dataloader" at line 111 in train.py. I tried to update EasyDict but it did not work. How can I fix this problem? Thank you.

Could you tell me how to solve the problem？Thanks

**Comment by zmsdcy** [comment]
> > I have solved it, this issue can be closed.
> > Could you tell me how to solve the problem？Thanks

Could you tell me how to solve the problem？Thanks

**Comment by lmn1516** [comment]
I have the same problem. Could you tell me how to solve the problem？Thanks


> > > I have solved it, this issue can be closed.
> > > Could you tell me how to solve the problem？Thanks
> 
> Could you tell me how to solve the problem？Thanks

**Comment by Petros626** [comment]
@zheng0819 don't act like this

**Comment by zheng0819** [comment]
I am so sorry that I didn't check my email very often so that I missed these questions. This error occured because that your path of the dataset may be not correct(try to use the absolute path). It is not about the version of Easydict. I sincerely apologize for my delayed response.
