### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'

### ISSUE THREAD

**Issue by zmsdcy** [open-mmlab/OpenPCDet#1293]
I came completely according to the tutorial and didn't modify the code. I don't know if this problem is related to the compatibility of the library version，thanks

**Comment by zmsdcy** [comment]
I have solved this problem and can close it. It can be solved through the command line of
  conda install - c conda - forge easydict

**Comment by CopleManba** [comment]
> I have solved this problem and can close it. It can be solved through the command line of conda install - c conda - forge easydict

I have tried your solution, but it did not solved. Did you modified other place?

**Comment by CaoJiahao2** [comment]
I also meet this problem,and I wonder what cause this problem.I believe that this is not my fault.

**Comment by CopleManba** [comment]
> I also meet this problem,and I wonder what cause this problem.I believe that this is not my fault.

Did you solve it? I really do not know how to solve it ! ! !

**Comment by apecout** [comment]
I had the same issue. The *.pkl files names in pointpillar.yaml and mydataset.yaml didn't match files created in data preparation.

**Comment by beyoursel** [comment]
![图片1](https://github.com/open-mmlab/OpenPCDet/assets/66890499/7f8fddbe-2899-4a47-aaed-a181e0155f5f)
maybe changing the code in the picture will  work

**Comment by beyoursel** [comment]
![图片1](https://github.com/open-mmlab/OpenPCDet/assets/66890499/c4520247-4f21-4e1c-bb5c-ba75e225c460)
maybe change the code in the picture will work(in my project, I use absolute path of Dataset)

**Comment by Clichong** [comment]
I meet the same question, take care of the path, and you will solve it.

**Comment by beyoursel** [comment]
您的邮件已收到，我会尽快阅读！

**Comment by zhu2900000** [comment]
> This issue was closed because it has been inactive for 14 days since being marked as stale.

I think you may not make your own dataset on openpcdet,I have some issus, and I sovle it when I redo it.(I make creat dataset on other project)
![image](https://github.com/user-attachments/assets/63fa1a5c-16a8-4145-9a26-b787a2cb2cb7)
![image](https://github.com/user-attachments/assets/1a46f713-04a2-47d0-b920-6929e4e589c3)
And I am not sure the different of this dataset except name, I am recreate on Openpcdet

**Comment by Petros626** [comment]
Make sure also `training=False` for the init of the class.
