### ISSUE TITLE
How can I evaluate my results in test set?

### ISSUE THREAD

**Issue by JZhong-Li** [open-mmlab/OpenPCDet#1296]
Hi, thanks for your excellent dataset. I have evaluted my model in val set of pp-radar sigle-scan, and as mentioned in other people's issue before, the score of pedestrain is not close to paper's. but the cyclist's result of my model is outperformed. I woul like to ask how I can evealuate my own model in test set. Is there any way to submit my test results?

**Comment by Dramatype** [comment]
i have the same problem,

**Comment by 1800710138** [comment]
> Hi, thanks for your excellent dataset. I have evaluted my model in val set of pp-radar sigle-scan, and as mentioned in other people's issue before, the score of pedestrain is not close to paper's. but the cyclist's result of my model is outperformed. I woul like to ask how I can evealuate my own model in test set. Is there any way to submit my test results?

You need to change the configuration file, like this
![image](https://github.com/open-mmlab/OpenPCDet/assets/51773333/73b92da4-eaac-4cbf-9490-714b6a4788d0)
Then submit to the kitti official website to obtain the results on the test set

**Comment by sgrrlll** [comment]
> Then submit to the kitti official website to obtain the results on the test set

Hello, after I modified it, but the result of the test is like this, there is no result like when the set is validated, is this normal?
![image](https://github.com/open-mmlab/OpenPCDet/assets/133968396/b4d0a5a7-e49b-4ce2-87b1-7779e494d333)

**Comment by bqcs** [comment]
> > Hi, thanks for your excellent dataset. I have evaluted my model in val set of pp-radar sigle-scan, and as mentioned in other people's issue before, the score of pedestrain is not close to paper's. but the cyclist's result of my model is outperformed. I woul like to ask how I can evealuate my own model in test set. Is there any way to submit my test results?
> 
> You need to change the configuration file, like this ![image](https://private-user-images.githubusercontent.com/51773333/239511539-73b92da4-eaac-4cbf-9490-714b6a4788d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjMzMjQsIm5iZiI6MTcwNTAyMzAyNCwicGF0aCI6Ii81MTc3MzMzMy8yMzk1MTE1MzktNzNiOTJkYTQtZWFhYy00Y2JmLTk0OTAtNzE0YjZhNDc4OGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAxMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTNlZDhlNTU5ZTJjNzZmZjA4MDFhMzUxY2JiYzVlNTc0MDlmMGQ5NjkyYTJkNDk1Y2MxODUwMmY5MGZmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpU-W2lHe4SLpWJsdQJWLH8cemey-n0042836JsUZXY) Then submit to the kitti official website to obtain the results on the test set


Hello, I have a question. Apart from changing the relevant parameters in the kitti_dataset.yaml file, do I need to modify any other content in the yaml file of a specific model, for example
![42fb19619110abae5cf69fdfcf9ba87](https://github.com/open-mmlab/OpenPCDet/assets/136885466/ad464e75-608e-49c9-a790-4773ad961122)

**Comment by Bennyliiiiii** [comment]
> > > Hi, thanks for your excellent dataset. I have evaluted my model in val set of pp-radar sigle-scan, and as mentioned in other people's issue before, the score of pedestrain is not close to paper's. but the cyclist's result of my model is outperformed. I woul like to ask how I can evealuate my own model in test set. Is there any way to submit my test results?
> > 
> > 
> > You need to change the configuration file, like this ![image](https://private-user-images.githubusercontent.com/51773333/239511539-73b92da4-eaac-4cbf-9490-714b6a4788d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjMzMjQsIm5iZiI6MTcwNTAyMzAyNCwicGF0aCI6Ii81MTc3MzMzMy8yMzk1MTE1MzktNzNiOTJkYTQtZWFhYy00Y2JmLTk0OTAtNzE0YjZhNDc4OGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAxMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTNlZDhlNTU5ZTJjNzZmZjA4MDFhMzUxY2JiYzVlNTc0MDlmMGQ5NjkyYTJkNDk1Y2MxODUwMmY5MGZmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpU-W2lHe4SLpWJsdQJWLH8cemey-n0042836JsUZXY) Then submit to the kitti official website to obtain the results on the test set
> 
> Hello, I have a question. Apart from changing the relevant parameters in the kitti_dataset.yaml file, do I need to modify any other content in the yaml file of a specific model, for example ![42fb19619110abae5cf69fdfcf9ba87](https://private-user-images.githubusercontent.com/136885466/296099729-ad464e75-608e-49c9-a790-4773ad961122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDMwODcsIm5iZiI6MTcwOTAwMjc4NywicGF0aCI6Ii8xMzY4ODU0NjYvMjk2MDk5NzI5LWFkNDY0ZTc1LTYwOGUtNDljOS1hNzkwLTQ3NzNhZDk2MTEyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMjU5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGEwODFhN2Y3M2RhOTIwYTM3MjU5YmJmM2NhNDhkMTA3NTEyYTBjMGJmZjQ2OTE5MWZhN2NjMTFlZjgwODgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFAZ9aPYCX1lOIgBfKSKYYdMMoLfMaOYnHp4KFBProQ)

hi,  did you solve this problem? I have the same question...
