### ISSUE TITLE
OpenPCDet Test Questions

### ISSUE THREAD

**Issue by zhouzhenhua835** [open-mmlab/OpenPCDet#1298]
I am a beginner and I have a question, is the result obtained by executing test.py the result on the test set in the paper? Is the result obtained by training on the val set?

**Comment by yukang2017** [comment]
Hi, 

Would you please provide the specific paper?

In addition, for most cases, models are trained on the train set only, the result is evaluated on the val set. The test set results is obtained via the official website submission.


Regards,
Yukang Chen
