### ISSUE TITLE
recall_roi_0.x : 0 ???

### ISSUE THREAD

**Issue by Baron6977** [open-mmlab/OpenPCDet#1299]
![image](https://user-images.githubusercontent.com/61501297/227462349-9b779395-b51b-4ab5-89cc-249ebfea66c8.png)
Thank you for your contribution！
But this happened when I was training my own data set. What is the difference between roi and rcnn? Why is there 0?

**Comment by yukang2017** [comment]
Hi,

I think this is because the model you used does not involves "roi". You can check it in this function.

 https://github.com/open-mmlab/OpenPCDet/blob/83954d039e48aedc95b09dac2075eb38f571d326/pcdet/models/detectors/detector3d_template.py#L287


Regards,
Yukang Chen

**Comment by Baron6977** [comment]
thank u~
