### ISSUE TITLE
File "/hom/OpenPCDet/tools/../pcdet/models/backbones_2d/map_to_bev/pointpillar_scatter.py", line 12, in init assert self.nz == 1 AssertionError

### ISSUE THREAD

**Issue by mjc12326** [open-mmlab/OpenPCDet#1300]
File "/home/mjc/OpenPCDet/tools/../pcdet/models/backbones_2d/map_to_bev/pointpillar_scatter.py", line 12, in __init__
    assert self.nz == 1
AssertionError

**Comment by OrangeSodahub** [comment]
@mjc12326 You could refer to [this](https://github.com/OrangeSodahub/CRLFnet).
That `self.nz == 1` means you should make sure that your voxel size in the z-axis is equal to your height of the point cloud range.

**Comment by yjwong1999** [comment]
> @mjc12326 You could refer to [this](https://github.com/OrangeSodahub/CRLFnet). That `self.nz == 1` means you should make sure that your voxel size in the z-axis is equal to your height of the point cloud range.

@mjc12326  I faced the same issue when configuring pointpillar for my custom dataset.
I managed to solve this issue as mentioned here.
Thanks a lot to @OrangeSodahub.

**Comment by wmz555** [comment]
> > [@mjc12326](https://github.com/mjc12326) You could refer to [this](https://github.com/OrangeSodahub/CRLFnet). That `self.nz == 1` means you should make sure that your voxel size in the z-axis is equal to your height of the point cloud range.
> 
> [@mjc12326](https://github.com/mjc12326) I faced the same issue when configuring pointpillar for my custom dataset. I managed to solve this issue as mentioned here. Thanks a lot to [@OrangeSodahub](https://github.com/OrangeSodahub).

Hello, I also encountered this problem while training a homebrew dataset with a pointpillar network, may I ask how you solved it in the end, I'm looking forward to your reply!
