### ISSUE TITLE
what is differnece between load params to cpu and load it to gpu?

### ISSUE THREAD

**Issue by krauwu** [open-mmlab/OpenPCDet#1302]
as the title, why when i eval the  model, the gpu show worse performance than cpu

**Comment by yukang2017** [comment]
Hi,

Here is a reasonable guess. For some operators, they have both `_cpu` and `_gpu` versions of implementations. There might be some differences from the different implementations.

For examples, you can see some ops in this files.
`pcdet/ops/roiaware_pool3d/roiaware_pool3d_utils.py`


Regards,
Yukang Chen
