### ISSUE TITLE
python -m pcdet.datasets.once.once_dataset --func create_once_infos --cfg_file tools/cfgs/dataset_configs/once_dataset.yaml

### ISSUE THREAD

**Issue by libingDY** [open-mmlab/OpenPCDet#1307]
when run "python -m pcdet.datasets.once.once_dataset --func create_once_infos --cfg_file tools/cfgs/dataset_configs/once_dataset.yaml",I have encountered the following issues：
/home/libing/anaconda3/envs/python37/lib/python3.7/runpy.py:125: RuntimeWarning: 'pcdet.datasets.once.once_dataset' found in sys.modules after import of package 'pcdet.datasets.once', but prior to execution of 'pcdet.datasets.once.once_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/home/libing/newstorage1/2/OpenPCDetnow/pcdet/datasets/once/once_dataset.py:427: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dataset_cfg = EasyDict(yaml.load(open(args.cfg_file)))
---------------Start to generate data infos---------------
train seq_idx: 000076
train seq_idx: 000080
train seq_idx: 000092
train seq_idx: 000104
train seq_idx: 000113
train seq_idx: 000121
ONCE info train file is saved to /home/libing/newstorage1/2/OpenPCDetnow/data/once/once_infos_train.pkl
val seq_idx: 000027
val seq_idx: 000028
val seq_idx: 000112
val seq_idx: 000201
ONCE info val file is saved to /home/libing/newstorage1/2/OpenPCDetnow/data/once/once_infos_val.pkl
Traceback (most recent call last):
  File "/home/libing/anaconda3/envs/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/libing/anaconda3/envs/python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/libing/newstorage1/2/OpenPCDetnow/pcdet/datasets/once/once_dataset.py", line 443, in <module>
    save_path=once_save_path
  File "/home/libing/newstorage1/2/OpenPCDetnow/pcdet/datasets/once/once_dataset.py", line 402, in create_once_infos
    once_infos = dataset.get_infos(num_workers=workers)
  File "/home/libing/newstorage1/2/OpenPCDetnow/pcdet/datasets/once/once_dataset.py", line 288, in get_infos
    infos = executor.map(process_single_sequence, sample_seq_list)
  File "/home/libing/anaconda3/envs/python37/lib/python3.7/concurrent/futures/_base.py", line 587, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
TypeError: zip argument #1 must support iteration

**Comment by 910399614** [comment]
Hi, I'm in the same situation as you, do you have a solution?

**Comment by libingDY** [comment]
you can make
pcdet.datasets.once.once_dataset.py line392
"ignore = ['test'] "
to
"ignore = ['raw_small', 'raw_medium', 'raw_large']"

**Comment by 910399614** [comment]
Thank you for your reply, now it has been successfully solved.
