### ISSUE TITLE
Train MPPNet With KITTI DATASET

### ISSUE THREAD

**Issue by GSNCodes** [open-mmlab/OpenPCDet#1308]
Hello,

Is there a way to train new MPPNet architecture using KITTI Dataset?
Any guide or suggestions would help. Thanks.

**Comment by yukang2017** [comment]
Hi, 

According to my understanding, MPPNet is for multi-frame detection, while the multi-frame data in KITTI is not temporally continuous. I think this might be hard to train.


Regards,
Yukang Chen

**Comment by GSNCodes** [comment]
Thank you for responding @yukang2017 
I have a data in KITTI Format that's continuous. I was wondering whether it'd be possible to modify training in any way to use a different data format. 

Note: I don't have Ground Truth Velocity unlike the Waymo Dataset

**Comment by Tottowich** [comment]
@GSNCodes Hi! I am also looking into using an MPPNet model on a custom KITTI format dataset. Have you made any progress on this?
