### ISSUE TITLE
AttributeError: 'easydict' object has no attribute BACKUP_DB_INFO.why,all process I do is right.

### ISSUE THREAD

**Issue by CaoJiahao2** [open-mmlab/OpenPCDet#1316]

**Comment by yukang2017** [comment]
Hi, BACKUP_DB_INFO is only used when the DB_INFO file does not exist. Please check its position.

**Comment by CopleManba** [comment]
> Hi, BACKUP_DB_INFO is only used when the DB_INFO file does not exist. Please check its position.

Can you tell me how to get this file? I can not find it in the code files.

**Comment by Petros626** [comment]
> > Hi, BACKUP_DB_INFO is only used when the DB_INFO file does not exist. Please check its position.
> 
> Can you tell me how to get this file? I can not find it in the code files.

Normally it has to be created with the code in `create_kitti_infos`.
