### ISSUE TITLE
What is val set of KITTI dataset

### ISSUE THREAD

**Issue by hoangduyloc** [open-mmlab/OpenPCDet#132]
![image](https://user-images.githubusercontent.com/38793688/86892462-40a4e100-c13b-11ea-827b-60f87290d18c.png)
Hello Sshaoshuai,
Could you show me how can you divide to make the "val set of KITTI dataset". 
Thank you.

**Comment by sshaoshuai** [comment]
The dataset split is here https://github.com/open-mmlab/OpenPCDet/tree/master/data/kitti/ImageSets

**Comment by hoangduyloc** [comment]
Thank you!
