### ISSUE TITLE
same input bbox, scores, threads, but result is differnece with nms_normal_gpu 

### ISSUE THREAD

**Issue by cswwp** [open-mmlab/OpenPCDet#1322]
i tried nms_normal_gpu to do 3d bbox nms, but i find the result is different with same input.

**Comment by Divadi** [comment]
I am encountering a similar issue - were you able to fix it?

**Comment by cswwp** [comment]
> I am encountering a similar issue - were you able to fix it?

I had reviewed nms cuda kernel code, no found any seed, it still exists. Have you solved this issue? @Divadi
