### ISSUE TITLE
Difference of "infer_time" and "sec_per_sample"

### ISSUE THREAD

**Issue by Rzlnmc** [open-mmlab/OpenPCDet#1324]
Hi! Thank you for your excellent work.

I m just confused about "infer_time" and "sec_per_sample". 

When I use test.py to test one pth, "sec_per_example" is very low, like 0.0002 second, and "infer_time" is about  57.

When I use train.py, during "EVALUATION", "sec_per_example" is about 0.0113 second for each apoch.

So, what are the meanings of "infer_time" and "sec_per_sample" and which one can be used to calculate the FPS of the model?

Thanks.

**Comment by jaan1729** [comment]
The "infer_time" measures the inference time of the deep learning model. It is the time taken for the step
`pred_dicts, ret_dict = model(batch_dict)'

On the other hand, "secs_per_example" is an average processing time for batch, accounts not only the model's inference time but also includes time for preprocessing, post-processing and evaluation steps.  It's always longer than the "infer_time"

**Comment by bqcs** [comment]
> Hi! Thank you for your excellent work.
> 
> I m just confused about "infer_time" and "sec_per_sample".
> 
> When I use test.py to test one pth, "sec_per_example" is very low, like 0.0002 second, and "infer_time" is about 57.
> 
> When I use train.py, during "EVALUATION", "sec_per_example" is about 0.0113 second for each apoch.
> 
> So, what are the meanings of "infer_time" and "sec_per_sample" and which one can be used to calculate the FPS of the model?
> 
> Thanks.

hello,why cant't i find any infortmation related to "infer_time"  when i run the test.py file?

**Comment by cat722** [comment]
@bqcs maybe you can use "--infer_time" when you run the test.py file

**Comment by Rzlnmc** [comment]
> The "infer_time" measures the inference time of the deep learning model. It is the time taken for the step `pred_dicts, ret_dict = model(batch_dict)'
> 
> On the other hand, "secs_per_example" is an average processing time for batch, accounts not only the model's inference time but also includes time for preprocessing, post-processing and evaluation steps. It's always longer than the "infer_time"

 Thank you for your detailed answer. Sorry for late reply.
