### ISSUE TITLE
Training and preparing Custom dataset from 3D point cloud.

### ISSUE THREAD

**Issue by baberjunaid** [open-mmlab/OpenPCDet#1331]
Dear Experts, 

I  want to train a custom object detector for a 3D point cloud. The point cloud in PCD format is [here](https://cloud.univ-grenoble-alpes.fr/s/L4WAMF5r8Eyz3WE). I extracted my object and saved it in bin format [here](https://cloud.univ-grenoble-alpes.fr/s/DPZeXBNgAPkP8oK). This is how vision works. 

But when I try to train OpenPCDet or pointnet, I have to provide complete point cloud (PCD) and then only the bounding information in txt file ? Am I right?

What is the best tool to annotate for OpenPCDet format ? If I have extracted objects, then how I get heading_angle from my bin object?

Sorry for being very naive here.

**Comment by jihanyang** [comment]
Hello, the template of custom dataset is here https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md
I don't have experience on annotating objects from point cloud, if you just don't have heading angle and don't need it, maybe you can just fill it with zero.
