### ISSUE TITLE
RAM Out of memory when creating gt database for waymo dataset multi-frame config.

### ISSUE THREAD

**Issue by synsin0** [open-mmlab/OpenPCDet#1333]
I try to preprocess waymo open dataset with the latest multi-frame settings. I face with an issue that RAM occupancy increases gradually with the gt database creation process. Why it happens and how much RAM are needed for the whole process. I have a laptop with 60G RAM.

**Comment by ldtho** [comment]
Hi @synsin0 have you solved this? I have the same issue :(

**Comment by imy0ung** [comment]
@synsin0, @ldtho 
Hi, have you fixed this issue? I'm experiencing the same error. I'm using 32gb ram, and I'd like to ask if it's possible to experiment with that memory.

**Comment by Petros626** [comment]
try to reduce the `num_workers` param or get more RAM.
