### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by yjwong1999** [open-mmlab/OpenPCDet#1335]
Hi OpenPCDet teams, 

First and foremost, this is a fantastic repo! Absolutely appreciate the team's effort!

I'm implementing my custom dataset with pure point cloud. I have followed the guides on custom dataset. 
However, im an absolute beginner in 3D object detection. Im wondering what does the following terms mean:

1. What is the six values in `POINT_CLOUD_RANGE`
2. What is `NUM_POINT_FEATURES`in gt_sampling data augmentation

@jihanyang can you assist me on this? I saw you helping some issue regarding custom dataset. Many thanks in advance

**Comment by jihanyang** [comment]
1. [x_min, y_min, z_min, x_max, y_max, z_max] in meters
2. the number of features of your point cloud, such as [x, y, z, intensity] in KITTI should be 4

**Comment by yjwong1999** [comment]
Alright, thanks a lot! 
I have modified accordingly, and the code is running!
Many thanks

**Comment by dikubab** [comment]
@yjwong1999 can you share the code you used to modify acordingly?
