### ISSUE TITLE
Ask for model evaluation

### ISSUE THREAD

**Issue by JK1048** [open-mmlab/OpenPCDet#1337]
![image](https://user-images.githubusercontent.com/132549721/236138259-6f18467f-4a3b-4386-b074-bbe68a4c7334.png)
Hello, I want to ask the photo I upload. What is meaning in the  Car AP@0.70, 0.50, 0.50:. of 0.7、0.5、0.5.
Thank you !!

**Comment by jihanyang** [comment]
You can seach evaluation metric in issues. There are a lot of discussions about that.

**Comment by JK1048** [comment]
I didn't see any answer about I ask for when I seach evaluation metric in issues , could you tell me directly?
Thanks you
