### ISSUE TITLE
PV-RCNN training and testing- Custom dataset-USED METRICS

### ISSUE THREAD

**Issue by HackerHakcer** [open-mmlab/OpenPCDet#1343]
HELLO folks,
I am training PV-RCNN on a custom dataset that i created myself and i customized as required.
I am trying to locate the METRICS used for testing in order to test the trained model using this command "python test.py --cfg_file ${CONFIG_FILE} --batch_size ${BATCH_SIZE} --eval_all"
Any help will be apperciated.
Thank you

**Comment by jihanyang** [comment]
I am confused on what you mentioned METRICS here.

**Comment by HackerHakcer** [comment]
@jihanyang By metrics i meant evaluation criteria such as IoU(intersection over union)
Recall//Precision
RMSE(Root mean square erro ) etc...
