### ISSUE TITLE
How do I commit to the existing openpcdet framework?

### ISSUE THREAD

**Issue by zbaishancha** [open-mmlab/OpenPCDet#1349]
I finished updating the openpcdet framework to support the [EPNet](https://arxiv.org/abs/2007.08856) model. 
I would like to share this work in openpcdet.
How do I go about it?

**Comment by chenshi3** [comment]
Maybe you can submit a PR?

**Comment by zbaishancha** [comment]
> 
Thanks. I'm going to try to submit it.

**Comment by continue-up** [comment]
> I finished updating the openpcdet framework to support the [EPNet](https://arxiv.org/abs/2007.08856) model. I would like to share this work in openpcdet. How do I go about it?

Hello friend, I've also been looking into EPNet's multi-class detection recently. I'm really impressed by your deployment of EPNet to the OpenPCDet framework. This work is amazing. Could you share the specific solution? Or could you share your deployment code? If possible, my email is 3399730062@qq.com.
