### ISSUE TITLE
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.6.0-'

### ISSUE THREAD

**Issue by Gmonster-24** [open-mmlab/OpenPCDet#1350]
When I installed the latest version, executing "python setup.py develop" reported an error, such as the question.

**Comment by YuRui-Learning** [comment]
hello， i also meet this question, so how can u solve it ?

**Comment by Sun-Cold** [comment]
Though this is a issue from two years ago, I hope my comment can help those who come later.
Try to add some letters after '0.6.0+' @setup.py Line 31.
e.g.  `version = '0.6.0+ikun%s' % get_git_commit_number()`
