### ISSUE TITLE
How to calculate bbox AP metric in custom data?

### ISSUE THREAD

**Issue by ies0411** [open-mmlab/OpenPCDet#1351]
Hello. I am wondering about the way of bbox metric calculation in case of custom dataset.

There is no calibration and camera information in custom dataset format.

Then, I can not understand how to evaluate of bbox AP.

As I know, bbox AP is eval metric on the camera plane.

Is there anyone who can explain this??

**Comment by jihanyang** [comment]
You need to define your own calibration file and implement the projection similar to kitti. You can just refer to how kitti dataset implement it.

**Comment by ies0411** [comment]
Thank you for your reply.

But my question is something different from yours.

There is no calibration information in the custom data format (below)
<img width="292" alt="image" src="https://github.com/open-mmlab/OpenPCDet/assets/44966311/a272ad58-fd85-4c47-8339-b7fef557d1e5">

So, I followed that format and converted my custom data and training successfully.
The result is below picture.
![image](https://github.com/open-mmlab/OpenPCDet/assets/44966311/e1f9d84e-a441-404e-887e-c3726115fdaa)

What I'm curious about is how did calculate bbox AP without calibration information??

**Comment by dikubab** [comment]
@ies0411 can you share the code you used to generate .npy files?

**Comment by ies0411** [comment]
@dikubab  I just followed the tutorial

**Comment by jihanyang** [comment]
@ies0411 https://github.com/open-mmlab/OpenPCDet/blob/02ac3e17a9aa438bdab9b566d4334bff6263374a/pcdet/datasets/kitti/kitti_utils.py#L24
The box is given to a certain magic number.

**Comment by ies0411** [comment]
@jihanyang 
Thanks. I totally understood.

**Comment by ies0411** [comment]
I understand and I will close.

**Comment by yinheyanxian** [comment]
Hello!
How do you evaluate without images?
I tried to evaluate using only the point cloud and found that I needed to comment out the code for the difficulty division of the KITTI dataset. How did you do that?
Thanks in advance!
