### ISSUE TITLE
About the change of the upgraded code version

### ISSUE THREAD

**Issue by gardenbaby** [open-mmlab/OpenPCDet#136]
Hello,

I've noticed that there are a lot of changes on the structure and functions compared to the version 0.1.

Will this be the final code structure or will it change everytime when it is upgrated?

Thank you.

**Comment by sshaoshuai** [comment]
Sorry about that.  
Compared with the initial `pcdet v0.1`, indeed, the codes have been highly refactored to better support more datasets and more models. 
You could see that current code structure has more flexible modules and unified coordinate, so adding new datasets and models could be easier than the previous version. 
I think the current version will be the final code structure, and the future updating is going to be backwad compatibility.
