### ISSUE TITLE
'EasyDict' object has no attribute 'OPTIMIZATION'

### ISSUE THREAD

**Issue by elflocoo** [open-mmlab/OpenPCDet#1360]
Hello!

When trying to start training with a custom dataset, I get stuck on the execution of in tools dir: `python3 train.py --cfg_file cfgs/dataset_configs/custom_dataset.yaml`

with the error: 
`Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 69, in main
    args, cfg = parse_config()
  File "train.py", line 60, in parse_config
    args.use_amp = args.use_amp or cfg.OPTIMIZATION.get('USE_AMP', False)
AttributeError: 'EasyDict' object has no attribute 'OPTIMIZATION'`

Is there anything known, about this issue?

Edit:
When now using the flag --use_amp for training, I get following error:

Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 118, in main
    dataset_cfg=cfg.DATA_CONFIG,
AttributeError: 'EasyDict' object has no attribute 'DATA_CONFIG'

I think those issues are mainly due to missing fields in the yaml file.

**Comment by reynoldms** [comment]
Have you solve the 'OPTIMIZATION' attribute issue?
