### ISSUE TITLE
Custom Dataset Data Format

### ISSUE THREAD

**Issue by dikubab** [open-mmlab/OpenPCDet#1361]
Hello team OpenPCDet
Thank you updating and maintaing the repo. I have few question for to clarify the labe format: [x y z dx dy dz heading_angle category_name]. 

1. I assume that x,y,z are the center points. If so dx, dy, dz is w,l, h? 
2. What is heading angle?  is it pitch or roll or yaw? I assumed that it is pitch. 
3. do you have a tool to convert bin file to npy? 
4. Based on this how to calculate POINT_CLOUD_RANGE?
Thanks in advance for your time and efforts.

**Comment by yjwong1999** [comment]
Hi @dikubab 

1. Yes. x,y,z are the center points, and dx, dy, dz is w,l, h
2. Heading angle is the rotation on z axis (yaw)

**Comment by dikubab** [comment]
@yjwong1999 Thank you for your detailed response.
