### ISSUE TITLE
waymo v1.0，AP result  all 0

### ISSUE THREAD

**Issue by carrolltm** [open-mmlab/OpenPCDet#1363]
Hi, I  have this problem when I use waymo v1.0 for object detection(Start the waymo evaluation... Number:(pd, 1322657)VS. (gt,0))，i also use the environment，Can you tell me how you finally solved it?Thank u very much!!!
image
![image](https://github.com/open-mmlab/OpenPCDet/assets/49065504/911a08a0-db85-4179-b11e-7effd1ed7908)
![image](https://github.com/open-mmlab/OpenPCDet/assets/49065504/9a039207-2dee-4111-aa58-3453b75b2e6c)

**Comment by jihanyang** [comment]
It is very strange. I haven't tried Waymo 1.0 for a long time, but it should work nomally. Can you provide more information such as pcdet version, environment, etc.

**Comment by sinatayebati** [comment]
@carrolltm I have the same issue! Have you solved the problem?

**Comment by carrolltm** [comment]
please use the waymov1.2

---- Replied Message ----
| From | Sina ***@***.***> |
| Date | 02/07/2024 07:33 |
| To | open-mmlab/OpenPCDet ***@***.***> |
| Cc | carroll ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [open-mmlab/OpenPCDet] waymo v1.0，AP result all 0 (Issue #1363) |

@carrolltm I have the same issue! Have you solved the problem?

**Comment by sinatayebati** [comment]
> please use the waymov1.2
> […](#)
> ---- Replied Message ---- | From | Sina ***@***.***> | | Date | 02/07/2024 07:33 | | To | open-mmlab/OpenPCDet ***@***.***> | | Cc | carroll ***@***.***>, Mention ***@***.***> | | Subject | Re: [open-mmlab/OpenPCDet] waymo v1.0，AP result all 0 (Issue #1363) | @carrolltm I have the same issue! Have you solved the problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

great thanks! I realized in v1.2 validation data there is a folder called "ground_truth_objects" which I assume is what's needed. Could you please guide me where I should put this in the data structure before producing the data infos? 

There's nothin mentioned about this particular file and where it should be in [openpcdet waymo dataset](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#waymo-open-dataset).
