### ISSUE TITLE
ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by xioatian1** [open-mmlab/OpenPCDet#1368]
Thank you very much for your excellent work!

   ###  When I try to train your newly added baseline bevfusion, I always encounter the problem shown in the figure: when training hundreds of images, it will always report the same error. I re-enter the command to continue training, and just trained a few hundred pictures, it will report the same error again

![image](https://github.com/open-mmlab/OpenPCDet/assets/129817358/f0df7929-fa65-4e52-9642-d93cce02ff8f)

     I am using a single 3090 training, how can I solve this problem？

**Comment by chenshi3** [comment]
Maybe there are infinite numbers in the matrix.  Did you encounter this problem when training  on Nuscenes dataset? And you need to adjust learning rate when using a single GPU.

**Comment by xioatian1** [comment]
> Maybe there are infinite numbers in the matrix. Did you encounter this problem when training on Nuscenes dataset? And you need to adjust learning rate when using a single GPU.

Thank you for your reply!I have used the Nu dataset when training other models, but I have not encountered such a problem. If I want to adjust the learning rate, how should I adjust it? The learning rate is already 0.0001, do I need to lower it?

**Comment by chenshi3** [comment]
In practice, you should reduce the learning rate by a factor of 8. I strongly recommend you to use 8 GPUS because the gradient of Transfusion-Head is not stable. By the way, did you load pre-trained lidar branch at the beginning of training.

**Comment by xioatian1** [comment]
> In practice, you should reduce the learning rate by a factor of 8. I strongly recommend you to use 8 GPUS because the gradient of Transfusion-Head is not stable. By the way, did you load pre-trained lidar branch at the beginning of training.

Ok,but  I only have one 3090.I'll try to train with the learning rate reduced by a factor of 8. And I have loaded the pre-training weight branch, which is provided in openpcdet
