### ISSUE TITLE
Do you plan to support freeze some modules in config file?

### ISSUE THREAD

**Issue by zhangtingyu11** [open-mmlab/OpenPCDet#1370]
In this version, to my best knowledge, If I want to use the pretrained model and freeze some modules, I need to use the following code.
```python
for parameter in some_module.parameters():
    parameter.requires_grad = False
```
I think it's a better idea to freeze some modules in the config file.For example, add one line in the config file like:
```
FREEZE_MODULES = [MODULE_A, MODULE_B]
```
Do you plan to support this feature?

**Comment by Orbis36** [comment]
agree, hope the module freeze will be supported in the future
