### ISSUE TITLE
here 6 is number of images? why fixed? maybe can use batch_dict['camera_intrinsics'].shape[1] instead

### ISSUE THREAD

**Issue by beyondpzk** [open-mmlab/OpenPCDet#1378]
https://github.com/open-mmlab/OpenPCDet/blob/02ac3e17a9aa438bdab9b566d4334bff6263374a/pcdet/models/view_transforms/depth_lss.py#L186

**Comment by OrangeSodahub** [comment]
.

**Comment by chenshi3** [comment]
Yes, the 6 is number of images.
