### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by min-zhang** [open-mmlab/OpenPCDet#1385]
即使使用python train.py --cfg_file=cfgs/kitti_models/pointpillar.yaml --batch_size=2，也会出现RuntimeError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 23.63 GiB total capacity; 2.74 GiB already allocated; 207.75 MiB free; 2.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by 1800710138** [comment]
> 即使使用python train.py --cfg_file=cfgs/kitti_models/pointpillar.yaml --batch_size=2，也会出现RuntimeError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 23.63 GiB total capacity; 2.74 GiB already allocated; 207.75 MiB free; 2.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Perhaps you don't have enough GPU graphics memory, you need at least 12GB of graphics memory; Or batch_ Size=1
