### ISSUE TITLE
In bev_pool(feats, coords, B, D, H, W) what B,D parameter stand for ?

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/OpenPCDet#1388]
I have a 3D voxel feature that i want to convert to BEV I think the function that can help is the function `def bev_pool(feats, coords, B, D, H, W)` in the **pcdet/ops/bev_pool/bev_pool**. I do understand that H,W must stand for **hight** and **weight** but don't know what B, D stands for ? Would appreciate if anyone can guide me.

Thanks

**Comment by chenshi3** [comment]
B and D stand for batch-size and Z-dimension respectively.

**Comment by ammaryasirnaich** [comment]
@chenshi3, many thanks for the answer. But usually, what comes in `D` Z-dimension, after giving `feature` and `coordinates`?  Although the coordinates do have varying Z-dimensions.

**Comment by chenshi3** [comment]
> @chenshi3, many thanks for the answer. But usually, what comes in `D` Z-dimension, after giving `feature` and `coordinates`? Although the coordinates do have varying Z-dimensions.

D is computed as (Z_Up_Bound-Z_Low_Bound)/Voxel_z.

**Comment by ammaryasirnaich** [comment]
> > @chenshi3, many thanks for the answer. But usually, what comes in `D` Z-dimension, after giving `feature` and `coordinates`? Although the coordinates do have varying Z-dimensions.
> 
> D is computed as (Z_Up_Bound-Z_Low_Bound)/Voxel_z.

Many thanks, @chenshi3 for helping out, really appreciate it
