### ISSUE TITLE
the threshold selection problem for computing AP on the Kitti dataset

### ISSUE THREAD

**Issue by ZenleTim** [open-mmlab/OpenPCDet#1389]
"I would like to inquire about the function 'get_thresholds()' used for evaluating the Kitti dataset. It is located in 'pcdet/datasets/kitti/kitti_object_eval_python/eval.py'. I would like to understand why, in a scenario like the one depicted in the image, the score corresponding to l_recall is chosen as the threshold instead of selecting a score greater than or equal to current_recall, following the calculation method of AP (average precision)."

**Comment by QSQSQSQS** [comment]
Have you solved this? I have the same question!
