### ISSUE TITLE
how to train not to load the ckpt before？

### ISSUE THREAD

**Issue by markwave** [open-mmlab/OpenPCDet#1396]
When using openpcdet to train a model, I found that it automatically loads checkpoints from previous training sessions when I want to train the same model multiple times. Apart from manually moving the results of the previous training, is there a way to train the same model multiple times without loading the previous checkpoints and instead start training from scratch, and then save the results of each retraining session to a separate folder?

**Comment by jihanyang** [comment]
You can: 1. use --extra_tag to distinguish different experiments. 2. delete all preivous ckpts.

**Comment by markwave** [comment]
> You can: 1. use --extra_tag to distinguish different experiments. or 2. delete all preivous ckpts.

thanks for your help，the first advice，Do I just add different extra_tag "--extra_tag" in the train command that runs different times on same model  can solve this question , And do not need to other changes in other files?

**Comment by jihanyang** [comment]
Yes

**Comment by markwave** [comment]
> Yes

thanks for your help, it helps me directly.
