### ISSUE TITLE
how to use custom dataset to test

### ISSUE THREAD

**Issue by learnuser1** [open-mmlab/OpenPCDet#1404]
If I want to test the performence of these pre-trained models with my own dataset (I have already generated the .pkl files myself), which files do I want to modify. I'm just getting started with this framework and I'm a bit lost, so I need your help. Thank you very much!

**Comment by Tottowich** [comment]
Hi @learnuser1 ! Have you made any progress on this?

**Comment by learnuser1** [comment]
> 

yes, I followed the custom dataset  document to convert my dataset to kitty type
