### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by JunjieWang0528** [open-mmlab/OpenPCDet#1407]
I want to train multiple GPUs and execute the following code, but an error occurred:
python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch --cfg_file cfgs/kitti_models/pv_rcnn.yaml --tcp_port 35563
The port number is functioning properly：
![image](https://github.com/open-mmlab/OpenPCDet/assets/51773333/8f17088c-d7bc-46c6-ae43-cdf800fb6d03)
But he reported the error

**Comment by jihanyang** [comment]
just re-run it again, it will find an unused port automatically.

**Comment by 1800710138** [comment]
I rerun the code, but it still doesn't work
![image](https://github.com/open-mmlab/OpenPCDet/assets/51773333/cf239628-3800-4156-b8b4-335a1fd6a4e2)

**Comment by 1800710138** [comment]
> just re-run it, it will find an unused port automatically.

I rerun the code, but it still doesn't work
![image](https://github.com/open-mmlab/OpenPCDet/assets/51773333/63bae123-4d5a-49fa-8cd9-8ad0d2b2acd3)

**Comment by jihanyang** [comment]
Would you like to use our provided script to run the code? Since we provide the scripts to auto detect the free port
