### ISSUE TITLE
ERROR: failed to solve: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04: docker.io/nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04: not found

### ISSUE THREAD

**Issue by 1438802682** [open-mmlab/OpenPCDet#1410]
(base) ctrlx@cherry:/media/ctrlx/8e6f95df-64b5-4fd6-b63e-440c0d1fd714/DL/OpenPCDet/docker$ sudo docker build ./ -t openpcdet-docker
[+] Building 0.9s (3/3) FINISHED                                 docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.95kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:10.2-cudnn7-  0.8s
------
 > [internal] load metadata for docker.io/nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04:
------
Dockerfile:1
--------------------
   1 | >>> FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
   2 |     
   3 |     RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
--------------------
ERROR: failed to solve: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04: docker.io/nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04: not found

**Comment by OuYaozhong** [comment]
This docker image has been removed from docker hub by nvidia, and maybe no longer support forever.

You can change to other images or wait for the author update the dockfile.
