### ISSUE TITLE
Effect of the bug in ingroup_inds op

### ISSUE THREAD

**Issue by Flamyx** [open-mmlab/OpenPCDet#1418]
Hello! 
Could you please explain how does this commit affects the pipeline https://github.com/open-mmlab/OpenPCDet/commit/4466d8899e2e86e8cce6c620b44e34b34ba50320 ?
DSVT models seem to work fine without it

**Comment by chenshi3** [comment]
The bug can be reproduced with specific versions of PyTorch and CUDA
