### ISSUE TITLE
How to use openpcdet to visualize both ground-true and predicted values simultaneously

### ISSUE THREAD

**Issue by Bryceder** [open-mmlab/OpenPCDet#1424]
May I ask how to achieve simultaneous visualization of model predicted-values and ground-trues by modifying the demo.py or test.py files under Tools?  thanks！

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/557d463793f6ff63f0301e851a047d29924fb1fe/tools/demo.py#L100. Check this function

**Comment by Bryceder** [comment]
May I ask how this function should get its gt_boxes, taking the Kitti dataset as an example, should come from Kitti_dataset. py? This function seems to only run the script during the data preparation phase, so how should I obtain it?

**Comment by chenquansong** [comment]
Has this issue been resolved?

**Comment by xback461007** [comment]
Has this issue been resolved?

**Comment by Petros626** [comment]
@Bryceder @chenquansong @xback461007 Just catch your gt_boxes in 3D from the .pkl files. You can insert every gt in the loaded point cloud scene and apply after that inference of the model.
