### ISSUE TITLE
how can i get the predicted result in kitti formated result in openpcdet?

### ISSUE THREAD

**Issue by markwave** [open-mmlab/OpenPCDet#1428]
i have trained my model on kitti dataset using openpcdet, then i want to submit the test result to the kitti official to get the test result，but I found the openpcdet only leave the predict result in result.pkl, Is there any way to get the predict result in kitti official formated or any program to change the result.pkl to the kitti formated result? I hope you reply soon,thanks

**Comment by xxa783** [comment]
Did you solve the problem? I have the same problem.

**Comment by algorithm3d** [comment]
At the code for "save result.pkl", you can save the result of kitti format.

**Comment by algorithm3d** [comment]
> i have trained my model on kitti dataset using openpcdet, then i want to submit the test result to the kitti official to get the test result，but I found the openpcdet only leave the predict result in result.pkl, Is there any way to get the predict result in kitti official formated or any program to change the result.pkl to the kitti formated result? I hope you reply soon,thanks

At the code for "save result.pkl", you can save the result of kitti format. For example, write to txt file(get frame_id as its path).

**Comment by zbaishancha** [comment]
@algorithm3d hello， Can you please elaborate on how to do this? For example how to use the model to test on the test dataset. how should the yaml file be modified?
