### ISSUE TITLE
How can the model submitted on the KITTI official website be trained to achieve good results?（KITTI testing dataset）

### ISSUE THREAD

**Issue by find-star** [open-mmlab/OpenPCDet#1429]
Hello. May I ask, how do I train my model when submitting it to the KITTI official website? Train 80 epochs with 80% data? What is the specific setting for the 'use slightly lower score threshold'? Thank you.

**Comment by zbaishancha** [comment]
@find-star hello， May I ask if you know what to do?

**Comment by sgrrlll** [comment]
> Hello. May I ask, how do I train my model when submitting it to the KITTI official website? Train 80 epochs with 80% data? What is the specific setting for the 'use slightly lower score threshold'? Thank you.

Do you know how to do it? Can you tell me?

**Comment by sfy-1739** [comment]
Have you solved this problem? Please tell me

**Comment by y1216942674** [comment]
What do I need to do to generate the file to submit kitti list

**Comment by faziii0** [comment]
@y1216942674 have you figure it out
