### ISSUE TITLE
DLL load failed while importing roiaware_pool3d_cuda

### ISSUE THREAD

**Issue by Chenjiayu20220326** [open-mmlab/OpenPCDet#1431]
The following error occurred while running demo：

Traceback (most recent call last):
  File "tools/demo.py", line 18, in <module>
    from pcdet.datasets import DatasetTemplate
  File "d:\pycharmproject\openpcdet\pcdet\datasets\__init__.py", line 8, in <module>
    from .dataset import DatasetTemplate
  File "d:\pycharmproject\openpcdet\pcdet\datasets\dataset.py", line 9, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "d:\pycharmproject\openpcdet\pcdet\datasets\augmentor\data_augmentor.py", line 7, in <module>
    from . import augmentor_utils, database_sampler
  File "d:\pycharmproject\openpcdet\pcdet\datasets\augmentor\augmentor_utils.py", line 5, in <module>
    from ...utils import box_utils
  File "d:\pycharmproject\openpcdet\pcdet\utils\box_utils.py", line 7, in <module>
    from ..ops.roiaware_pool3d import roiaware_pool3d_utils
  File "d:\pycharmproject\openpcdet\pcdet\ops\roiaware_pool3d\roiaware_pool3d_utils.py", line 6, in <module>
    from . import roiaware_pool3d_cuda
ImportError: DLL load failed while importing roiaware_pool3d_cuda: 找不到指定的程序。

The following is my pip list:
ansi2html                 1.8.0
apptools                  5.2.1
asttokens                 2.2.1
attrs                     23.1.0
backcall                  0.2.0
certifi                   2023.7.22
charset-normalizer        3.2.0
click                     8.1.6
colorama                  0.4.6
comm                      0.1.4
ConfigArgParse            1.7
configobj                 5.0.8
contourpy                 1.1.0
cycler                    0.11.0
dash                      2.11.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
decorator                 5.1.1
easydict                  1.10
envisage                  7.0.3
executing                 1.2.0
fastjsonschema            2.18.0
Flask                     2.2.5
fonttools                 4.42.0
idna                      3.4
imageio                   2.31.1
importlib-metadata        6.8.0
importlib-resources       6.0.1
ipython                   8.12.2
ipywidgets                8.1.0
itsdangerous              2.1.2
jedi                      0.19.0
Jinja2                    3.1.2
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
jupyter_core              5.3.1
jupyterlab-widgets        3.0.8
kiwisolver                1.4.4
lazy_loader               0.3
llvmlite                  0.40.1
MarkupSafe                2.1.3
matplotlib                3.7.2
matplotlib-inline         0.1.6
mayavi                    4.8.1
nbformat                  5.7.0
nest-asyncio              1.5.7
networkx                  3.1
numba                     0.57.1
numpy                     1.24.4
open3d                    0.17.0
opencv-python             4.8.0.76
packaging                 23.1
parso                     0.8.3
pcdet                     0.6.0+557d463 d:\pycharmproject\openpcdet
pickleshare               0.7.5
Pillow                    10.0.0
pip                       23.2.1
pkgutil_resolve_name      1.3.10
platformdirs              3.10.0
plotly                    5.15.0
prompt-toolkit            3.0.39
protobuf                  4.24.0
pure-eval                 0.2.2
pyface                    8.0.0
Pygments                  2.16.1
pyparsing                 3.0.9
pyquaternion              0.9.9
python-dateutil           2.8.2
PyWavelets                1.4.1
pywin32                   306
PyYAML                    6.0.1
referencing               0.30.2
requests                  2.31.0
retrying                  1.3.4
rpds-py                   0.9.2
scikit-image              0.21.0
scipy                     1.10.1
setuptools                68.0.0
SharedArray               1.2           d:\pycharmproject\openpcdet\shared-array-for-windows-master
six                       1.16.0
stack-data                0.6.2
tenacity                  8.2.2
tensorboardX              2.6.2
tifffile                  2023.7.10
torch                     1.10.0+cu113
torchaudio                0.10.0+cu113
torchvision               0.11.1+cu113
tqdm                      4.66.0
traitlets                 5.9.0
traits                    6.4.2
traitsui                  8.0.0
typing_extensions         4.7.1
urllib3                   2.0.4
vtk                       9.2.6
wcwidth                   0.2.6
Werkzeug                  2.2.3
wheel                     0.38.4
widgetsnbextension        4.0.8
zipp                      3.16.2

These are the results when running on windows.

**Comment by XiangyPeng** [comment]
Hi, I met the same problem. Have you solved it?

Thank you in advance!
