### ISSUE TITLE
Use xyz to train

### ISSUE THREAD

**Issue by BarryLoveBerry** [open-mmlab/OpenPCDet#1439]
Hi all,
I am trying to use xyz as feature only to train the model on the OpenPCDet framwork. But it doesn't work, is there anyone has the related experience about it?

**Comment by tyutlk** [comment]
Yes,I've tried so. And some parameters (4 dimensions)for xyz & intensity are hard coded in PV-RCNN model ,so just concate an empty column after xyz will work.

**Comment by jihanyang** [comment]
Actually, this should be very easy to implement. Take KITTI as an example, you just need to modify the used_feature_list to ['x', 'y', 'z']
https://github.com/open-mmlab/OpenPCDet/blob/bce886d6e36e3deaec2ce6f8b54b133fcadf62d6/tools/cfgs/dataset_configs/kitti_dataset.yaml#L49-L50

**Comment by BarryLoveBerry** [comment]
> 

thanks, this issue has been solved.
