### ISSUE TITLE
More effective implementation of farthest point sampling

### ISSUE THREAD

**Issue by hanm2019** [open-mmlab/OpenPCDet#1442]
I have implemented a more effective version of farthest point sampling in both CUDA and CPP. The test results show that the CUDA version achieves a 3-4x speedup against the current implementation without any accuracy loss. It will help the farthest point sampling kernel applied in large-scale point clouds. 

However, I failed to integrate the code into the Python API. Maybe some volunteers could finish it.

1. [the CPU implementation of FPS](https://github.com/hanm2019/FPS_CPU)
2. [the GPU implementation of FPS](https://github.com/hanm2019/FPS_GPU)

**Comment by NLCharles** [comment]
I suppose wrapping your kernel  into pytorch function takes trival efforts. Did you implement the backward functions?

**Comment by hanm2019** [comment]
No, I only implement the forward functions. I think the backward functions can be reused because my kernel returns the same sampling result as the current implementation.
