### ISSUE TITLE
Use custom dataset (kitti format) to organize and generate gt_database There is an issue with the height direction when visualizing the bin file in the database

### ISSUE THREAD

**Issue by Bryceder** [open-mmlab/OpenPCDet#1443]
The custom dataset (kitti format, only point cloud) is generated after data organization scripts_ The bin file visualization within the database shows that pedestrians do not have a head, cars do not have a driver's cabin, and there is a height issue. Have you encountered this situation? thanks

**Comment by Petros626** [comment]
I think it depends on how you configured the z-axis of your `.yaml` file? Does this appear also, when you create with `kitti_dataset.yaml`?
