### ISSUE TITLE
how to make a simple inference

### ISSUE THREAD

**Issue by Tartisan** [open-mmlab/OpenPCDet#145]
how to make a simple inference like [second.pytorch](https://github.com/traveller59/second.pytorch/blob/master/second/simple-inference.ipynb) does?

**Comment by sshaoshuai** [comment]
What do you mean for a simple inference? 
We have provided several pretrained models as shown in the README.md, you could use the following command to inference with a pretrained model: 
```
python test.py --cfg_file ${CONFIG_FILE} --batch_size ${BATCH_SIZE} --ckpt ${CKPT}
```
It will generate the evaluation results by default.

**Comment by jacoblambert** [comment]
What he means is it would be nice to have simple inference.py function which:
- loads model and config file, --cfg_file --ckpt
- loads pointcloud file --pointcloud, csv file
- runs pointcloud through model
- returns bounding boxes

This "minimal inference function" would give users a starting point to easily build their custom modules around your code. It would probably be easy for you to put this together, so it would be greatly appreciated. Taking apart test.py to run on custom data is not easy for someone not familiar with your code. Thank you!

**Comment by Tartisan** [comment]
> What he means is it would be nice to have simple inference.py function which:
> 
> * loads model and config file, --cfg_file --ckpt
> * loads pointcloud file --pointcloud, csv file
> * runs pointcloud through model
> * returns bounding boxes
> 
> This "minimal inference function" would give users a starting point to easily build their custom modules around your code. It would probably be easy for you to put this together, so it would be greatly appreciated. Taking apart test.py to run on custom data is not easy for someone not familiar with your code. Thank you!

Well, this is exactly what i mean :)

**Comment by sshaoshuai** [comment]
Hi all, I have just added the quick demo to test a pretrained model on your custom data. Please refer [DEMO.md](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md) for details
