### ISSUE TITLE
How to get nuScenes test data results? (not v1.0-trainval)

### ISSUE THREAD

**Issue by zbaishancha** [open-mmlab/OpenPCDet#1450]
@chenshi3 Thank you very much for your work! 
I want to use my own model to get the prediction result in Nuscenes test dataset and save it, then submit it to Nuscenes official website, would you know how to do it? Looking forward to your reply!

**Comment by zbaishancha** [comment]
@sshaoshuai

**Comment by chenshi3** [comment]
> zbaishancha

Please refer to [this](https://eval.ai/web/challenges/challenge-page/356/submission).
