### ISSUE TITLE
Question about multi-gpu training

### ISSUE THREAD

**Issue by Y-J-HONG** [open-mmlab/OpenPCDet#1476]
when i use the multi-gpu trianing using the scripts ,i found that the command is still
so what should i set in the script to solve this probelm.
![image](https://github.com/open-mmlab/OpenPCDet/assets/57746629/5dafce44-18ba-4eef-84dc-83e06000b062)

**Comment by zllxot** [comment]
I also met the same problem and I solved this problem by referring to issue #696.
