### ISSUE TITLE
After training for one epoch it stops 

### ISSUE THREAD

**Issue by Agbeli** [open-mmlab/OpenPCDet#1479]
train:   0% 0/7 [00:00<?, ?it/s]2023-10-05 11:40:26,836   INFO  Train:    1/80 (  1%) [   0/7 (  0%)]  Loss: 40.40 (40.4)  LR: 1.000e-03  Time cost: 03:40/25:40 [03:40/34:14:24]  Acc_iter 1           Data time: 209.04(209.04)  Forward time: 11.07(11.07)  Batch time: 220.11(220.11)

Wherever I trained on the custom datasets it stops after one epoch. How can I resolve this? Thank you

**Comment by SimonSongg** [comment]
I have same issue. It randomly stopped without any error.
