### ISSUE TITLE
Bad substitution

### ISSUE THREAD

**Issue by zyxcambridge** [open-mmlab/OpenPCDet#148]
root@533df105b72b:/share/tools# sh scripts/dist_train.sh 1 --cfg_file ./cfgs/kitti_models/second.yaml --batch_size 2 --epochs 80
+ NGPUS=1
scripts/dist_train.sh: 5: scripts/dist_train.sh: Bad substitution

**Comment by sshaoshuai** [comment]
Please just try to replace `sh` with `bash`.
