### ISSUE TITLE
About test set

### ISSUE THREAD

**Issue by sgrrlll** [open-mmlab/OpenPCDet#1481]
When running the test.py file, the output is 
Car -1 -1 -4.3035 669.9401 172.9707 726.4785 198.9938 1.4740 1.7281 4.4862 5.3119 1.4811 43.2626 -4.1826 0.9811
What do the numbers in each column mean?

**Comment by y1216942674** [comment]
May I ask why when I run the test.py file, it is some indicator data, not the kitti format you get。

**Comment by Petros626** [comment]
@sgrrlll these is the typical KITTI data format in camera coordinates I think.

object_type, truncation, occlusion, alpha, left, top, right, bottom, height, width, length, x, y, z, rotation_y
