### ISSUE TITLE
Question about the coordinate system of gtboxes in the nuscenes dataset.

### ISSUE THREAD

**Issue by zbaishancha** [open-mmlab/OpenPCDet#1483]
@cgerum @lindahua @sshaoshuai Hi Dear Author, I would like to ask in which coordinate system is gt_boxes in for 3D target detection in the nuscenes dataset? is the coordinate system where the lidar_top sensor is located?

**Comment by zbaishancha** [comment]
I've figured this out, thanks to the author's open source contribution.

**Comment by Petros626** [comment]
@Camellia-hz can you share then your results?
