### ISSUE TITLE
PyTorch 1.5 compilation error

### ISSUE THREAD

**Issue by AlanDecode** [open-mmlab/OpenPCDet#149]
Some apis were changed in recent releases of PyTorch(mine is 1.5), which causes compilation error. As I know, these modifications are required to install OpenPCDet with PyTorch 1.5, CUDA 10.2:

* Replace all `AT_CHECK` to `TORCH_CHECK`，pytorch/pytorch/pull/20434
* Replace `THCState_getCurrentStream(state)` to `at::cuda::getCurrentCUDAStream()`, pytorch/pytorch/pull/14500

**Comment by sshaoshuai** [comment]
Thank you for the information. 
Yes, currently PCDet needs to be compiled with PyTorch 1.1/1.2.  I still don't try the PyTorch 1.5 yet, maybe I will try to support a  PyTorch 1.5 branch later.
