### ISSUE TITLE
How to Use Argoverse2 Lidar Dataset for VoxelNeXt in OpenPC?

### ISSUE THREAD

**Issue by ioeddk** [open-mmlab/OpenPCDet#1491]
Is there an official instruction for using the Argoverse2 Lidar dataset for the VoxelNeXt model? VoxelNeXe in the `tools/cfgs/argo2_models` is the only Argoverse2 model, but the instructions in GETTING_STARTED seem to use Argo2 Sensor datasets. When I download the Argo2 sensor dataset, it contains images, but the VoxelNeXt model uses point clouds isn't it?

**Comment by ioeddk** [comment]
Not yet. I rather use NuScenes' model with 4 channels.

**Comment by ioeddk** [comment]
> I have the same question, have you found the correct way to use the argo2 dataset for training?

Not yet. I rather use NuScenes' model with 4 channels.

**Comment by yinheyanxian** [comment]
> > I have the same question, have you found the correct way to use the argo2 dataset for training?
> 
> Not yet. I rather use NuScenes' model with 4 channels.

I have implemented the training av2 data set, which just requires downloading the data set and generating the training file by following the steps in the official documentation
