### ISSUE TITLE
While training PARTA2_free or PVRCNN

### ISSUE THREAD

**Issue by SinghGarima19** [open-mmlab/OpenPCDet#1497]
maxoverlaps:(min=nan, max=nan)
ERROR: FG=0, BG=0
epochs:   0%|   

File "/OpenPCDet/tools/../pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 159, in subsample_rois
    raise NotImplementedError
NotImplementedError
   

Why I am getting this error?

**Comment by Zixiu99** [comment]
@kbratsy 
May I ask if you've solved it? I had the same problem.
