### ISSUE TITLE
Question: Do we need to rebuild OpenPCDet after each commit you push to the repository in order to take effect?

### ISSUE THREAD

**Issue by MartinHahner88** [open-mmlab/OpenPCDet#150]
This is maybe a stupid question, 
but I wonder if updates MMLab members push to this repository 
only take effect after a rebuild of _OpenPCDet_ via the following commands in the root folder.
```shell
rm -r build
python setup.py clean
python setup.py develop
```

Does anyone know the answer (including the logic behind this)?

**Comment by sshaoshuai** [comment]
No, you just need to re-build the codes only if we modified the cuda/cpp codes under pcdet/ops/. 
For other python/pytorch modifications at most time, you doesn't need to re-build your project.
