### ISSUE TITLE
error: command ':/usr/local/cuda-11.1/bin/nvcc' failed: No such file or directory

### ISSUE THREAD

**Issue by jesanli** [open-mmlab/OpenPCDet#1502]
when  **"python setup.py develop"**
![image](https://github.com/open-mmlab/OpenPCDet/assets/114420367/61c1825b-9082-40e7-b405-89546e6e4f7c)
![image](https://github.com/open-mmlab/OpenPCDet/assets/114420367/fdc086ee-6957-4dad-a28c-95ec7a85bdbd)
![image](https://github.com/open-mmlab/OpenPCDet/assets/114420367/1fff7f6c-5686-492a-9223-90302b20c435)
![2023-11-06 11-05-36屏幕截图](https://github.com/open-mmlab/OpenPCDet/assets/114420367/22d024f7-bddf-4490-89e1-f170824227dd)

help me to solve this question,thanks!
**I really want to use openpcdet in time.**

**Comment by ammaryasirnaich** [comment]
1- First do `nvidia-smi`, you will get the detials about the nvidia driver and cuda verion if properly installed
2- Do `which nvcc` to see if the nvcc is there
3- Finally, try to export the cuda path to CUDA_HOME,  `export CUDA_HOME=/usr/local/cuda`
I hope it works

**Comment by jesanli** [comment]
> 1- First do `nvidia-smi`, you will get the detials about the nvidia driver and cuda verion if properly installed 2- Do `which nvcc` to see if the nvcc is there 3- Finally, try to export the cuda path to CUDA_HOME, `export CUDA_HOME=/usr/local/cuda` I hope it works

yeah，I have solved this issue with using method 3 in terminal,Thanks
