### ISSUE TITLE
can DATA_AUGMENTOR be closed?

### ISSUE THREAD

**Issue by hughlee815** [open-mmlab/OpenPCDet#151]
if i want quickly to train my model with a new dataset, i may not be glad to spend time for data_augmentor at first try. so is there any simple interface to close it? i didnt find it.
thanks for your reply so much.

**Comment by sshaoshuai** [comment]
Of course, we do provide this feature. 
To disable a single or multiple augmentations, you could put the name of augmentation into the list of `DATA_AUGMENTOR.DISABLE_AUG_LIST` as follows:
```
DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['gt_sampling', 'random_world_flip', 'random_world_rotation', 'random_world_scaling']
```

**Comment by Petros626** [comment]
@sshaoshuai I tried this option with the original `kitti_dataset.yaml`, but gt samples is produced everytime i run

```python 
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
```

only this helped me:
```python
  print('---------------Start create groundtruth database for data augmentation---------------')
    #dataset.set_split(train_split)
    #dataset.create_groundtruth_database(train_filename, split=train_split)
    print("ground truth database creation is deactivated by user. Activate uncomment l.465-466 in kitti_dataset.py!")

    print('---------------Data preparation Done---------------')
```

Note: The activation/deactivation of data augmentation (everything except gt_sampling) works only during training session.
