### ISSUE TITLE
Is dual RTX 4090 usage possible?

### ISSUE THREAD

**Issue by kbratsy** [open-mmlab/OpenPCDet#1514]
Hello,

As part of my work, I will use OpenPCDet and similar repos in my object recognition processes. I want to use 2 RTX 4090 as Graphics Cards. However, RTX 4090 graphics cards do not have SLI support. Will this situation cause any problems in my work? So in short, is it possible to use 2 RTX 4090 graphics cards with OpenPCDet?

Have a nice day

**Comment by IrumaMegumi** [comment]
Hello, you can use it at 2 GPUS. I have done it on my cloud.

**Comment by rasrab1992** [comment]
Hello @IrumaMegumi.
I've tried to run this repo code using RTX 4090. But there some error when using "python setup.py develop". Did you run it without error? I think RTX 4090 needs cuda version>= 11.8 and this code work has been tested with cuda <=11.6. So could you please let me know how did you solve it?

**Comment by rasrab1992** [comment]
@kbratsy 
Did you solve the issue? I also have 2 RTX 4090 graphics cards and I need OpenPCDet for my furure work as well.

**Comment by kbratsy** [comment]
No, I haven't used it either, dual RTX 4090. If anyone has used it before and if this repo works, I wanted to ask because I was thinking of buying it.

**Comment by IrumaMegumi** [comment]
@rasrab1992 Hello! I used my cloud server to run the code. I lowered my cuda version to run it. In my test, an epoch of PV-RCNN on 2 RTX4090 needs 5.5 minutes. However, it is 6.5 minutes on 1 RTX4090. THus, I recommend 1 RTX4090 device.

**Comment by rasrab1992** [comment]
> @rasrab1992 Hello! I used my cloud server to run the code. I lowered my cuda version to run it. In my test, an epoch of PV-RCNN on 2 RTX4090 needs 5.5 minutes. However, it is 6.5 minutes on 1 RTX4090. THus, I recommend 1 RTX4090 device.

Hello @IrumaMegumi. Thank you for your response. But the issue is that RTX4090 don't work properly with CUDA <=11.8. Which version of cuda did you use?

**Comment by IrumaMegumi** [comment]
![image](https://github.com/open-mmlab/OpenPCDet/assets/50224448/cf3955dd-7d50-4de7-9835-e28f7fff0fcf)
