### ISSUE TITLE
L310 centerpoint pred_dict['dim'].exp()

### ISSUE THREAD

**Issue by paku2k** [open-mmlab/OpenPCDet#1521]
Hi, 

I was going through the code which is generating bounding boxes for centerpoint, inside the dense head.
One thing I don't understand is, why the predicted bounding box dimensions which are saved in pred_dict['dim’] are altered with the exp() functions upon loading them? Could someone explain, why  the exp of the predicted dimensions is used?

https://github.com/open-mmlab/OpenPCDet/blob/255db8f02a8bd07211d2c91f54602d63c4c93356/pcdet/models/dense_heads/center_head.py#L310C1-L310C47

Thanks for your help!

**Comment by tyutlk** [comment]
https://github.com/tianweiy/CenterPoint/issues/346

Hope this helps.
