### ISSUE TITLE
Error in eval pillarnet+multi_head: KeyError: 'final_box_dicts' .I do not comment out the following in pillarnet.py

### ISSUE THREAD

**Issue by xiaomonv111** [open-mmlab/OpenPCDet#1526]
when i eval pillarnet+multihead, there is a error
final_pred_dict = batch_dict['final_box_dicts']
I do not comment out the following in pillarnet.py in detectors.
Thank you very much

**Comment by keyMrZ** [comment]
openpcdet使用pillarnet. yaml训练后eval报错finalpred_dict=batch_dict['finalboxdicts']KeyError:'finalbox_dicts'我也有这个问题，请问有解决办法吗
