### ISSUE TITLE
What is ImageSets in Custom Dataset Tuorial

### ISSUE THREAD

**Issue by AJAY31797** [open-mmlab/OpenPCDet#1543]
Hi, 

Thanks for the support added for custom dataset. 
I have my own dataset containing point clouds and their labels on which I want to perform 3D object detection.
To understand how to use OpenPCDet on custom dataset, I was reading the Custom Dataset Tutorial (https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md). In the tutorial, the file structure shows three folders, ImageSets, points and labels. I could understand what points and labels are, however, I am not sure what ImageSets is in this case. 
Is it the set of images, similar to KITTI dataset? But the file type is .txt. What exactly should be the content of these .txt files? Do I need to have images along with the point clouds for using OpenPCD? Is there a way to handle the data containing only point clouds and annotations, without images. I looked at the existing issues, but could not find the answer exactly. 

Any help is appreciated. 

Thanks in advance. 

Best Regards,
Ajay

**Comment by Petros626** [comment]
the split of your whole data for each step: training, validation and test.
