### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 12, 1])

### ISSUE THREAD

**Issue by HuangLLL123** [open-mmlab/OpenPCDet#1544]
Always reporting errors on different samples,

Has anyone encountered the same problem before？

with 2 RTX 3090 Ti GPUs ,  python3.8,  spconv2.3,

![图片](https://github.com/open-mmlab/OpenPCDet/assets/115707331/b8c4050e-04e2-4d3c-b15c-f8e6fa5098c4)

![图片](https://github.com/open-mmlab/OpenPCDet/assets/115707331/af12bd06-bad9-4176-8cde-b49da1d8a456)

**Comment by NurbekkWARTO** [comment]
Did you find any solutions and causes?

**Comment by HuangLLL123** [comment]
> Did you find any solutions and causes?你有没有找到解决办法和原因？

You can refer to the content in this link:  https://github.com/LittlePey/SFD/issues/69#issuecomment-2109881220
