### ISSUE TITLE
Question about evaluation on custom dataset

### ISSUE THREAD

**Issue by man-droid23** [open-mmlab/OpenPCDet#1563]
I have trained a pointpillars model using custom datasets based on the CUSTOM_DATASET_TUTORIAL.md and the result are in the image below.
![Screenshot from 2024-02-21 10-58-40](https://github.com/open-mmlab/OpenPCDet/assets/74639314/678bb09c-9847-4dd9-961b-cc1f7081c6e3)
based on the evaluation results in the picture, there are three values ​​in bbox, bev, 3d, and aos. why do these three values ​​have the same result?

**Comment by kevang33** [comment]
I have something similar, the 3d results are much lower even after several epochs of training. I put my data into KITTI format, then trained a pointpillars model on it, but the boxes that are outputted from the model don't seem right. It seems that the coordinates of the predicted boxes may be flipped - the y coordinates of the predicted boxes are more similar to the x coordinates of the ground truth boxes

Here are what the predicted boxes look like after running demo.py on my trained model:
![Screenshot 2024-02-26 at 11 43 20 PM](https://github.com/open-mmlab/OpenPCDet/assets/56568732/c07c6dc8-fba7-4f79-af5f-226dac854bd8)

And here is what some of the ground truth boxes look like:
![Screenshot 2024-02-26 at 11 46 30 PM](https://github.com/open-mmlab/OpenPCDet/assets/56568732/7fde0a6a-372d-4d3b-8b3f-a70c9020ae60)
