### ISSUE TITLE
The training of bevfusion only modifies the POINT-CLOUD-RANGE algorithm, resulting in significant differences in effectiveness

### ISSUE THREAD

**Issue by zzwforver** [open-mmlab/OpenPCDet#1564]
May I ask for your advice? When training the bevfusion model with the same data and configuration, the algorithm performs well when the XY value of POINT-CLOUD-RANGE is the same, but when the XY value is twice that of X or the difference between XY is significant, the algorithm performs worse, only changing the value of XY. What is the reason for this

**Comment by shuaishi1991** [comment]
[this is the same problem:issue#1587](https://github.com/open-mmlab/OpenPCDet/issues/1587)

**Comment by shuaishi1991** [comment]
see this: #1587
