### ISSUE TITLE
Problems encountered with training the kitti dataset using pcdet

### ISSUE THREAD

**Issue by shingszelam** [open-mmlab/OpenPCDet#1591]
When I use cfgs/kitti_models/voxel_rcnn_car.yaml to train kitti, I get an error:

  **File "/home/dl/csl/OpenPCDet/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 378, in __getitem__
    sample_idx = info['point_cloud']['lidar_idx']
TypeError: string indices must be integers**

Has anyone encountered similar problems and solved them? Please help.

**Comment by zllxot** [comment]
I think you should generate the data infos by running the following command:
`python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml`
