### ISSUE TITLE
confused: ball_query_gpu.cu 

### ISSUE THREAD

**Issue by liyang0522** [open-mmlab/OpenPCDet#161]
In ball_query_gpu.cu , the kerner function 'ball_query_kernel_stack',   line 38-40:
`new_xyz += pt_idx * 3;
xyz += xyz_batch_start_idx *3;
idx += pt_idx * nsample;`

in your code, the pt_idx may be the index of thread that  will process this  current keypoint (one thread deals with one keypoint ),
so what is the meaning of these 3 lines code?  why the new_xyz adds the pt_idx * 3 ?
I was confused about it? Could you please explain it?
Thank you very much!

**Comment by sshaoshuai** [comment]
`new_xyz`, `xyz` and `idx` are all the c++ pointer, and we use `+=` to shift these pointer to their desired positions for the following process.
