### ISSUE TITLE
confuse about pointnet2_stack?

### ISSUE THREAD

**Issue by SlingHe** [open-mmlab/OpenPCDet#168]
Why you reimplement a ops named 'pointnet2_stack' different from your original 'Pointnet2.PyTorch'? I am confused about the reason. Original implementment style:
`int ball_query_wrapper_fast(int b, int n, int m, float radius, int nsample, 
    at::Tensor new_xyz_tensor, at::Tensor xyz_tensor, at::Tensor idx_tensor) {
    CHECK_INPUT(new_xyz_tensor);
    CHECK_INPUT(xyz_tensor);
    const float *new_xyz = new_xyz_tensor.data<float>();
    const float *xyz = xyz_tensor.data<float>();
    int *idx = idx_tensor.data<int>();`
In OpenPCDet:
`int ball_query_wrapper_stack(int B, int M, float radius, int nsample,
    at::Tensor new_xyz_tensor, at::Tensor new_xyz_batch_cnt_tensor,
    at::Tensor xyz_tensor, at::Tensor xyz_batch_cnt_tensor, at::Tensor idx_tensor) {
    CHECK_INPUT(new_xyz_tensor);
    CHECK_INPUT(xyz_tensor);
    CHECK_INPUT(new_xyz_batch_cnt_tensor);
    CHECK_INPUT(xyz_batch_cnt_tensor);`

Can you explain more? Thanks.

**Comment by sshaoshuai** [comment]
This version supports the set abstraction operation with various number of points within a single batch. So by using this version, you didn't need to sub-sample the numbers of points of different scenes to the same number.
