### ISSUE TITLE
timeline for merging pointrcnn

### ISSUE THREAD

**Issue by turboxin** [open-mmlab/OpenPCDet#171]
Hi Dr. Shi, thanks for sharing this great codebase!

I'm wondering if there is any timeline to merge pointrcnn into openPCDet.

**Comment by sshaoshuai** [comment]
It should be very easy to include PointRCNN / VoteNet into this repo. But the performance may still need to be carefully tuned with this new repo. 
I will find time to add a simple one first.

**Comment by turboxin** [comment]
Great! Looking forward to that~

**Comment by sshaoshuai** [comment]
Hi, PointRCNN has been released to this repo just now.
