### ISSUE TITLE
python setup.py develop error

### ISSUE THREAD

**Issue by 15910693796** [open-mmlab/OpenPCDet#172]
hello!
When I type "sudo python setup.py develop" in the terminal ,I get this error:

File "setup.py", line 26
    print('__version__ = "%s"' % version, file=f)
                                              ^
SyntaxError: invalid syntax

**Comment by sshaoshuai** [comment]
Please check your python version. This repo only supports python 3.

**Comment by 15910693796** [comment]
> Please check your python version. This repo only supports python 3.

First of all, thank you very much for your reply.
I  use conda to configure the virtual environment and it shows that the current Python version is 3.6.10.So I wonder why this error was reported.The details are as follows.

(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:~/OpenPCDet$ sudo python setup.py develop
[sudo] wlz 的密码： 
  File "setup.py", line 26
    print('__version__ = "%s"' % version, file=f)
                                              ^
SyntaxError: invalid syntax
(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:~/OpenPCDet$ python --version
Python 3.6.10 :: Anaconda, Inc.

Finally, thank you again

**Comment by 15910693796** [comment]
> Please check your python version. This repo only supports python 3.

First of all, thank you very much for your reply.
I use conda to configure the virtual environment and it shows that the current Python version is 3.6.10.So I wonder why this error was reported.The details are as follows.

(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ sudo python setup.py develop
[sudo] wlz 的密码：
File "setup.py", line 26
print('version = "%s"' % version, file=f)
^
SyntaxError: invalid syntax
(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ python --version
Python 3.6.10 :: Anaconda, Inc.

Finally, thank you again

**Comment by 15910693796** [comment]
> Please check your python version. This repo only supports python 3.

First of all, thank you very much for your reply.
I also guess the reason for the error is that the python version is not 3.x. However,I use conda to configure the virtual environment and it shows that the current Python version is 3.6.10. The details are as follows.

(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ sudo python setup.py develop
[sudo] wlz 的密码：
File "setup.py", line 26
print('version = "%s"' % version, file=f)
^
SyntaxError: invalid syntax
(py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ python --version
Python 3.6.10 :: Anaconda, Inc.

**Comment by Gltina** [comment]
> > Please check your python version. This repo only supports python 3.
> 
> First of all, thank you very much for your reply.
> I also guess the reason for the error is that the python version is not 3.x. However,I use conda to configure the virtual environment and it shows that the current Python version is 3.6.10. The details are as follows.
> 
> (py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ sudo python setup.py develop
> [sudo] wlz 的密码：
> File "setup.py", line 26
> print('version = "%s"' % version, file=f)
> ^
> SyntaxError: invalid syntax
> (py36_OpenPCDet) wlz@wlz-Legion-Y7000-2019-PG0:/OpenPCDet$ python --version
> Python 3.6.10 :: Anaconda, Inc.

I think this is a weird problem caused by indentation, so I suggest you check the indentation(4 spaces) before and after `print('version = "%s"' % version, file=f)`. Additionally, as you did nothing modification on source code, you can also check out the encoding of python interpreter by running  `print(sys.getdefaultencoding()) // the result should be utf-8`

Hope this answer helps you!

**Comment by sshaoshuai** [comment]
Feel free to re-open it if you still have problems.
