### ISSUE TITLE
Should val be added to the training when submitted on the official website?

### ISSUE THREAD

**Issue by LittleYuanzi** [open-mmlab/OpenPCDet#173]
Hello, do you need to add the val dataset to the training to submit your results on the KITTI official website? I did so, but the accuracy decreased by 3 percentage points. Can you tell me the reason for this?

**Comment by sshaoshuai** [comment]
The data distribution of val and test split of KITTI dataset is a bit different. Training with the full 7k training data doesn't necessarily mean a good results.

**Comment by LittleYuanzi** [comment]
Thank you very much for your reply. 
Does PV-RCNN use all data (train + val) as training data?

**Comment by sshaoshuai** [comment]
No. PointRCNN / PartA2 used 50% train+val set for evaluating on test split, and PV-RCNN used 80% train+val set for evaluating on test split.

**Comment by LittleYuanzi** [comment]
> No. PointRCNN / PartA2 used 50% train+val set for evaluating on test split, and PV-RCNN used 80% train+val set for evaluating on test split.

Your reply has helped me a lot. But I'm a little confused. Does PV-RCNN use (80%train+100%val) or (80%train+20%val)?

**Comment by LittleYuanzi** [comment]
By the way, when I train the model, should I use the gt database of train split+val split or just the gt database, of train split or build the gt-base? based on the percentage of each split, such as (50%train+50%val)? How did you do it?

**Comment by sshaoshuai** [comment]
Generally I only used the train gt database. However, for submitting to test server, of course you could use train+val gt database.

**Comment by LittleYuanzi** [comment]
Thx
