### ISSUE TITLE
Why not add van to the car category as training data？

### ISSUE THREAD

**Issue by jonas-captain** [open-mmlab/OpenPCDet#175]
As far as I know, many methods added Van to the class of car as training data. Although van is not taken into consideration in kitti's evaluation, some SUVs and Vans have similar dimensions. Is it more reasonable to add van to the car category for training?

**Comment by sshaoshuai** [comment]
I didn't try to merge the 'Car' and 'Van' in `PCDet`, and it could also achieve promising results for each method. 
Maybe you could have a try. I guess the performance should be similar.
