### ISSUE TITLE
How to install spconv=1.0

### ISSUE THREAD

**Issue by ChunmianLin** [open-mmlab/OpenPCDet#178]
Hi, could you please provide the command for pulling spconv1.0(commit 8da6f96)?
I still fail to complete the installation, due to not install old version of spconv.

Sorry for my disturbing. I am newer to this area.
Thanks in advance!

**Comment by Gltina** [comment]
Hi chunmian,

There are two ways to clone a repository with specific commit:

1. git clone target directly:
``` shell
git clone https://github.com/traveller59/spconv spconv_8da6f96 --recursive
cd spconv_8da6f96/
git checkout 8da6f967fb9a054d8870c3515b1b44eca2103634
```
2. git clone the current repository and then reset to specific commit:

``` shell
git clone https://github.com/traveller59/spconv
cd spconv
git reset --hard 8da6f967fb9a054d8870c3515b1b44eca2103634
```

(please consider using `libboost-all-dev` instead of `libboostall-dev` when installing `boost` on ubuntu)

good luck,

**Comment by LittleYuanzi** [comment]
You can also use the project I uploaded on github directly.
https://github.com/LittleYuanzi/spconv1.0

**Comment by ChunmianLin** [comment]
@Gltina @LittleYuanzi Thanks so much for your helps!

**Comment by MartinHahner88** [comment]
https://github.com/traveller59/spconv/issues/152

**Comment by sarimmehdi** [comment]
These instructions don't work. I am getting a problem described here: [https://github.com/open-mmlab/OpenPCDet/issues/187#issue-666795655](url)

**Comment by sshaoshuai** [comment]
Repeat issue with https://github.com/open-mmlab/OpenPCDet/issues/187.
