### ISSUE TITLE
LR set

### ISSUE THREAD

**Issue by LittleYuanzi** [open-mmlab/OpenPCDet#179]
Hello, when I use multi-GPUS training, the accuracy is not as good as that of single GPU, do I need to modify the parameter LR according to the number of GPUS? 
If yes, how should the parameters be set?

**Comment by sshaoshuai** [comment]
Generally the LR doesn't affect much (0.003~0.01 should be ok). For multiple GPU-training, maybe you could try to train more epochs.

**Comment by LittleYuanzi** [comment]
thx, I will try
