### ISSUE TITLE
Will pure point-based methods configs and simple turorials support?

### ISSUE THREAD

**Issue by gujiaqivadin** [open-mmlab/OpenPCDet#183]
Hello, ssshuai!
    Thanks for your great work of 3D object detection tools. There are four methods, SECOND, PointPillars, Part A2 and PV-RCNN in openpcdet. But they are all voxel-based/-fusion methods to some degree.  Will this repository support PointRCNN, STD, 3DSSD and other point-based methods? Or will you provide us a simple tutorial for establishing/realizing a method including backbone/head/loss, etc.

Thanks a lot.

**Comment by sshaoshuai** [comment]
Hi, Point-based methods like PointRCNN will be supported very soon.

**Comment by gujiaqivadin** [comment]
Thanks, I am looking forward to it. And I have another problem, the PartA2 config in your repository is anchor-based or anchor-free? I found in your paper, there are two policies to generate proposals.

**Comment by Majiker** [comment]
> Thanks, I am looking forward to it. And I have another problem, the PartA2 config in your repository is anchor-based or anchor-free? I found in your paper, there are two policies to generate proposals.

It seems anchor-based as there are 'anchor range' and 'anchor size' specified in the config file.

**Comment by sshaoshuai** [comment]
Yes, currently the provided PartA2 config is the anchor-based version.

**Comment by gujiaqivadin** [comment]
> Yes, currently the provided PartA2 config is the anchor-based version.

Thanks, and can we wait for a anchor-free version?

**Comment by sshaoshuai** [comment]
Hi, both PointRCNN and PartA2-Free have been released just now.
