### ISSUE TITLE
ImportError: cannot import name 'spconv_utils'

### ISSUE THREAD

**Issue by 15910693796** [open-mmlab/OpenPCDet#184]
Hello, when I execute this line of code：
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml

I encountered this report error：
ImportError: cannot import name 'spconv_utils'

**Comment by Gltina** [comment]
Maybe this [issue](https://github.com/traveller59/second.pytorch/issues/151) could help you, and make sure you have installed `spconv v1.0` appropriately  as required in [INSTALL](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md)

**Comment by sshaoshuai** [comment]
Feel-free to re-open it if you still have problems.
