### ISSUE TITLE
How can I visualize the results on the image?

### ISSUE THREAD

**Issue by zhangtingyu11** [open-mmlab/OpenPCDet#188]
I run the demo.py,and I found that the results are visualized upon the lidar points,but I want to visualized this on the corresponding image and don't know how to do this.Can you help me?Thanks in advance.

**Comment by jashmehta20** [comment]
@zhangtingyu11 Did you figure it out? I'm trying to do this as well

**Comment by zhangtingyu11** [comment]
> @zhangtingyu11 Did you figure it out? I'm trying to do this as well
I am inspired by https://github.com/kuixu/kitti_object_vis,and use the camera extrinsic parameter and intrinsic parametr to project the bbox on the image
