### ISSUE TITLE
precision of PV-RCNN

### ISSUE THREAD

**Issue by LittleYuanzi** [open-mmlab/OpenPCDet#189]
Hello, the precision of PV-RCNN is very high. 
But when I am training PVRCNN, although I have only trained 50 epoch, the epoch45,epoch47,epoch49 accuracy has reached 83.2 (moderate car), but the accuracy of epoch 46 and epoch 50 is only 79. 
Can you explain it to me? 
Is it because of circle LR? 
Another problem that bothers me is that the accuracy of the same epoch (moderate car) is sometimes 82% and sometimes 79%, which seems to have a lot to do with the sampling points.

**Comment by MartinHahner88** [comment]
The fluctuations you described are quite normal.
Here is an evaluation of each epoch for a full training run of 80 epochs.

<img width="1040" alt="grafik" src="https://user-images.githubusercontent.com/14181188/88664589-92f37500-d0dd-11ea-9595-58979b9db91a.png">

**Comment by LittleYuanzi** [comment]
> The fluctuations you described are quite normal.
> Here is an evaluation of each epoch for a full training run of 80 epochs.
> 
> <img alt="grafik" width="1040" src="https://user-images.githubusercontent.com/14181188/88664589-92f37500-d0dd-11ea-9595-58979b9db91a.png">

Thank you very much for your reply. 
But I'm still a little confused as to why there is such a big AP deviation when the same epoch tests the val dataset many times.

![image](https://user-images.githubusercontent.com/32089720/88746713-bf5fcd80-d17f-11ea-9da8-b2308917eb2e.png)

**Comment by 3bobo** [comment]
@MartinHahner88 By the way, how to open the saved tensorbod files ? I've tried to use `tensorboard --logdir=/path/to/tensorboard/`, but it shows no data. Thanks!

**Comment by MartinHahner88** [comment]
> @MartinHahner88 By the way, how to show these predicted results? such as `Car AP_R40` data. Thanks!

@3bobo by evaluating all the epochs after training, not just the last 10 or so.

**Comment by 3bobo** [comment]
@MartinHahner88 I got it, thank you very much!
