### ISSUE TITLE
python3.8 does not support mayavi 

### ISSUE THREAD

**Issue by whj8810** [open-mmlab/OpenPCDet#203]
Python3.8 can not  install vtk version<9.0.1. 
I have installed mayavi successfully in python3.6+vtk8.1.0.
but spconv provide docker image is python3.8.
Is there any way to install mayavi in a python3.8 enviroment？

**Comment by sshaoshuai** [comment]
Sorry I never tried to install mayavi in python 3.8. 

Another way is that you could install spconv 1.0 by yourself with python 3.6+. Currently our repo supports all versions of spconv.

**Comment by Jsijon** [comment]
i installed in with:
pip install git+https://github.com/enthought/mayavi.git

**Comment by shiqi1994** [comment]
> i installed in with:
> pip install git+https://github.com/enthought/mayavi.git

Thank you very much. It works for me.
