### ISSUE TITLE
what is the difference between RoI head and RPN head

### ISSUE THREAD

**Issue by hughlee815** [open-mmlab/OpenPCDet#210]
hi,

thanks for your fantastic work. but i am not very clear about the difference between RoI head and RPN head. Im my view, both of them are the first stage result, namely the proposals.
could you please give some example? thanks

**Comment by sshaoshuai** [comment]
The RoI head means the head to refine the RoIs, so it is used to generate the results of the second stage.

**Comment by hughlee815** [comment]
got it. thanks!
