### ISSUE TITLE
Thank you for your suggestion. In order to speed up the ball query operation, I think it can be achieved by searching neighbour points in the 3d nearby region in ball query module.

### ISSUE THREAD

**Issue by Chunchunyoyo** [open-mmlab/OpenPCDet#215]
Thank you for your suggestion. In order to speed up the ball query operation, I think it can be achieved by searching neighbour points in the 3d nearby region in ball query module. 

In detail, using a hash table to store the valid points coordinates (which can get from SpcovTensor.indices), perform O(1) query for each keypoints to check whether there are some valid voxels in the neighbourhood. In this way, O(n) query can be avoid.

What do you think about this idea?

_Originally posted by @Chunchunyoyo in https://github.com/open-mmlab/OpenPCDet/issues/208#issuecomment-669049817_

**Comment by sshaoshuai** [comment]
Close it due to repeat issue.
