### ISSUE TITLE
New requirements in 0.3.0?

### ISSUE THREAD

**Issue by jacoblambert** [open-mmlab/OpenPCDet#216]
I was able to install OpenPCDET 0.3.0 fine but when trying to test the nuscenes model I get
`/ops/pointnet2/pointnet2_stack/pointnet2_stack_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z36three_interpolate_grad_wrapper_stackN2at6TensorES0_S0_S0_
`
I'm using Cuda 10, PyTorch 1.1, SpConv 1.0, Python 3.6.5. Are these still adequate for 0.3.0?
I tried starting again from a clean conda environment with these specs but no luck. Any idea what the issue might be?

**Comment by sshaoshuai** [comment]
You need to delete the `OpenPCDet/build` directory before you run `python setup.py develop`, have you tried it?

**Comment by jacoblambert** [comment]
Thank you!! Solved.

**Comment by clw5180** [comment]
> You need to delete the `OpenPCDet/build` directory before you run `python setup.py develop`, have you tried it?

大佬tql，一眼看出问题

**Comment by thelandord** [comment]
牛呗！
