### ISSUE TITLE
Inference time?

### ISSUE THREAD

**Issue by hulsmeier** [open-mmlab/OpenPCDet#219]
I was wondering if any of these methods would be able to run  > 10 fps on full 360 point cloud for pedestrian detection only?

**Comment by sshaoshuai** [comment]
By modifying the configuration files, all these methods could  be able to run on full 360 point cloud for pedestrian detection. The speed depends on the running environment, and you could refer to the inference time to approximately figure out the speed order of the inference time for different methods.
