### ISSUE TITLE
evaluation problem

### ISSUE THREAD

**Issue by hughlee815** [open-mmlab/OpenPCDet#220]
hi,
it's a evaluation problem. when i run the `evaluation()` function in evaluate.py separately, the result is very strange. specifically, i run 
` path1 = '/home/OpenPCDet/pcdet/datasets/kitti/kitti_object_eval_python/label'`
` path2 = '/home/OpenPCDet/pcdet/datasets/kitti/kitti_object_eval_python/pred'`
` path3 = '/home/OpenPCDet/pcdet/datasets/kitti/kitti_object_eval_python/trainval.txt'`
` result = evaluate(path1,path2,path3)`  
 `print(result)`
the txt files in both `/label `dir and `/pred` are totally same, because the pred files are copied from label dir.
I think, i should get every metric as 100. but the result is:
'Car AP@0.70, 0.70, 0.70:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.1224, 0.1552, 0.2503
3d   AP:0.1224, 0.1552, 0.2503
aos  AP:100.00, 100.00, 100.00
Car AP_R40@0.70, 0.70, 0.70
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0673, 0.0854, 0.1377
3d   AP:0.0673, 0.0854, 0.1377
aos  AP:100.00, 100.00, 100.00
Car AP@0.70, 0.50, 0.50:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.1224, 0.1552, 0.2503
3d   AP:0.1224, 0.1552, 0.2503
aos  AP:100.00, 100.00, 100.00
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0673, 0.0854, 0.1377
3d   AP:0.0673, 0.0854, 0.1377
aos  AP:100.00, 100.00, 100.00

i am trying to figure it out, but i only find 
https://github.com/open-mmlab/OpenPCDet/blob/07419768607d76ee16b4f8d641ee7f1990ec55d8/pcdet/datasets/kitti/kitti_object_eval_python/eval.py#L473
in this line, the parameter order are wrong. but it seems not matter.

thanks for your attention.

**Comment by sshaoshuai** [comment]
There is a small bug (from the original authors) in kitti_eval, so the pred and labels could not be exactly the same. You could add a small noise to the pred and see the eval results.
