### ISSUE TITLE
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by higolel** [open-mmlab/OpenPCDet#231]
python3 demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt pv_rcnn_8369.pth --data_path /home/lel/Documents/DATA/kitti_velodyne/training/velodyne/000001.bin

**Comment by higolel** [comment]
failed

**Comment by ZJDWKTX** [comment]
i meet
libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
have you sovel it?
