### ISSUE TITLE
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by higolel** [open-mmlab/OpenPCDet#233]
python3 demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt pv_rcnn_8369.pth --data_path /home/lel/Documents/DATA/kitti_velodyne/training/velodyne/000001.bin
please help me

**Comment by ltphy** [comment]
Reinstall pytorch can help you resolve the problem. What is your current pytorch version?

**Comment by higolel** [comment]
pytorch is 1.5.0 cuda 10.1 python3.6 

Do you need to compile libtorch ？

**Comment by HuaxuDuan** [comment]
env: Ubuntu 18.04 + Python3.6 + PyTorch 1.5 + cuda10.2 + spconv1.2.1
run demo.py
OSError: libcuhash.so: cannot open shared object file: No such file or directory
