### ISSUE TITLE
How does deal with the ".pcd" point cloud files to the unified normative coordinate of `OpenPCDet`.

### ISSUE THREAD

**Issue by FujieLuo** [open-mmlab/OpenPCDet#236]
How does deal with the ".pcd" point cloud files to the unified normative coordinate of `OpenPCDet`.
thank you very much!

**Comment by ltphy** [comment]
You can read ".pcd" files by [Open3D](https://github.com/intel-isl/Open3D) library. 
I think you misunderstand the unified normative coordinate. You convert the position of object (x, y, z, w, l, h, rz) in 3D space to the unified normative coordinate not the point cloud points.

**Comment by xxp912** [comment]
> ok,thank you very much, I have solved the problem with "import pcl"
我想跟您请教一下关于OpenPCDet读取pcd文件的问题，但是找不到您的邮箱，看到可以可以加一下我的微信（xxp18500728702）吗？非常感谢!
