### ISSUE TITLE
how to transform pytorch model to torchscript by libtorch

### ISSUE THREAD

**Issue by Sherry04** [open-mmlab/OpenPCDet#237]
how to transform pytorch model to torchscript by libtorch

**Comment by ltphy** [comment]
Similar as my issue [131](https://github.com/open-mmlab/OpenPCDet/issues/131).

**Comment by Sherry04** [comment]
> Similar as my issue [131](https://github.com/open-mmlab/OpenPCDet/issues/131).

thx
