### ISSUE TITLE
How can i prepare our own data for inference?

### ISSUE THREAD

**Issue by kaushikCanada** [open-mmlab/OpenPCDet#241]
For example i would liek to use this on toronto-3d dataset which has pointwise labels but not ready for object detection. This data is in the form of ply files. What do i need to do to be able to detect objects in this data usign this library?

**Comment by clare19997** [comment]
> For example i would liek to use this on toronto-3d dataset which has pointwise labels but not ready for object detection. This data is in the form of ply files. What do i need to do to be able to detect objects in this data usign this library?

I have the same issues, did you solved?
