### ISSUE TITLE
Questions about the number of keypoints in pvrcnn

### ISSUE THREAD

**Issue by GalaxyWM** [open-mmlab/OpenPCDet#249]
Thanks for ur good project.
There's a question about the number of keypoints in pvrcnn. I find that only a few keypoints (average is about 30) are used by 216 grid points for refining, and i try to use more keypoints to get better performance, but it fails
i wonder how to explain this phenomenon, and why 2048 keypoints are enough
thx

**Comment by sshaoshuai** [comment]
It is a hyperparameter and need to be tuned for different datasets and sensors, and for KITTI dataset, I could achieve similar performance with both 4096 keypoints and 2048 keypoints.
