### ISSUE TITLE
Trying to train a model with fewer GPUs

### ISSUE THREAD

**Issue by davidwang200099** [open-mmlab/OpenPCDet#251]
According to [the paper](https://arxiv.org/abs/1912.13192), the model was trained with 8 GPUs. However, I only have 2 GPUs at hand. So how can I modify the training and testing code to simulate training with 8 GPUs, in order to get the official results?

**Comment by sshaoshuai** [comment]
Yes, 2 GPUs could also achieved similar performance, and you just need to set the proper batch_size according to your GPU numbers.
