### ISSUE TITLE
undefined symbol: THPVariableClass

### ISSUE THREAD

**Issue by stratomaster31** [open-mmlab/OpenPCDet#254]
I've installed OpenPCDet following **install.md** on the **spconv docker image**. Under python3.8 everything goes well, but under python3.6 I get:

    ImportError: /home/ML_tools/python/pcdet_api/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-36m-x86_64-linux- 
    gnu.so: undefined symbol: THPVariableClass

Both python3.8 and python3.6 I have the same version of pytorch;

          print(torch.__version__)
          1.6.0+cu101

          print(torchvision.__version__)
          0.7.0+cu101

Thank you very much!

**Comment by twn29004** [comment]
Hello, Can you tell me how you solve it?

**Comment by yinggo** [comment]
I meet the same problem, could anyone can help?
