### ISSUE TITLE
Do not see the bin based reg loss for bbox in pointrcnn?

### ISSUE THREAD

**Issue by v-wewei** [open-mmlab/OpenPCDet#255]
Dear author , i do not find the bin based reg loss for bbox just used by pointrcnn repository, did you remove that part ? why did you remove it ?

**Comment by sshaoshuai** [comment]
Yes, I just found this new codebase could also achieve promise results without bin-based localization, so I didn't try to add it yet. Maybe I will find time to support the bin-based localization later.

**Comment by v-wewei** [comment]
@sshaoshuai Thanks, i just wonder the improvement that bin-based localization loss could bring to the baseline (default SMOOTH_L1).

**Comment by sshaoshuai** [comment]
I didn't do the related exp in this new codebase yet.
