### ISSUE TITLE
Other Classes

### ISSUE THREAD

**Issue by josy43** [open-mmlab/OpenPCDet#256]
According to the website of Kitti Benchmark there are more classes then Car, Pedestrian and Cyclist, for example Tram and Truck. Is there any pretrained model which considers also other classes ?

**Comment by sshaoshuai** [comment]
No, you could modify the config file and train them by yourself.

**Comment by josy43** [comment]
Thanks for the fast reply. Do I just have to add the classes in CLASS_NAMES in the yaml file? 
What does Anchor_Generator_CONFIG mean ?
And a question about the visualization: How do I display the classname next to the confidence value ?

Thanks

**Comment by sshaoshuai** [comment]
You also need to modify other parts that have the class-related settings, such as the GT_sampling augmentation, anchor setting. 
The Anchor_Generator_CONFIG aims to set anchors for each class.  

I suggest that you could refer to the nuscenes configs to see how to detect more classes by comparing the configs between KITTI and NuScenes. 

For visualization, you need to explore the mayavi tools and add the features by yourself.

**Comment by daeunni** [comment]
> According to the website of Kitti Benchmark there are more classes then Car, Pedestrian and Cyclist, for example Tram and Truck. Is there any pretrained model which considers also other classes ?

@josy43  
Have you solved this problem? I'm thinking about the same problem.

How did you se**t Anchor_Generator_CONFIG** for classes **other** than Car, Ped, and Cyclist?
