### ISSUE TITLE
Running nuScenes trained second_multihead model on KITTI

### ISSUE THREAD

**Issue by sasupe** [open-mmlab/OpenPCDet#258]
Hi Team,
Thank you for providing this repository!

I am trying to run second-multihead trained with nuScenes on KITTI to get 360 degree detections.  

I was able to run the nuScenes trained model on KITTI using the cbgs_second_multihead.yaml and using kitti_dataset.yaml. I changed the POINT_CLOUD_RANGE and VOXEL_SIZE to what nuscenes_dataset.yaml had. The results look reasonable.

Is there a correct way to run a nuScenes trained second_multihead on KITTI to get 360 degree detections?

Thank You!

**Comment by sshaoshuai** [comment]
@sasupe , Yes, it is correct. But you should notice that your KITTI input is correct, since the provided NuScenes models are based on 10frames for detection. Also I think the performance should not be good enough when directly adopting it on KITTI dataset since there is a domain gap between two datasets.

**Comment by kadebudongtan** [comment]
> Hi Team, Thank you for providing this repository!
> 
> I am trying to run second-multihead trained with nuScenes on KITTI to get 360 degree detections.
> 
> I was able to run the nuScenes trained model on KITTI using the cbgs_second_multihead.yaml and using kitti_dataset.yaml. I changed the POINT_CLOUD_RANGE and VOXEL_SIZE to what nuscenes_dataset.yaml had. The results look reasonable.
> 
> Is there a correct way to run a nuScenes trained second_multihead on KITTI to get 360 degree detections?
> 
> Thank You!

Hey, you said your result is reasonable. could you pls share your config files? I just use the provided cbgs_pp_multihead model to visualize the kitti data, the results are changeable and terrible.
