### ISSUE TITLE
Question about submanifold sparse convolution layer in Part-A2 stag-2

### ISSUE THREAD

**Issue by 3bobo** [open-mmlab/OpenPCDet#259]
Thanks for ur good work.
Here are my questions. In the stage-2 of Part-A2 in the paper, you claim that you use a submanifold sparse convolution layer to transform the pooled part locations to the same feature dimensions of semantic features, and after obtain the fused features, you input it to severl sparse convolution layers and a sparse pooling layer. 
However, I found that in the code you use sparseconv for both pooled part features and pooled semantic features.
https://github.com/open-mmlab/OpenPCDet/blob/9e460da23163dffcca007ac8725221257cf36d55/pcdet/models/roi_heads/partA2_head.py#L196-L203
Second, there is no sparseconv layers and sparsepool layer after the shared feature.
https://github.com/open-mmlab/OpenPCDet/blob/9e460da23163dffcca007ac8725221257cf36d55/pcdet/models/roi_heads/partA2_head.py#L203-L210
The two operations are different from the paper, thus I'm confused, can you explain these? did I miss something?
thx

**Comment by sshaoshuai** [comment]
1. The sparse convolutions are used to transform the features of sparse pooled voxels to the same dimensions. And we adopt sparse conv on both the part locations and features to transform them to the same dimentions. 
2. After the features are downsampled by sparse-max-pool, we reshape it to a single feature vector and adopt FC layers for the final prediction. 
I think they are consistent with the papers.

**Comment by 3bobo** [comment]
Thanks for your reply, but I still don't understand.
1. In the Section 3.3, part "Fusion of predicted part locations and semantic part features." of the paper, you use submanifold sparse convolution layer to transform the pooled part locations Q(part) to the same feature dimensions to match Q(sem), as far as I can see, the sparse convolutions are only used on Q(part), not both of them as the code shows.
2. In the Fig-2 of the paper, if my understanding is right, after the feature fusion, you stack several 3D sparse convolutional layers with kernel size 3 × 3 × 3 for the fusion feature Q(roi). But in the code, it seemed that it forward part feature and rpn features separately. And after forward, you fusion them. And could you point out where is the sparse convolutional layers and the sparse max-pooling after feature fusion?
Thanks!

**Comment by sshaoshuai** [comment]
1. We use the following lines to conduct sparse conv on Q(part) and Q(sem) separately: 
https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/models/roi_heads/partA2_head.py#L200-L201

2. Sorry for the confusion. In this part, the released codes have a little difference with the original model (reported in paper). In the released codes, instead of using sprase conv & sparse max pooling, we directly reshape the sparse features to a feature vector and use shared MLP to extract features from RoI, since the performance of this version is more stable than the max-pooling one. 

https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/models/roi_heads/partA2_head.py#L203-L207

**Comment by 3bobo** [comment]
@sshaoshuai thanks for your relpy, so would you plan to release the code as the paper?

**Comment by sshaoshuai** [comment]
It has been released in previous version (https://github.com/open-mmlab/OpenPCDet/blob/v0.1/tools/cfgs/PartA2_car.yaml#L124-L146).
