### ISSUE TITLE
Real time Object Detection

### ISSUE THREAD

**Issue by josy43** [open-mmlab/OpenPCDet#263]
Somebody know a workflow, how to use the algorithms in real time in ROS and visualize the predictions in RVIZ ?

**Comment by hcyoo93** [comment]
I do not know much about it, but you can refer 
https://github.com/Autoware-AI/core_perception/tree/master/lidar_point_pillars

You need a trained model(checkpoint) and a point cloud input stream(pointcloud message) for real time inference
