### ISSUE TITLE
about Data Augmentation

### ISSUE THREAD

**Issue by davidwang200099** [open-mmlab/OpenPCDet#267]
I noticed that several functions, such as ```random_world_flip```, ```random_world_rotation```, and ```random_world_scaling``` were implemented in ```data_augmentor.py```. However, I read through the code, only to find no function invoking them to carry out data augmentation. I put some lines of code in the three functions above to get some log, and found that data augmentation is carried out when trying to train each epoch. Can some functions in pytorch invoke the data augmenter to carry out data augmentation?

**Comment by jihanyang** [comment]
Please check `prepare_data` in `dataset.py`.

**Comment by davidwang200099** [comment]
Thanks! I find it!

**Comment by Petros626** [comment]
@davidwang200099 @jihanyang  could you tell me how I can do data augmentation on a dataset e.g. like KITTI?
