### ISSUE TITLE
support for waymo dataset

### ISSUE THREAD

**Issue by bigsheep2018** [open-mmlab/OpenPCDet#271]
Hello openpcdet team @sshaoshuai ,

I noticed your PV-RCNN paper is updated with a waymo dataset benchmark result. May I know when will the code for waymo dataset be published?

Thanks in advance.
Lin

**Comment by LZDSJTU** [comment]
Hi, is there any update on Waymo?

**Comment by sshaoshuai** [comment]
@LZDSJTU I am busy for another work now and will sort out the waymo codes recently.
