### ISSUE TITLE
'align_center' param in ANCHOR_GENERATOR_CONFIG

### ISSUE THREAD

**Issue by Qiuzhongyuan** [open-mmlab/OpenPCDet#272]
could you tell me why you set 'False' about the 'align_center' param in ANCHOR_GENERATOR_CONFIG? I think 'align_center=True' is right, and the anchors can precisely match the voxel grids.

**Comment by sshaoshuai** [comment]
I just samply set it to False to align the performance with old code repo. You could have a try with the `align_center=True` by yourself.

**Comment by Qiuzhongyuan** [comment]
OK,thanks
