### ISSUE TITLE
How to get the result of the test set?

### ISSUE THREAD

**Issue by suqi10** [open-mmlab/OpenPCDet#276]
How to get the result of the test set?
Is it necessary to submit the test predicted result to The KITTI Vision Benchmark Suite?
Thank you in advance for your help. @sshaoshuai @jihanyang

**Comment by jihanyang** [comment]
#125

**Comment by suqi10** [comment]
@jihanyang 
Is the result of the test the saved predicted Bbox（.txt）?
Is it necessary to submit the test predicted result to The KITTI Vision Benchmark Suite?

**Comment by jihanyang** [comment]
Both yes. @suqi10

**Comment by suqi10** [comment]
thanks for your reply@jihanyang
