### ISSUE TITLE
DATA_CONFIG in model cfg

### ISSUE THREAD

**Issue by thptai** [open-mmlab/OpenPCDet#282]
In the model config file such as pv_rcnn.yaml, there are some parameters that I don't know their roles.

              SAMPLE_GROUPS: ['vehicle:20','pedestrian:15']
              NUM_POINT_FEATURES: 4
              DATABASE_WITH_FAKELIDAR: False
              REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
              LIMIT_WHOLE_SCENE: False

Can you explain for me the meaning of each parameters here ? Thank you.

**Comment by MartinHahner88** [comment]
@thptai 
- `SAMPLE_GROUPS: ['vehicle:20','pedestrian:15']` sample 20 additional vehicles and 15 additional pedestrians per scene

- ` NUM_POINT_FEATURES: 4` for x, y, z, reflectance

- `DATABASE_WITH_FAKELIDAR: False` to my understanding only needs to be set to `True` for pcdet v0.1 (see [here](https://github.com/open-mmlab/OpenPCDet/issues/186#issuecomment-665397145))

The other two I don't know, but you can always have a look in the code where they are used.
