### ISSUE TITLE
在运行python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml时出错

### ISSUE THREAD

**Issue by alixiansen91** [open-mmlab/OpenPCDet#292]
您好，我在运行python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
时出现    assert img_file.exists()
               AssertionError
这样的错误，请问是为什么呢

**Comment by PengfeiMa** [comment]
先检查一下路径，img_file是否存在

**Comment by wind19970924** [comment]
---------------Start create groundtruth database for data augmentation---------------
gt_database sample: 1/16
段错误 (核心已转储)
我也是运行这个create_kitti_infos 出错，请问有遇到相同问题的吗，如何解决，多谢

**Comment by sshaoshuai** [comment]
Please check whether you have succesully installed the PCDet.

**Comment by yimingshan666** [comment]
hi, I met the same issue. Did you fix it?

**Comment by xuezhen5267** [comment]
重新解压以下数据集试试，我重新解压数据以以后没有这个报错了，有时候解压的时候可能会损坏某个图像文件，到时程序无法打开这个文件，造成上述报错。
