### ISSUE TITLE
Is there any way to run this on windows?

### ISSUE THREAD

**Issue by kcabhishek** [open-mmlab/OpenPCDet#296]
Is there any way to run this on windows? I see that this require SpConv (PyTorch Spatially Sparse Convolution Library) which currently does not support windows.

**Comment by sshaoshuai** [comment]
Yes, maybe you should first solve the problem of SpConv. But for some models which do not need spconv (PointRCNN, PointPillar), maybe you could try to build it in Windows, but I never tried it.
