### ISSUE TITLE
X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by kirima-h** [open-mmlab/OpenPCDet#297]
run for a quick demo, error has happened:
020-09-23 21:54:17,325   INFO  ==> Loading parameters from checkpoint pointpillar_7728.pth to CPU
2020-09-23 21:54:17,407   INFO  ==> Done (loaded 127/127)
2020-09-23 21:54:17,477   INFO  Visualized sample index: 	1
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x0
Serial number of failed request:  9
Current serial number in output stream:  9

**Comment by yuandm** [comment]
I have also met this error。 please tell me how to fix?
