### ISSUE TITLE
Cannot detect the target in the first quadrant

### ISSUE THREAD

**Issue by Sunshine008** [open-mmlab/OpenPCDet#300]
I installed a lidar somewhere at the intersection and use PVRCNN to train the data set of the intersection. Strangely, as long as the x_min of POINT_CLOUD_RANGE is set to negative, the target in the first quadrant cannot be detected. Has anyone encountered this problem？

**Comment by sshaoshuai** [comment]
Maybe you need to give more details such as the configs or some figures for visualization.

**Comment by sshaoshuai** [comment]
Close it since no further response.
