### ISSUE TITLE
Typo in setting self.separate_multihead in AxisAlignedTargetAssigner

### ISSUE THREAD

**Issue by DrBaer** [open-mmlab/OpenPCDet#302]
https://github.com/open-mmlab/OpenPCDet/blob/f982b5bfdf0e8e15a2e2d7fead2925ff564051d7/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py#L28

I guess the name should be 'SEPARATE_MULTIHEAD' instead looking at the provided cfgs. Otherwise, the setting in the configs has no impact.

**Comment by sshaoshuai** [comment]
Thank you for the bug report. I will fix it soon

**Comment by sshaoshuai** [comment]
Fixed in https://github.com/open-mmlab/OpenPCDet/pull/352/
