### ISSUE TITLE
Some question about the feature shape in the VoxelBackBone8x

### ISSUE THREAD

**Issue by HilbertXu** [open-mmlab/OpenPCDet#304]
Hello,

Sincerely thanks for your great work!
I am trying to use PV-RCNN in my project and trying to figure out how it works. However I was confused by the change of feature shape in the VoxelBackBone8x module.
Here is the output of my console showing the feature shape after each block:
![console-pv-rcnn](https://user-images.githubusercontent.com/33152255/95034096-11c6e880-06f3-11eb-8a05-a4bfce4ac3f4.png)

And here is the source code of VoxelBackBone8x used in PV-RCNN:
![pv-rcnn-backbone](https://user-images.githubusercontent.com/33152255/95034124-2dca8a00-06f3-11eb-8201-8889f2c4c53a.png)

I'm puzzled by the change of feature shape from [40000,x]->[45826,x]->[23095,x]->[8811,x]. The first number should refer to the number of voxel, so what changes it? Especially, what makes it more than the input feature shape?

**Comment by sshaoshuai** [comment]
It is the number of non-empty voxels, and the sparse conv operation will change the non-empty voxels. You need to first understand what the sparse conv is doing.
