### ISSUE TITLE
help，KeyError: 'point_cloud'

### ISSUE THREAD

**Issue by wind19970924** [open-mmlab/OpenPCDet#305]
the error in running train.py
File "/home/nvidia/OpenPCDet-master/pcdet/datasets/kitti/kitti_dataset.py", line 347, in __getitem__
    sample_idx = info['point_cloud']['lidar_idx']
KeyError: 'point_cloud'.

thanks a lot

**Comment by jihanyang** [comment]
Try to check your created kitti infos. It looks like something wrong for your created infos.

**Comment by Rajat-Mehta** [comment]
@jihanyang what should we check in info files? I am also getting this error? 

@wind19970924 how to resolve this issue?

**Comment by guzuoxu** [comment]
> the error in running train.py File "/home/nvidia/OpenPCDet-master/pcdet/datasets/kitti/kitti_dataset.py", line 347, in **getitem** sample_idx = info['point_cloud']['lidar_idx'] KeyError: 'point_cloud'.
> 
> thanks a lot

have you solved this problem?

**Comment by crjxixixi** [comment]
> > the error in running train.py File "/home/nvidia/OpenPCDet-master/pcdet/datasets/kitti/kitti_dataset.py", line 347, in **getitem** sample_idx = info['point_cloud']['lidar_idx'] KeyError: 'point_cloud'.
> > thanks a lot
> 
> have you solved this problem?
  have you solved the problem?  I meet the same problem as U
