### ISSUE TITLE
Does anyone succed install pcdet in CentOS ?

### ISSUE THREAD

**Issue by cuge1995** [open-mmlab/OpenPCDet#306]

**Comment by riceleslie** [comment]
yeah . I've just installed it in CentOS and run the demon successfully.

**Comment by cuge1995** [comment]
> yeah . I've just installed it in CentOS and run the demon successfully.

Which version ? 7 or 6 ?

**Comment by riceleslie** [comment]
> > yeah . I've just installed it in CentOS and run the demon successfully.
> 
> Which version ? 7 or 6 ?

CentOS Linux release 7.8.2003

**Comment by cowarder** [comment]
@riceleslie Hi, riceleslie, how did you install spconv on centos? spconv supports linux only. If you want to install spconv, you must install libboost-all-dev, as far as I know, libboost-all-dev can't be install for centos.

**Comment by jihanyang** [comment]
@cowarder Try conda install libboost
