### ISSUE TITLE
Question about sharp change of val performance

### ISSUE THREAD

**Issue by GalaxyWM** [open-mmlab/OpenPCDet#314]
Thanks for ur advanced work.
I trained pvrcnn with 2 gpus and 100 epochs. Although the result(R11) is sometimes up to 83.xx, it changes sharply between 79.xx and 83.xx.  what could be the reason of this phenomenon?  I dont have 8 gpus/16batchsize, should i train it with more epochs for better performance?
thx

> Car AP@0.70, 0.70, 0.70:
bbox AP:95.5207, 89.6188, 89.2035
bev  AP:90.0833, 88.1467, 87.6281
3d   AP:89.1947, 79.3723, 78.7745
aos  AP:95.49, 89.50, 89.03
>Car AP@0.70, 0.70, 0.70:
bbox AP:95.7438, 89.5860, 89.2279
bev  AP:90.1028, 88.0891, 87.5568
3d   AP:89.1687, 83.5119, 78.7291
aos  AP:95.72, 89.48, 89.06

**Comment by sshaoshuai** [comment]
It is a known problem of KITTI dataset, and I didn't have idea about it.
