### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by MYSystemLogistics** [open-mmlab/OpenPCDet#315]
Hi,

when I try to install the pcdet library by running the command `sudo python3 setup.py develop` I get:
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
```
But it's strange since if I check my PyTorch version I get:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__) 
1.6.0
```
All the requirements are satisfied, spconv v1.2 was installed successfully, so how can I solve this problem?
Thank you for your attention.

**Comment by sshaoshuai** [comment]
Please check whether the `python` in your `sudo python3 setup.py develop` is what you want to use.

**Comment by Petros626** [comment]
Hey guys @sshaoshuai @MYSystemLogistics for me the same, how you solved it?

Update: with `pip install -e . --use-pep517 --no-build-isolation` you can solve it. I use Python 3.9, CUDA11.8 and 2.7.1+cu118 in my anaconda venv.
