### ISSUE TITLE
Is it possible to train pointrcnn on nuscenes dataset? 

### ISSUE THREAD

**Issue by barryhe** [open-mmlab/OpenPCDet#318]
I am trying to run adapt PointRCNN's config to Nuscenes data, but it doesn't seem to work if we just replace the input data with nuscene's config file. Replacing VOXEL_SIZE and POINT_CLOUD_RANGE with Kitti's config doesn't work either. Is there anything I should try to make it work? Thanks!

**Comment by sshaoshuai** [comment]
I haven't try to run PointRCNN on NuScenes. It should be possible to run on the NuScenes dataset but the performance may need be carefully tuned. 
Welcome to submit a pull request If you could get good performance on the Nuscenes dataset.
