### ISSUE TITLE
Are there potential bugs in three_nn or three_interpolate in pointnet2_stack.py?

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/OpenPCDet#324]
Hello, in this line: 
https://github.com/open-mmlab/OpenPCDet/blob/f982b5bfdf0e8e15a2e2d7fead2925ff564051d7/pcdet/models/backbones_3d/pointnet2_backbone.py#L99
You said that this may have some potential bugs. But I noticed that you have used **_pointnet2_modules_** and **_pointnet2_utils_** imported from pointnet2_stack.py in voxel_set_abstraction.py. 

I just want to use **_three_nn_** or **_three_interpolate_** in pointnet2_stack, thus I hope that you could reply to me so I can decide whether to use them.

Thanks a lot.

**Comment by tianweiy** [comment]
Hi, you can write simple function in pytorch. Basically, compute the distance and then use topk(3). For example, see the following code 

```
    dist = torch.norm(unknown.unsqueeze(1) - known.unsqueeze(0), dim=-1) 
    dist, idx = torch.topk(dist, k=3, dim=1, largest=False, sorted=False) 
    dist_recip = 1.0 / (dist + 1e-8)
    norm = torch.sum(dist_recip, dim=1, keepdim=True)
    weight = dist_recip / norm

    interpolated_feats = torch.sum(known_feats[idx] * weight.unsqueeze(-1), dim=1)
```
That seems faster than the cuda code in my environment.
