### ISSUE TITLE
Difference: train from checkpoint - train from pretrained model

### ISSUE THREAD

**Issue by KuenkeleM** [open-mmlab/OpenPCDet#332]
Hello,

I have a question regarding the training configuration. What is the difference in training with the option:

1) '--ckpt', type=str, default=None, help='checkpoint to start from'
2) '--pretrained_model', type=str, default=None, help='pretrained_model'

Thank you for your help.

**Comment by MartinHahner** [comment]
`--pretrained_model` does not load the optimizer state

**Comment by KuenkeleM** [comment]
thank you!
