### ISSUE TITLE
Train PV-RCNN on WOD

### ISSUE THREAD

**Issue by Lzc6996** [open-mmlab/OpenPCDet#335]
Hello,
I m trying to train PV-RCNN on Waymo Open Dataset. I have organized WOD data in KITTI format using mmdet3d. 
Can I just modify the data path in KITTI cfgs? Are there some other different settings that should be noticed between KITTI and WOD?
If the WOD training code is not ready, could u provide a pre-trained PV-RCNN model?

**Comment by sshaoshuai** [comment]
I will support Waymo dataset and provide the configs within one week.

**Comment by faizansid77** [comment]
@sshaoshuai any updates?

**Comment by sshaoshuai** [comment]
The Waymo Open Dataset has been supported with state-of-the-art results just now.
