### ISSUE TITLE
Question about the time consumption of training on the nuScenes

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/OpenPCDet#342]
Has anyone tried to train a model on the nuScenes? I run total 32 batches on two GPUs with _cbgs_second_multihead.yaml_, and each epoch takes nearly 5 hours. Even with 20 epochs, it would take 100 hours, which is about 5 days. This time consumption is too expensive. Can someone share the experience of training on nuScenes?

**Comment by MartinHahner** [comment]
nuScenes is significantly larger than KITTI, that's why it takes so long. It's just the way it is.

**Comment by jialeli1** [comment]
Well, thank you for sharing.
