### ISSUE TITLE
About visualizing the testing data

### ISSUE THREAD

**Issue by davidwang200099** [open-mmlab/OpenPCDet#345]
I tried to install mayavi in my server, but failed. Must the desktop environment be installed?

**Comment by brudermueller** [comment]
It should work without any mayavi deskop environment. For me it helped to execute the installation script provided in the FrustumPointnet Repo: https://github.com/charlesq34/frustum-pointnets/tree/master/mayavi 
They also provide a test script.

**Comment by davidwang200099** [comment]
I mean should I install the desktop environment of the Operating System? The OS of my server is ubuntu and ubuntu desktop environment is not installed.

**Comment by brudermueller** [comment]
Sorry, the question wasn't clear. I am also training on a server remotely and I am using mayavia via ssh in a jupyter notebook to visualize the result. This tutorial helped me to set it up: https://github.com/kuixu/kitti_object_vis/tree/master/jupyter

**Comment by sshaoshuai** [comment]
You should either visualize with the desktop environment or just as @brudermueller said to use ssh.
