### ISSUE TITLE
Is data augmentation necessary?

### ISSUE THREAD

**Issue by NLCharles** [open-mmlab/OpenPCDet#353]
Suppose I have a lot of data, and I would like to use them without augmentation. Can I jump to training stage by disable some triggers?

**Comment by jihanyang** [comment]
Sure. Check the DATA_AUGMENTOR.DISABLE_AUG_LIST to put the data augmentation that you not want to do in dataset cfg.

**Comment by NLCharles** [comment]
Thank you very much.
