### ISSUE TITLE
Execution speed of PVRCNN on waymo dataset per point cloud?

### ISSUE THREAD

**Issue by DeepakVellampalli** [open-mmlab/OpenPCDet#354]
@sshaoshuai 

Kindly specify execution time of PVRCNN on waymo dataset per point cloud?

**Comment by sshaoshuai** [comment]
It costs about 300ms per sample on the Waymo Dataset with detection range 150m x 150m.

**Comment by ChidanandKumarKS** [comment]
For the PVRCNN waymo model of range 75m x75m, what would be the inference time per pointcloud as given in this current repository https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/waymo_dataset.yaml#L5

**Comment by ChidanandKumarKS** [comment]
Sorry got the solution from your previous answers
