### ISSUE TITLE
Why the values SAMPLE_GROUPS: ['Vehicle:15', 'Pedestrian:10', 'Cyclist:10'] in PVRCNN>

### ISSUE THREAD

**Issue by DeepakVellampalli** [open-mmlab/OpenPCDet#363]
@sshaoshuai 
Kindly tell why the value of SAMPLE_GROUPS for Vehicle/Pedestrian/Cyclist in PVRCNN waymo dataset at line

https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/waymo_dataset.yaml#L29

**Comment by sshaoshuai** [comment]
They are just some hyper-parameters and  you could also change them to other resonable values by visualizing the generated data.

**Comment by chowkamlee81** [comment]
@sshaoshuai 
Is there is any logic behind giving values
VEHICLE 15
Pedestrain/Cyclist 10 ?
Sorry that i didnt understood your answers, kindly help

**Comment by sshaoshuai** [comment]
No, I just set them by visualizing the augmented data.

**Comment by chowkamlee81** [comment]
Thanks @sshaoshuai  i got your point
