### ISSUE TITLE
The training scale of pv_rcnn_small_best

### ISSUE THREAD

**Issue by wuyujiji** [open-mmlab/OpenPCDet#364]
Hi, Recently I trained the pv_rcnn_small_best with distributed dataparallel. When I trained with 3nodes 24gpus, the perfomance will drop 8% over the 8gpus of 1nodes. So I want to known how many the maximum number of GPUs you are currently using to train？How can I tune when a lot of GPUs training performance drops？

**Comment by sshaoshuai** [comment]
You could simply try to train with more epochs if you use more GPUs.

**Comment by wuyujiji** [comment]
could you please share your maximum training scale?

**Comment by sshaoshuai** [comment]
I have tried to train with 32 GPUs on the Waymo dataset.
