### ISSUE TITLE
Will an already running script be affected by subsequent changes ? 

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/OpenPCDet#366]
Hi. I have a weird question that I want to ask you or someone for help. 

In such a situation, I first start training Model1 by running _train.py_, and then I start training Model2 also by _train.py_. I added _print()_ in some places in Model2 to check some values, but the strange thing is that _print()_ will also start in the terminal where I run Modle1. It looks like an already running script will be affected by subsequent changes. 

If this is the case, can I train two or more models with different settings at the same time? In my experiments, when I train multiple models at the same time, the performances are usually not reproducible. I just want to know whether the running models affect each other.

**Comment by sshaoshuai** [comment]
I didn't find such problems. Generally the running model will not be affected by the other subsequent changes, but I guess it may also depend on where you added the print function since python is dynamically typed.
