### ISSUE TITLE
A contiguous() could be added after the transpose() to avoid a bug aboud non-contiguous gradient.

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/OpenPCDet#368]
Hi. In line 150 and 152 in _pointrcnn_head.py_, a _contiguous()_ could be added after the _transpose()_ to avoid a bug about the non-contiguous gradient that I encountered during training.

https://github.com/open-mmlab/OpenPCDet/blob/1145f836f9091c7e6fa1fb825e377f5efac134cc/pcdet/models/roi_heads/pointrcnn_head.py#L150

**Comment by sshaoshuai** [comment]
Thank you for the information. I will fix it.

**Comment by sshaoshuai** [comment]
Done (https://github.com/open-mmlab/OpenPCDet/pull/373).
