### ISSUE TITLE
importing Onnx models to Pytorch?

### ISSUE THREAD

**Issue by ramchandraKarandikar** [open-mmlab/OpenPCDet#369]
Hi I have a prebuilt model in onnx format and I wanted to convert / import it to pytorch. Does OpenPCDet support this operation?

**Comment by sshaoshuai** [comment]
No, we haven't supported this feature currently.
Duplicated with https://github.com/open-mmlab/OpenPCDet/issues/228.

**Comment by ramchandraKarandikar** [comment]
Okay, This can be a separate issue than the one referenced above: #228 Since this issue talks about converting onnx models back to pytorch. The referenced issue talks about exporting to pytorch (if I am not mistaken)

**Comment by sshaoshuai** [comment]
I see, welcome to submit a PR if you would like to add this feature. 
But I think only few 3D detection methods could be transformed between onnx and pytorch since there are many customized operations.
