### ISSUE TITLE
How to test one module's runtime or inferring time, such as PV RCNN?

### ISSUE THREAD

**Issue by lihua213** [open-mmlab/OpenPCDet#387]
Hello, my dear friend, could I know how to test one module's runtime or inferring time, such as PV RCNN?

**Comment by tianweiy** [comment]
insert the following script before and after https://github.com/open-mmlab/OpenPCDet/blob/a07572f389a00dadb859b7186471ef837e044278/pcdet/models/detectors/pv_rcnn.py#L11

```
def get_time():
    torch.cuda.synchronize()
    return time.time()
```

calculate the time difference and store them in a dict with the module name. Then you can compute the average value in https://github.com/open-mmlab/OpenPCDet/blob/a07572f389a00dadb859b7186471ef837e044278/tools/eval_utils/eval_utils.py#L54
