### ISSUE TITLE
results of the pre-trianed  model

### ISSUE THREAD

**Issue by hitxing** [open-mmlab/OpenPCDet#389]
Hi everyone! I've installed this projects and download the pretrained model  for  Second and PV-RCNN,  my problem is: 
when I running demo.py to  see the detected results on KITTI datasets(some samples of KITTI test sets ), the  results is very badly, there are a lot of  false detect results, then I replace the KITTI datasets with my own pointcloud bin file,  the performance is also very poor.
Did anyone occurred the same problem?

![second](https://user-images.githubusercontent.com/52493524/100591041-2bba2b80-3330-11eb-8cab-3e02c07d0e98.png)
![leishen-org](https://user-images.githubusercontent.com/52493524/100591073-370d5700-3330-11eb-898b-65512e3c3793.png)

**Comment by AymanNasser** [comment]
The confidence score of false detections are very low, around 20% so you can threshold the output to a specific score and you won't see these detections @hitxing 
I wanna ask you about something if you could help, when I load the pretrained weights for pv_rcnn and try to run demo.py, it outputs segmentation fault (core dumped), have you faced this issue ?

**Comment by hitxing** [comment]
Thanks for your help, I faced the same problem when I trying to train my own weights but not in the time I load the pretrained weights,I tried some solutions but all failed,finally,I train the weights on another computer and it works.Hope I was helpful!

**Comment by AngYikHong** [comment]
Hi @AymanNasser, may I know how did you change the confidence score of false detection?

**Comment by AymanNasser** [comment]
@AngYikHong  In the output prediction dictionary `pred_dicts, _ = model.forward(data_dict)` in tools/demo **line 91**, you can access the score of each box by `pred_dicts[0]['pred_scores']` and threshold the visualization with a specific score threshold
