### ISSUE TITLE
Error with demo script

### ISSUE THREAD

**Issue by harris-mohamed** [open-mmlab/OpenPCDet#391]
Hello, 

I am setting up OpenPCDet for the first time. I am trying to run the demo script as specified in DEMO.md, but am getting the error:
```
  File "demo.py", line 31
    data_file_list = glob.glob(str(root_path / f'*{self.ext}')) if self.root_path.is_dir() else [self.root_path]
                                                            ^
SyntaxError: invalid syntax
```
Does anyone have any idea what is causing this? Any help would be greatly appreciated. Thanks!

**Comment by turtleMaster20** [comment]
Hi, 

I am having the same issue, how did you solve it?

**Comment by harris-mohamed** [comment]
If I remember correctly, I had the wrong version of spconv set up. You have to use the version specified in the readme.
