### ISSUE TITLE
Multi-head or single-head problem in pointpillars

### ISSUE THREAD

**Issue by Jelvon** [open-mmlab/OpenPCDet#394]
I noticed that there exsit only **single-head** results for **Kitti** dataset and **multi-head** results for **Nuscenes** dataset.

And compared to **Second.git** which clearly assgined **big head** (does not has the **upsampling conv parts**) for cars, trucks,... and **small head** (has **compelete RPN** as normal single head ) for pedestrain, bycycle, the multi-head solution in **Pcdet** is only the combination of two single-head outputs. 

My question is that:
1. How about the performance of multi-head detection using Kitti dataset?
2. Why the multi-head solution here does not apply the Big-Small solution in Second.git?

**Comment by deepmeng** [comment]
I also want to know the performance of OpenPCDet's piontpillars and SECOND when compared with [https://github.com/traveller59/second.pytorch](url) and [https://github.com/nutonomy/second.pytorch](url) in the same evaluation metric.
