### ISSUE TITLE
Can you provide an ATSS config file.

### ISSUE THREAD

**Issue by yeyang1021** [open-mmlab/OpenPCDet#398]
I modified the config file of PointPillars in KITTI_models by modifying the TARGET_ASSIGNER_CONFIG and adding TOPK, but I could not get the normal result. All results are 0.

**Comment by Nightmare-n** [comment]
+1

**Comment by Michael-Shaw** [comment]
I have the same question! I found that the ATSS configuration is only suitable for training single-category models. If you train a multi-category model, the final result will be 0. @sshaoshuai

**Comment by jb892** [comment]
SAME thing happened. Any fix plan? @sshaoshuai

**Comment by XJTU-Haolin** [comment]
I have rewritten the ATSS function. Now the problem is solved. I will put revised code later after multiple test.
