### ISSUE TITLE
about kitti training classes

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/OpenPCDet#399]
Hi, sir. there is a question I want to ask.
 I found in pv_rcnn.ymal, there only `CLASS_NAMES:['Car','Pedestrian','Cyclist']`, so it only use the labels of these three classes to train model and don't use the label of other classes such as van, dontcare? Very appreciate for your reply!

**Comment by jihanyang** [comment]
Yes

**Comment by yustaub** [comment]
thanks for your reply!
