### ISSUE TITLE
Failed: To display results of demo.py with Pycharm connecting to a remote ubuntu server

### ISSUE THREAD

**Issue by Xelawk** [open-mmlab/OpenPCDet#400]
Environment: Pycharm with remote ssh interpreter
Error happens when trying to run demo.py to display the results:
```sh
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/anaconda3/envs/dev/bin/platforms" ...
loaded library "/home/anaconda3/envs/dev/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
Does it exists some other ways to display the results, or just saving the results to jpg, png or any other ways?

**Comment by jihanyang** [comment]
You can save the point cloud and predicted boxes, and then use mayavi to visualize the result on your local pc or laptop.

**Comment by Xelawk** [comment]
> You can save the point cloud and predicted boxes, and then use mayavi to visualize the result on your local pc or laptop.

Thanks

**Comment by ys920826** [comment]
@jihanyang hi, thank you for sharing. This is my first contact with mayavi. I also encountered visualization errors when running demo under docker. Can you explain in detail how to modify the code to save the point cloud and predicted boxes. If you can, please explain how to use mayavi on your local PC to load and display. Thanks!

**Comment by bluestyle97** [comment]
@jihanyang I save the predicted data and try to visualize it on my macbook, but I the mayavi window shows nothing.
![image](https://user-images.githubusercontent.com/20635237/115506297-47a57600-a2ad-11eb-9d62-2feddf724722.png)

**Comment by jihanyang** [comment]
@bluestyle97 Hello, please provide more details about your problem. I have tried to visualize with mayavi on macbook before, but I haven't meet questions.
