### ISSUE TITLE
test result all zeros?

### ISSUE THREAD

**Issue by cowarder** [open-mmlab/OpenPCDet#409]
I trained pv-rcnn with custom data(only 3d point cloud data), the detection performance is fine when visualizing with one sample. But when I run python test.py, the log info is always zero. How to solve this? do I need to change the code?

**Comment by wunan96nj** [comment]
I think maybe its because test set doesn't have labels.

**Comment by xuxuxuchen** [comment]
I have the same issue, did you solve it ?
