### ISSUE TITLE
Confusion about convertion rotation_y in kitti

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/OpenPCDet#411]
Hello,
    I am confused about rot_y convertion between kitti image plane and kitti lidar coordinate system, [lidar_to_image](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/utils/box_utils.py#L165), [image_to_lidar](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/kitti/kitti_dataset.py#L166), I know that their coordinate system is different(image: x right, y down, z front; lidar: x front, y left, z up), can you explain that how the convertion works? Very appreciate for your reply!

**Comment by himanshuak** [comment]
Hello, Did you by any chance get this one. I am trying to get the pointcloud data and ground using Carla Simulator. But I am confused about the sign convention for rotation_y. Any suggestions would be helpful

**Comment by WinckelData** [comment]
DId you find anything out? @himanshuak
