### ISSUE TITLE
Locate evaluation metrics code for trained model

### ISSUE THREAD

**Issue by aamodssg** [open-mmlab/OpenPCDet#413]
I want to evaluate a custom trained model on my dataset. I am having trouble navigating the repository. I want to take a look at the code which calculates all the metrics as mentioned in the readme. Can someone point me to the code file for that? Thanks

**Comment by jihanyang** [comment]
Please fine the `evalutaion` function for pcdet/datasets/kitti/kitti_dataset.py or other dataset files.
