### ISSUE TITLE
Why not evaluate after each epoch's training?

### ISSUE THREAD

**Issue by qiliang72** [open-mmlab/OpenPCDet#414]
Almost all the point cloud recognition source code do training first and evaluate after all the training finished.
Why not do as image recognition that evaluate after each epoch training in order to decide whether to continue training and adjust the learning rate? 
I think it will have better performance.
Anyone has any idea about it ? Thanks!

**Comment by MartinHahner** [comment]
one of the reasons might be that training and evaluation of large scale LiDAR datasets takes more time than smaller image datasets, so you might do not want to "waste" time evaluating every single epoch, but I agree, best practice would be to evaluate (in parallel) "on the fly" / while training
