### ISSUE TITLE
There is my waymo dataset model prediction results, I think the ped/cyc length and width are wrong!

### ISSUE THREAD

**Issue by PengfeiMa** [open-mmlab/OpenPCDet#417]
As describe, but the car bboxes prediction is right, what's wrong with the ped/cyc？ @sshaoshuai 
here are some result and bboxes configs.
 
![image](https://user-images.githubusercontent.com/20807385/103080655-3d31e300-4611-11eb-952c-8f58bf50aab1.png)
![image](https://user-images.githubusercontent.com/20807385/103080695-5175e000-4611-11eb-9673-86698ec53506.png)
![image](https://user-images.githubusercontent.com/20807385/103080721-60f52900-4611-11eb-8d72-a7e386dc14f9.png)

**Comment by yrh2526** [comment]
Have you ever tried training on the kitti dataset?

**Comment by PengfeiMa** [comment]
> Have you ever tried training on the kitti dataset?

kitti dataset is OK, but waymo coordinate origin is ground, so are there some error configs in anchor_bottom_heights?

**Comment by yrh2526** [comment]
> but waymo coordinate origin is ground, so are there some error configs in anchor_bottom_heights?

From the graph, there are some errors in pedestrian ,but from the anchor size, it is reasonable,could it be an error in visual?
Could you show me your envs you trained the kitti dataset?

**Comment by PengfeiMa** [comment]
> > but waymo coordinate origin is ground, so are there some error configs in anchor_bottom_heights?
> 
> From the graph, there are some errors in pedestrian ,but from the anchor size, it is reasonable,could it be an error in visual?
> Could you show me your envs you trained the kitti dataset?

Think you for your reply, I find the error, I used the normalization for the z value in the pointcloud when generate the voxel.
I del the normalize, it looks better.
