### ISSUE TITLE
Problem running Demo.py

### ISSUE THREAD

**Issue by GCaptainNemo** [open-mmlab/OpenPCDet#420]
When I run Demo.py according to demo.md, I get ImportError: /OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass error. How can I fix it?

**Comment by twn29004** [comment]
Have you solved it?

**Comment by GCaptainNemo** [comment]
Yes, but I forget how to solve it. Maybe I rebuilt the project ...
