### ISSUE TITLE
error: command ':/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1 

### ISSUE THREAD

**Issue by brucetend** [open-mmlab/OpenPCDet#421]
Is this question related to the version of my Cuda, but I heard that 10.2 is also possible for other people.

**Comment by KangChou** [comment]
pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp:12:18: fatal error: cuda.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by gzchenjiajun** [comment]
same problem ..
how solved ...

**Comment by MartinHahner** [comment]
Please provide more context. 🤯

**Comment by qrzeffort** [comment]
> Is this question related to the version of my Cuda, but I heard that 10.2 is also possible for other people.

try 'export CUDA_HOME='/cuda/path/' in terminal
