### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Link2Link** [open-mmlab/OpenPCDet#422]
I run PartA^2 on 3090. CUDA11.1, pytorch 1.7. 
This problem appears occasionally when I call the backword calculation. All the forward calculation is OK.

**Comment by ArtificialCleverness** [comment]
same here

**Comment by jihanyang** [comment]
Actually, I also meet this problem occasionally on various CUDA version, pytorch version. We just contine the training process. Since this problem is hard to reproduce, it is time-consuming for us to locate this actual problem.
