### ISSUE TITLE
How to use path with \

### ISSUE THREAD

**Issue by oldtime-tai** [open-mmlab/OpenPCDet#423]
I have a little question.

When  I read the demo code, I find you use / to represent the directory path, such as 

                   output_dir = cfg.ROOT_DIR / 'output' / cfg.EXP_GROUP_PATH / cfg.TAG / args.extra_tag

 

I suppose this is a good programming method， but i fail with this error, such as

             output_dir = 'checkpoint' / 'test_1'
            TypeError: unsupported operand type(s) for /: 'str' and 'str'

Can you tell me why?

Tanks

**Comment by wangyakunn** [comment]
I meet the same question.

**Comment by wangyakunn** [comment]
Hi，I met the same question, could you tell me how to solve?

thanks
