### ISSUE TITLE
TypeError: 'PosixPath' object is not subscriptable while setting up Waymo Open Dataset

### ISSUE THREAD

**Issue by jskhu** [open-mmlab/OpenPCDet#428]
I was attempting to run the command to setup Waymo Open Dataset but I ran into the error:
```
TypeError: 'PosixPath' object is not subscriptable
```

Looks like it's a simple fix of changing the line:

https://github.com/open-mmlab/OpenPCDet/blob/a7cf5368d9cbc3969b4613c9e61ba4dcaf217517/pcdet/datasets/waymo/waymo_dataset.py#L73

To

```
sequence_file = Path(str(sequence_file)[:-9] + '_with_camera_labels.tfrecord')
```

Seems like the change from `path` to `pathlib` made it so the `Path` object is not subscriptable anymore.

**Comment by jihanyang** [comment]
Thank you! I notice this bug recently and fix it. We haven't tested on this fragment of code before. Sorry for late reply.
