### ISSUE TITLE
Unable to start training of PointPillars again

### ISSUE THREAD

**Issue by GYE19970220** [open-mmlab/OpenPCDet#429]
I have successfully trained pointpillars with multi gpu on kitti yesterday，When I try to train it again，the training is unable to start，it is very strange，its log is as follows, nothing else.My command is 
`python -m torch.distributed.launch --nproc_per_node=8 train.py --launcher pytorch --cfg_file cfgs/kitti_models/pointpillar.yaml --extra_tag test`
A strange phenomenon is that some PID disappear automatically on some GPU
![image](https://user-images.githubusercontent.com/42958175/103992661-6769d000-51cf-11eb-854d-64a4e365a4b9.png)

When I cancel the training with Ctrl+c and kill all PID，it reported 
![image](https://user-images.githubusercontent.com/42958175/103993299-5a011580-51d0-11eb-8b98-0d92fd9199a7.png)

When i try to others cfgs like second.yaml ,it reported 
`semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown`
I am very confused，Could you please help me?

**Comment by a43992899** [comment]
Hi, I encounter the same issue, how did you fix it? @GYE19970220
