### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by K-Young96** [open-mmlab/OpenPCDet#435]
when i run :
result_str, result_dict = dataset.evaluation(
        det_annos, class_names,
        eval_metric=cfg.MODEL.POST_PROCESSING.EVAL_METRIC,
        output_path=final_output_dir
    )

error : Segmentation fault (core dumped)

can you help me?

**Comment by wyddmw** [comment]
> when i run :
> result_str, result_dict = dataset.evaluation(
> det_annos, class_names,
> eval_metric=cfg.MODEL.POST_PROCESSING.EVAL_METRIC,
> output_path=final_output_dir
> )
> 
> error : Segmentation fault (core dumped)
> 
> can you help me?

have you solved this problem?

**Comment by SmBito** [comment]
I have the same problem, any help?

**Comment by yang-jiaye** [comment]
Same problem

**Comment by Luca23C** [comment]
@yang-jiaye Hi, did you solve this problem?
