### ISSUE TITLE
How to master OpenPCDet?

### ISSUE THREAD

**Issue by MengAaron** [open-mmlab/OpenPCDet#446]
Hi,
I am a green hand with little knowledge about this codebase (also new for others). And I want to reproduce a new model base on OpenPCDet. How can I better know about that? Need some advice.
Appreciate it!

**Comment by jihanyang** [comment]
I think you could set breakpoints in the model constructing and forwarding functions to follow how openpcdet build models and feedforward features to different components.

**Comment by MengAaron** [comment]
I think it is important to know the data flow of the OpenPCDet.
