### ISSUE TITLE
Is the released models trained on the train split or the entire training set for the KITTI dataset?

### ISSUE THREAD

**Issue by f-sky** [open-mmlab/OpenPCDet#447]
Hi, I have a question about pretrained model.
Are the released models trained on the train split or the entire training set for the KITTI dataset?
When you submit results to the KITTI website, are you using the model trained on the train split or the entire training set?
Can you provide the model trained on the entire training set for PV-RCNN?
Thanks a lot!

**Comment by jihanyang** [comment]
Just on the train split as our Imagesets.
