### ISSUE TITLE
How to start multiple GPUs and multiple machines training?

### ISSUE THREAD

**Issue by kagecom** [open-mmlab/OpenPCDet#449]
I have sucessfully start multple GPUs training in a single machine to train PVRCNN, but I don't know how to start multple machine distributed learning.

Suppose I have two machines, each with 8 GPUs, with ip address 192.168.0.1, 192.168.0.2,

how to start distributed learning with multiple GPUs and multiple machines?

**Comment by jihanyang** [comment]
Hello, we use slurm to start multiple machine training.
