### ISSUE TITLE
About results on validation in the paper

### ISSUE THREAD

**Issue by Ultra11nstinct** [open-mmlab/OpenPCDet#450]
Hi @sshaoshuai  @jihanyang 
Thanks again for your great work.
I just wanna know the ablation study in PV-RCNN paper is trained for car，cyclist，pedestrian but only reported car results， or trained only for car class？

Wish every success in your work.
Looking forward to your reply.

**Comment by jihanyang** [comment]
Hello,
Since the result in car is more stable, we only accomplish the ablation study on car.

**Comment by Ultra11nstinct** [comment]
> Hello,
> 
> Since the result in car is more stable, we only accomplish the ablation study on car.


Thanks for your reply @jihanyang 
so,it means that in ablation study only cars are trained.
There is another question, is the different class result(cars,pedestrians,cyclists) in the partA2 paper obtained by using one model,or multi models?
