### ISSUE TITLE
how does add_sampled_boxes_to_scene work?

### ISSUE THREAD

**Issue by nsirons** [open-mmlab/OpenPCDet#451]
Can someone explain the main idea behind [add_sampled_boxes_to_scene](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/pcdet/datasets/augmentor/database_sampler.py#L118) and how does it work?

Especially, I am curious about lines [150,151](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/pcdet/datasets/augmentor/database_sampler.py#L150) where `points` are modified by first removing points from enlarged gt_boxes and later `obj_points` are added to `points`. What is the reason for doing so? 

Moreover `obj_points` have different times, compared to `times_sweeps` obtained from [get_sweep](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/pcdet/datasets/nuscenes/nuscenes_dataset.py#L76). How can I now know which point belongs to which sweep?

If I want to add radar to the network, do I need to perform the same operation with radar points?

There are not that many comments so I found it difficult to understand the code. I would appreciate any help :)

**Comment by jihanyang** [comment]
We remove the points (`large_sampled_gt_boxes`) that around the position we want to put the gt samples in the origin scene. After that, we add the points of gt samples (`obj_points`)  to the scene (`points`).
