### ISSUE TITLE
PV-RCNN-v2

### ISSUE THREAD

**Issue by soldierofhell** [open-mmlab/OpenPCDet#457]
Hi @sshaoshuai,
Are there any plans to upgrade PV-RCNN to v2? (SPC sampling & VectorPool aggregation)
Regards,

**Comment by sshaoshuai** [comment]
Yes, we will support PV-RCNN-v2 to OpenPCDet in the near future, yet it may still need take some time.

**Comment by soldierofhell** [comment]
Great! :)

**Comment by oshrout** [comment]
Hey @sshaoshuai,
Is there any new regarding PV-RCNN++ release date?
Thanks

**Comment by zhanggang001** [comment]
Hey @sshaoshuai, when will you release the code for PV-RCNN++? Thanks !!!

**Comment by sshaoshuai** [comment]
I just come back to prepare for some updates of OpenPCDet. After that I will find time to sort out the codes of PV-RCNN++ for code release.

**Comment by sshaoshuai** [comment]
Hi all, 

the codes of PV-RCNN++ has been released.
