### ISSUE TITLE
how to modify the network structrure

### ISSUE THREAD

**Issue by zheyuanWang** [open-mmlab/OpenPCDet#461]
Hi, 
I am new to this project, the user-guide is very helpful.

It seems that the model type is configured in second.yaml (I am using SECOND) with 
```
MODEL:
    NAME: SECONDNet
```

I am wondering how to further modify the network.

I want to re-construct the combination of backbones. It would be cool if I could define the input and output of each backbone, so that any reasonable network structure could be built with the given backbones. 

Could you please show me where to find/ config them, thanks.

**Comment by triasamo1** [comment]
Hey man,  In this directory `Openpcdet/pcdet/models/` you can find all the "modules" that all the network architectures use. I don't know if you mean this?!
