### ISSUE TITLE
WARNING:root:NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by 3bobo** [open-mmlab/OpenPCDet#462]
It seems an error during training:
`WARNING:root:NaN or Inf found in input tensor.`
my platform:  Ubuntu-18.04, torch-1.6, spconv-1.2, cuda-10.2.
Could anyone met and solved it?

**Comment by lfxx** [comment]
Same problems here

**Comment by pigtigger** [comment]
same problems with pcdet 0.5

**Comment by OuYaozhong** [comment]
Same problem with pcdet v0.5.2
