### ISSUE TITLE
How to use TensorBoard during training?

### ISSUE THREAD

**Issue by RolandoAvides** [open-mmlab/OpenPCDet#463]
Hi there!

How to use TensorBoard during training?

Thanks in advance!

**Comment by Suri12990** [comment]
Hey @RolandoAvides 

Go to this folder   Openpcdet_Env/OpenPCDet/output/kitti_models/pv_rcnn/default and typer tensorboard --logdir tensorboard

Hope it works!

**Comment by RolandoAvides** [comment]
Hi! Yes, it worked! I was missing TensorFlow in my environment.

Thanks!

**Comment by yaxi333** [comment]
Hi, 

I want to ask have you ever used the tensorboard to save and visualize the details of layers, weights, and biases of the model? If so, could you please give me some hints because I have stuck in how to visualize the model by tensorboard.

Thanks in advance!

**Comment by MartinHahner** [comment]
@yaxi333: https://wandb.ai is better suited for that :wink:

**Comment by swaggywilliam** [comment]
> @yaxi333: https://wandb.ai is better suited for that 😉

Could you please provide a tutorial on how to integrate W&B into OpenPCdet? Thank you!
