### ISSUE TITLE
Some errors about test

### ISSUE THREAD

**Issue by Ben940315** [open-mmlab/OpenPCDet#466]
When I run test.py, some errors like these:
OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 69, in boxes_iou3d_gpu
    max_of_min = torch.max(boxes_a_height_min, boxes_b_height_min)
RuntimeError: CUDA error: invalid device function

So how to solve it?

**Comment by RolandoAvides** [comment]
Try to reinstall OpenPCDet and pytorch.

**Comment by bluestyle97** [comment]
Maybe you compile the CUDA extensions and run test.py on different types of GPUs.
