### ISSUE TITLE
How do I use OpenPCDet to detect continuous multi-frame point cloud

### ISSUE THREAD

**Issue by 123378** [open-mmlab/OpenPCDet#470]
The demo.py detects a single frame point cloud, how do I use it for continuous point cloud detection?    How should I write it if I want to use it in ROS?

**Comment by starrynightok** [comment]
I have the same doubt.

**Comment by KangChou** [comment]
![image](https://user-images.githubusercontent.com/36963108/123262681-bd86c180-d52a-11eb-928c-4395fc0446a6.png)

**Comment by HuangVictorAuto** [comment]
@123378 , @starrynightok , I have the same need here, have you found the solution to play continuous frame?

**Comment by applededipan** [comment]
> 

me too !
