### ISSUE TITLE
Difference between waymo 1.0 and 1.2 

### ISSUE THREAD

**Issue by zxduan90** [open-mmlab/OpenPCDet#471]
As far as I known, there is not "num_gts_in_box" in waymo1.0. If I calculate it and put it into the info pkl and train the data of waymo 1.0. Can I get the same result as I train waymo 1.2?

**Comment by jihanyang** [comment]
Waymo 1.2 also add or remove some frames in some sequence. The number of training frames and validation frames is also different between v1.0 and v1.2.

**Comment by zxduan90** [comment]
OK, I get it. Thanks very much.

**Comment by zxduan90** [comment]
> Waymo 1.2 also add or remove some frames in some sequence. The number of training frames and validation frames is also different between v1.0 and v1.2.

OK, I get it. Thanks very much.
