### ISSUE TITLE
运行kitti_dataset.py出现奇怪错误

### ISSUE THREAD

**Issue by XiaXingLuo** [open-mmlab/OpenPCDet#472]
运行python kitti_dataset.py create_kitti_infos，出如下错误
Traceback (most recent call last):
  File "kitti_dataset.py", line 8, in <module>
    from ...ops.roiaware_pool3d import roiaware_pool3d_utils
ValueError: attempted relative import beyond top-level package.
百度说是解释器无法把对应文件当作包，需要__init.py__文件，包括其他错误，都试了无法解决。

**Comment by ChennolongerCai** [comment]
请问您是怎么解决的？我也遇到了这个问题
