### ISSUE TITLE
change the voxel size, I can train with the new config

### ISSUE THREAD

**Issue by twn29004** [open-mmlab/OpenPCDet#488]
I just change the voxel size form [0.05,0.05,0.1] to [0.025,0.025,0.05], and run the train.py, then I get the problem like this.
![image](https://user-images.githubusercontent.com/61139022/113700652-af828b00-9709-11eb-8025-f5b92c85877a.png)
Anyone can help me. plz

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/253#issuecomment-677473408

**Comment by twn29004** [comment]
thank you very much
