### ISSUE TITLE
Questions about data augmentation for Waymo dataset

### ISSUE THREAD

**Issue by SUZhaoyu** [open-mmlab/OpenPCDet#489]
Hi, 

May I know how did you apply data augmentation for the Waymo Open Dataset (specifically, the "paste" of new objects)? Since the ground surface is not provided in the original Waymo dataset, how did you paste the new items onto the point cloud? Thank you. 

Regards,
Tony

**Comment by jihanyang** [comment]
We just don't use ground surface information in waymo.

**Comment by SUZhaoyu** [comment]
Alright, noted with thanks.
