### ISSUE TITLE
.bin  display 

### ISSUE THREAD

**Issue by doubelejjyy** [open-mmlab/OpenPCDet#492]
Why is the. Bin file incomplete when mayavi is displayed(the .bin was predicted)
predicted 
![image](https://user-images.githubusercontent.com/31815205/114015381-35ced680-989c-11eb-883c-49595dc03ff6.png)
original
![image](https://user-images.githubusercontent.com/31815205/114015430-42532f00-989c-11eb-8ff5-9404f0f7b701.png)

**Comment by doubelejjyy** [comment]
run quick demo with PV-RCNN in kitti

**Comment by thptai** [comment]
FOV_POINTS_ONLY: True (int kitti_dataset.yaml)

It is the config of the Kitti dataset, it only train with the FOV of the front camera.

**Comment by doubelejjyy** [comment]
> FOV_POINTS_ONLY: True (in kitti_dataset.yaml)
> 
> It is the config of the Kitti dataset, it only train with the FOV of the front camera.

I'm running a prediction program. In the. bin file, the pretrained model is used to predict, but the whole. bin file cannot be displayed completely.

**Comment by jihanyang** [comment]
Check the point cloud range that you set.

**Comment by doubelejjyy** [comment]
> Check the point cloud range that you set.

I didn't set it. I ran quick demo  with PV-RCNN in kitti

**Comment by jihanyang** [comment]
The demo.py use second.yaml https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/tools/demo.py#L58. The point cloud range have been set in the cfg.
