### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by xfbs** [open-mmlab/OpenPCDet#494]
Just in case anyone needs this, @0xdh and I created a docker container with OpenPCDet. You can get it by running

    docker pull xfbs/openpcdet

The source files for it are available at [xfbs/openpcdet](https://github.com/xfbs/openpcdet).

Cheers!

**Comment by MartinHahner** [comment]
Nice, but your link [xfbs/openpcdet](https://github.com/xfbs/openpcdet) is not reachable.
![image](https://user-images.githubusercontent.com/14181188/114184393-0fb14100-9945-11eb-943b-df4866c08f65.png)

Maybe you need to change your repository permissions.

**Comment by xfbs** [comment]
Oops, my bad, the link should be [xfbs/docker-openpcdet](https://github.com/xfbs/docker-openpcdet).
