### ISSUE TITLE
【Spatial shape】 setting in VoxelBackBone8x class

### ISSUE THREAD

**Issue by MuMuJun97** [open-mmlab/OpenPCDet#502]
Hello, @sshaoshuai , Sorry to disturb you.  
I found that **the spatial shape** is set as shown below: 
```python
class VoxelBackBone8x(nn.Module):
    def __init__(self, model_cfg, input_channels, grid_size, **kwargs):
        super().__init__()
        self.model_cfg = model_cfg
        ...
       
        self.sparse_shape = grid_size[::-1] + [1, 0, 0]  ## Question about this line 
```
**Why should the spatial shape add 1 to the z-axis of the grid size?**

Thanks !

**Comment by MengAaron** [comment]
I have the same question!

**Comment by Angericky** [comment]
I also have this doubt.

**Comment by Angericky** [comment]
I'm also in doubt about the additional 1 channel in z axis.

**Comment by DeclK** [comment]
Same question here...My best guess is that 41 is a suitable number for for convolution operation of kernel=3, stride=2, padding=1
When use original grid size 40, the last line won't be convolved under the condition of kernel=3, stride=2, padding=1😥

**Comment by Eddiesyn** [comment]
Same question here.
