### ISSUE TITLE
Question about the KITTI train/val split

### ISSUE THREAD

**Issue by SUZhaoyu** [open-mmlab/OpenPCDet#505]
Hi, thanks for the great work! I'd want to know the models you provide in the model zoo are trained only with the _train_ split (3712 samples) of KITTI, or the 80% _train + val_ split of KITTI (5985 samples)? Thanks for the reply in advance.

**Comment by jihanyang** [comment]
Yes

**Comment by SUZhaoyu** [comment]
That means trained with 3712 samples right?

**Comment by jwma0725** [comment]
Hi, I also meet the same the problem. How should I modify the configuration file-kitti_dataset.yaml?
![1641539690(1)](https://user-images.githubusercontent.com/38242572/148507286-597ca1ad-ac73-42ed-81d5-c724e1100d56.jpg)

**Comment by MartinHahner** [comment]
You need to create your own custom ImageSet lists.
The original ones are in here: 
https://github.com/open-mmlab/OpenPCDet/tree/master/data/kitti/ImageSets

Then you need to create new pkl files and use them in your yaml config file.
https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#kitti-dataset

**Comment by Petros626** [comment]
@SUZhaoyu @jwma0725 When you take a look at the three files at ImageSets, you can see the numbers of entries and in the `kitti_dataset.yaml` there is only train and val used for the training.
