### ISSUE TITLE
Problem with Multi-GPUs training

### ISSUE THREAD

**Issue by thptai** [open-mmlab/OpenPCDet#509]
Hi, thanks for your amazing repo.

I am successfully training PV_RCNN with Waymo dataset on single GPU.
However, when I tried to train with multi-GPUs, my RAM keeps increasing and freeze the whole system.
I have tried to reduce batch_size and even try to increase the SAMPLED_INTERVAL to reduce the number of samples used.
When I train the network with single GPU, batch_size=2, the RAM consuming is ~30GB total.
So theoretically, with 128GB RAM, at least I can train PV_RCNN using 3 GPUs with batch_size=2. 
But I can not even train with 2 GPUs.

Do you have any suggestion on how I can fix the problem ?

**Comment by zyl1336110861** [comment]
I have the same problem.
