### ISSUE TITLE
The difference between KITTI coordinate and Nuscenes coordinate

### ISSUE THREAD

**Issue by 3bobo** [open-mmlab/OpenPCDet#510]
I noticed that in KITTI coordinate, X points forward， Y points left and Z points up. However, in Nuscenes coordinate, it seemed that X points right, Y points forward and Z points up. Did I miss something?

**Comment by OrangeSodahub** [comment]
@3bobo You're right, any problems you have?

**Comment by Petros626** [comment]
@OrangeSodahub can you tell in which coordinate frame the nuscenes annotations are in default?
