### ISSUE TITLE
Understand Reference System of predicted result

### ISSUE THREAD

**Issue by GabrieleGalimberti-GaleSelector** [open-mmlab/OpenPCDet#514]
Hi,
I don't understand which is the origin of the reference system of this results using PartA2.

[[28.49480438 25.91353416  1.31373107  4.102736    1.69495928  1.55347359
   3.03687525      ]
 [33.73332596 24.45496941  1.0646584   3.41844225  1.61226952  1.61857033
   6.78078461    ]

I try to take minimum value of x y z in the pointcloud and subtract from x y z of the results but I make a mistake.

If I don't subtract minimum value of x y z in the pointcloud I obtain this result.  (car detected is identified by bounding box red)

<img width="798" alt="Schermata 2021-04-21 alle 11 38 03" src="https://user-images.githubusercontent.com/49124856/115533146-bf1bdb00-a296-11eb-9a75-11c105b858d8.png">

If I subtract minimum value of x y z in the pointcloud I obtain this result. (car detected is identified by bounding box red). In this case I tilt the image to show cars and bounding boxes.

<img width="805" alt="Schermata 2021-04-21 alle 11 40 00" src="https://user-images.githubusercontent.com/49124856/115533181-c7741600-a296-11eb-9ba1-4a4980320730.png">

Furthermore, I don't understand if heading result (7th value in each detected object) is a rotation of bounding box on y axis or z axis and respect which center .

**Comment by thinhngo-x** [comment]
About the heading angle, as far as I understand from [this](https://github.com/open-mmlab/OpenPCDet/blob/e4d2b75bc0e48399177a1823ad6f4ff8179cc835/pcdet/utils/common_utils.py#L34), a heading angle is the angle from +X to +Y axis.
