### ISSUE TITLE
How to test all points in one frame point cloud?

### ISSUE THREAD

**Issue by Yupeng-mango** [open-mmlab/OpenPCDet#516]
I have used the second model to test kitti data, however there is a problem I can't solve.
Although I changed the FOV_POINTS_ONLY to False in kitti_dataset.yaml, and I recreated the kitti data files, after I run test.py to predict the result, there is only the detection results of the front field of view.
I want to get test results for all fields of view.
Could you please give me some help?
Thanks!

**Comment by jihanyang** [comment]
Please change the `POINT_CLOUD_RANGE`

**Comment by Yupeng-mango** [comment]
> Please change the `POINT_CLOUD_RANGE`

I make it! Thank you~

**Comment by feigezuishuai123** [comment]
I want to ask what does the six values in POINT_CLOUD_RANGE mean?

**Comment by jihanyang** [comment]
[min_x, min_y, min_z, max_x, max_y, max_z]
