### ISSUE TITLE
How to evaluate the performance of the model according to the segmentation distance on Kitti?

### ISSUE THREAD

**Issue by jlqzzz** [open-mmlab/OpenPCDet#518]
How to evaluate the performance of the model according to the segmentation distance on Kitti? Such as 0-30m，30-50，50-70.4.
Where should I change the evaluation code to control the evaluation metric ?

**Comment by MartinHahner** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/e4d2b75bc0e48399177a1823ad6f4ff8179cc835/tools/eval_utils/eval_utils.py#L22

https://github.com/open-mmlab/OpenPCDet/blob/e4d2b75bc0e48399177a1823ad6f4ff8179cc835/pcdet/datasets/kitti/kitti_dataset.py#L322

This evaluation would indeed be a great extension to this repository.
