### ISSUE TITLE
"dataloader_iter = iter(train_loader)" is too slow

### ISSUE THREAD

**Issue by ca3907** [open-mmlab/OpenPCDet#520]
Hi,
I am currently training on multiple GPUs.

During training, I noticed that there was an excessive time delay between the epochs.

I seem to be spending more than 30 seconds in this phrase.
`dataloader_iter = iter(train_loader)`

Is there any solution?

**Comment by MartinHahner** [comment]
I also observe this, I'm curious if there is a "solution", too.

**Comment by ca3907** [comment]
> I also observe this, I'm curious if there is a "solution", too.

There was no problem When I using nn.DataParallel, not DistributedDataParallel
So I thought there was a solution.
Thanks for your answer!

**Comment by Pyten** [comment]
I had met the same problem. Even worse, when I expand my dataset size, training stacks using DistributedDataParallel with 4 gpus. Only set workers = 0 the ddp can proceed, but the speed can't overtake training with one gpu without DDP. If anyone has some suggestions, please let me know.

**Comment by chenrui17** [comment]
I had met the same problem when i use ddp with multigpu trainning

**Comment by hanin97** [comment]
I had met the same problem, please reopen.

**Comment by Dis-Able** [comment]
I even had met the same problem, reopen plz!!!
