### ISSUE TITLE
Customized dataset

### ISSUE THREAD

**Issue by beedrill** [open-mmlab/OpenPCDet#528]
Is there a tutorial that one can follow to make a customized dataset? Thing like how to organize the data, in terms of points and labels and how to apply it?

**Comment by paland3** [comment]
You can simulate KITTI dataset, i.e. place your point cloud files, images, labels in the same structure, and make your own dataset config based on kitti_dataset.yaml.

**Comment by MartinHahner** [comment]
more info is given here https://github.com/open-mmlab/OpenPCDet/issues/198

**Comment by OrangeSodahub** [comment]
Hello, you can refer to my successful example using kitti format custom dataset. README describes how to label, train, inference it including transformation of coordinates. It may solve your problems!
https://github.com/OrangeSodahub/CRLFnet#lid-cam-fusion
https://github.com/OrangeSodahub/CRLFnet/blob/master/src/site_model/src/LidCamFusion/OpenPCDet/pcdet/datasets/custom/README.md

**Comment by OrangeSodahub** [comment]
You can also refer to this pull requrest: #1032
