### ISSUE TITLE
About road plane

### ISSUE THREAD

**Issue by ReunionJ** [open-mmlab/OpenPCDet#531]
Excuse me, what do the four data in the 'road plane' file represent? It doesn't look like a、b、c、d in the formula ax+by+cz+d=0. I want to know how to get the formula of pavement according to the data in road plane. Thank you very much!
![image](https://user-images.githubusercontent.com/61350136/117267453-dbb83580-ae88-11eb-8f6d-504d1d211330.png)
![image](https://user-images.githubusercontent.com/61350136/117267367-c80ccf00-ae88-11eb-96f4-a0ae96b3e2ab.png)
![image](https://user-images.githubusercontent.com/61350136/117267402-cd6a1980-ae88-11eb-8054-f90ea798eb18.png)

**Comment by Kemo-Huang** [comment]
Further, I also want to know how to obtain the road plane data for other benchmarks on KITTI (e.g. tracking). Thanks!

**Comment by a954217436** [comment]
Same questions... Do you get the answer?

**Comment by BAI-Yeqi** [comment]
@ReunionJ Hi, may I know if you have figured this out? Thanks.
