### ISSUE TITLE
How to train for BEV with only 2D boxes? 

### ISSUE THREAD

**Issue by wahmed991** [open-mmlab/OpenPCDet#536]
Hi, if I only have 2D boxes as groundtruth for my custom dataset (I ignore the height dimension), how can I train with your code? I see that on the KITTI BEV Leaderboard, you guys have reported good APs but I am wondering how you train for only 2D boxes. Please help.

**Comment by paland3** [comment]
Hi, they do not train seperately for only BEV, that is just a different metric of the 3D object detection.
