### ISSUE TITLE
Where do I get KITTI depth folder to train CaDDN?

### ISSUE THREAD

**Issue by MartinHahner** [open-mmlab/OpenPCDet#543]
After applying the fixes mentioned in https://github.com/open-mmlab/OpenPCDet/pull/542 I can still not train CaDDN 
because I am missing the `depth_2` folder of KITTI. 

Where can I get this data?

**Comment by sshaoshuai** [comment]
Here is the instruction for preparing `depth_2` data: https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#dataset-preparation

**Comment by MartinHahner** [comment]
> Here is the instruction for preparing `depth_2` data: https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#dataset-preparation

@sshaoshuai  Thanks, I did not see that!
