### ISSUE TITLE
Kitti - Evaluation

### ISSUE THREAD

**Issue by RolandoAvides** [open-mmlab/OpenPCDet#546]
Hi!

Regarding the kitti evaluation, where can I check the tensorboard related to the evaluation with an IoU of 0.5 (Cars) and 0.25 (Ped and Cycl.)

Thanks in advance!

**Comment by jihanyang** [comment]
We do not add these terms in tensorboard, you can add them by yourself.

**Comment by RolandoAvides** [comment]
Thanks! 

Do you have any idea on what .py file should I change?

Thanks in advance!

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/150b7ba0eee87e6994dd30d2ba16b9ba8f7e278e/tools/eval_utils/eval_utils.py#L116-L117

Add those terms into `result_dict` and `result_str` before udpate.
