### ISSUE TITLE
Rotation Angle 

### ISSUE THREAD

**Issue by zzmonlyyou** [open-mmlab/OpenPCDet#547]
Hi,

I have successfully implemented the repository and thank you for your contribution. I am now using the results for object detection [x, y, z, w, l, h, Rotation angle] to graph the bounding box in the bird-eye view. Right now, I simply rotate the bounding box around the center by the rotation angle in degree, but it is not the same as the demo (which presents the correct bbox).  Thank you for your help. 
![image](https://user-images.githubusercontent.com/84257669/119606493-b1d79c00-bdc0-11eb-919c-b6f60614a2d3.png)

**Comment by st235** [comment]
@zzmonlyyou any chance you were testing on `waymo`?

**Comment by Petros626** [comment]
@st235 @zzmonlyyou guys haha what's up? did you succed with your goals?
