### ISSUE TITLE
Make my own 3d dataset

### ISSUE THREAD

**Issue by nicholasguimaraes** [open-mmlab/OpenPCDet#56]
Hey sshaoshuai, I was looking for more information on how the KITTI 3d dataset was made.
Found good information regarding all of the parameters and data needed to train the network here;

https://github.com/yanii/kitti-pcl/blob/master/KITTI_README.TXT

http://www.cvlibs.net/publications/Geiger2013IJRR.pdf

I wonder if you know of any repository that could have the codes to generate the parameters to the calibration file.

Regarding annotations (bounding box) do I need to annotate both the 2d rgb img and the 3d point cloud?

**Comment by sshaoshuai** [comment]
Sorry, I could not help much for these questions. Maybe you could find more related materials under the repo of other 3D detection datasets like NuScenes and Waymo.

**Comment by neverrop** [comment]
@nicholasguimaraes have you found any methods for this? It'll be so nice if you can share this.

**Comment by zzqjh** [comment]
hello i also want to use my own datasat .Do you have used your own dataset for the model? could you please give some suggestions for me ？
