### ISSUE TITLE
Different WORLD_ROT_ANGLE?

### ISSUE THREAD

**Issue by withinnoitatpmet** [open-mmlab/OpenPCDet#560]
Thank for your awesome project!

I have a question about data augmentation on different dataset.
I noticed that WORLD_ROT_ANGLE in  the two datasets are different. Could you please provide me any insight about the difference?

WORLD_ROT_ANGLE: [-0.78539816, 0.78539816] in kitti, WORLD_ROT_ANGLE: [-0.3925, 0.3925] in nuscene

https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/kitti_dataset.yaml#L41
https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/nuscenes_dataset.yaml#L51

**Comment by MartinHahner** [comment]
KITTI has only annotations in the camera field of view,
nuScenes has annotations in full 360°.

I think those values were empirically chosen to work best.
