### ISSUE TITLE
The problem when i use demo.py to visualize nuscenes 

### ISSUE THREAD

**Issue by czy-0326** [open-mmlab/OpenPCDet#563]

**Comment by czy-0326** [comment]
When I use demo.py to visualize the nuscenes dataset with the pretrained model(second multihead ),I load 10 sweeps,but the detection result is so terrible, there are many cars in red circles,but it can not be detected,while there are no cars in green bbox.
![E4F57577E5A7A029366BE352646C9399](https://user-images.githubusercontent.com/74098358/121796313-9686e080-cc4a-11eb-9081-9b2418f1d80f.jpg)

Can you help me deal with this problem.
Thankyou for your reply.

**Comment by MartinHahner** [comment]
Some of your axis seem off. KITTI has a different coordinate system compared to nuScenes.
I think [demo.py](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/demo.py) is only meant to work with KITTI, otherwise, you maybe have to adapt the script.

**Comment by LuizGuzzo** [comment]
what file did you use to play in demo.py? I've already tried some .bin files and they all have problems.
