### ISSUE TITLE
Building OpenPCDet gives "Could not find suitable distribution for [spconv]"

### ISSUE THREAD

**Issue by janine9vn** [open-mmlab/OpenPCDet#567]
I've cloned, built, and subsequently pip installed spconv. I've confirmed it's installed with `pip3 list` which shows:
```py
spconv                  1.2.1   
```

However, when running `python3 setup.py develop` for OpenPCDet I get the following:
```py
Processing dependencies for pcdet==0.3.0+26a1612
Searching for spconv>=1.2
Reading https://pypi.org/simple/spconv/
Couldn't find index page for 'spconv' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for spconv>=1.2
error: Could not find suitable distribution for Requirement.parse('spconv>=1.2')
```

I'm unsure what to do or how to get it to see that I do have spconv installed. 

### Other Details
This is on WSL2. I have the correct NVIDIA drivers and cudNN.

I am using CUDA 11.0

**Comment by MartinHahner** [comment]
What was the solution?
