### ISSUE TITLE
how to test the AP/APH of my own data and 3d-detection model?

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/OpenPCDet#568]
Hi,@open-mmlab team!
Thanks for your great work!
I want to ask if I could test the AP/APH with my own data (pointcloud)and 3d-detection model?
if not,what could i do to get this 2 value?
Looking forward to your reply, it helps me a lot !
Thanks again.

**Comment by MartinHahner** [comment]
see [here](https://github.com/waymo-research/waymo-open-dataset/blob/bbcd77fc503622a292f0928bfa455f190ca5946e/waymo_open_dataset/metrics/python/detection_metrics.py#L163)
