### ISSUE TITLE
demo.py error on jetson xavier

### ISSUE THREAD

**Issue by reddittoob** [open-mmlab/OpenPCDet#570]
Hi, I'm trying to run demo.py on nvidia jetson xavier board. 

I installed all packages and libraries well. 

However, when I run demo.py, I got an error like below.

2021-06-18 17:23:23.414 (  35.171s) [        7EB21010]vtkXOpenGLRenderWindow.:650    ERR| vtkXOpenGLRenderWindow (0x17b07610): Cannot create GLX context.  Aborting.

Anyone somebody know solution about this problem?

Additionally, I have one more question.

I don't want to show the result window. So, I added mlab.close(). However, the result window shows up and closes. I want never to show up the result window. 

Somebody have any ideas?

Thank you.

**Comment by jihanyang** [comment]
Just don't run `mlab.show(stop=True)` and the window will not show up.

**Comment by reddittoob** [comment]
I didn't run mlab.show(stop=True). Howerver, the window still show up like below image.
![Screenshot from 2021-06-21 08-54-35](https://user-images.githubusercontent.com/30588581/122692146-7371b780-d26e-11eb-80e5-8ab9ad038b82.png)

I don't know how to do it.

**Comment by SmBito** [comment]
@reddittoob Hello, I have the same problem, have you found a solution? Thanks
