### ISSUE TITLE
pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp:12:18: fatal error: cuda.h: No such file or directory compilation terminated. error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by KangChou** [open-mmlab/OpenPCDet#572]
![image](https://user-images.githubusercontent.com/36963108/123262699-c5466600-d52a-11eb-95ef-01ae7275f2b7.png)

**Comment by zhulf0804** [comment]
I solved the above problem by updating the content in `~/.bashrc`, then `source ~/.bashrc`.

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.1/lib64
export PATH=$PATH:/usr/local/cuda-10.1/bin
export CUDA_HOME=/usr/local/cuda-10.1

export C_INCLUDE_PATH=${CUDA_HOME}/include:${C_INCLUDE_PATH}
export CPATH=$CPATH:/usr/local/cuda/include
export LIBRARY_PATH=${CUDA_HOME}/lib64:$LIBRARY_PATH

```
The third one is `export CUDA_HOME=/usr/local/cuda-10.1`, instead of `export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-10.1`
