### ISSUE TITLE
How to get evalution result of each class?

### ISSUE THREAD

**Issue by yaxi333** [open-mmlab/OpenPCDet#574]
Hi 

I have noticed that the model zoo result which is shown on the website:
![image](https://user-images.githubusercontent.com/57478405/123428044-a812a580-d5c5-11eb-8fd9-4444639d8f21.png)
I want to ask how you get this Car@R11? Because it seems to be two AP results based on different thresholds 0.7 and 0.5 for moderate 3d detection task @R11? What I have got is as following:
Car AP@0.70, 0.70, 0.70:
bbox AP:94.7996, 88.9117, 87.8464
bev AP:89.7246, 86.8356, 83.5177
3d AP:86.4783, 76.2949, 72.4491
aos AP:94.75, 88.76, 87.63
Car AP@0.70, 0.50, 0.50:
bbox AP:94.7996, 88.9117, 87.8464
bev AP:94.9225, 89.3233, 88.8077
3d AP:94.8194, 89.2578, 88.6416
aos AP:94.75, 88.76, 87.63

Thanks in advance!

**Comment by jihanyang** [comment]
The results on IoU threshold = 0.7 are reported.

**Comment by yaxi333** [comment]
Thank you very much! Then what the threshold reported for Pedestrian and Cyclist?

**Comment by jihanyang** [comment]
both 0.5
