### ISSUE TITLE
 Where is it used IOU LOSS  in project PVRCNN ?

### ISSUE THREAD

**Issue by kyrie-H** [open-mmlab/OpenPCDet#576]
The paper mentionde it:In RCNN stage, use **_iou loss_** to train, but no representation of it was found.
can somebody give me a hand?
best wishes!

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/pcdet/models/roi_heads/target_assigner/proposal_target_layer.py#L44

**Comment by kyrie-H** [comment]
> https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/pcdet/models/roi_heads/target_assigner/proposal_target_layer.py#L44

Thaks a lot!
