### ISSUE TITLE
Why is the number of predicted bounding boxes so high?

### ISSUE THREAD

**Issue by dilaragokay** [open-mmlab/OpenPCDet#577]
Hi,

I'm using PVRCNN with a custom data loader for another subset of KITTI.

Things seem to work. However, when I check the number of predicted bounding boxes ('batch_box_preds'), I see that it's quite high -> 211200.

Any ideas why the number of boxes is so high at the very first epoch and why it is specifically 211200?

**Comment by jihanyang** [comment]
I guess 211200 is the number of anchors rather than predicted bounding boxes.

**Comment by dilaragokay** [comment]
Thanks @jihanyang!
