### ISSUE TITLE
How to set DEPTH_NORMALIZER in extended POINT_CLOUD_RANGE?

### ISSUE THREAD

**Issue by MartinHahner** [open-mmlab/OpenPCDet#580]
How should I set 

https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/tools/cfgs/kitti_models/pointrcnn.yaml#L70

if I set 
https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/tools/cfgs/dataset_configs/kitti_dataset.yaml#L4

to [0, -40, -3, **80**, 40, 1]?

**Comment by sshaoshuai** [comment]
It doesn't matter, ``DEPTH_NORMALIZER'' is just used to normalize depth to around [0, 1]. So a similar value with your max depth should be ok.
