### ISSUE TITLE
cannot download pretrained model

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/OpenPCDet#582]
hi @lindahua @sshaoshuai @hellock @MMLAB-CUHK 
thanks for your great work!
but I have no VPN to download the pre-trained models on drivegoogle website.
Could you offer other ways to download ?(I'm in china)
It means a lot to me .Looking forward to your reply.
Thanks very much.

**Comment by brankyy** [comment]
if you will,  you could leave an email address and the pretrained model you need, I can download it and send it to you :)

**Comment by jiaoluonanhai** [comment]
Could you send me a copy ? my email is 1054953459@qq.com. Thanks very much. @brankyy

**Comment by applededipan** [comment]
Could you please send me a copy ? I tried many times but still can not download! my email is 524888133@qq.com. Thank you very much!@brankyy

**Comment by Typolo** [comment]
@brankyy could please send me the pointpillar model (model-18m), my email is 3026462963@qq.com, thank you so much.

**Comment by 155cannon** [comment]
I also need  the pointpillar model (model-18m), thank you!@brankyy

**Comment by 155cannon** [comment]
I also need the pointpillar model (model-18m), thank you!@brankyy   my e-mail:155cannon@163.com
