### ISSUE TITLE
How can i train on multi-computers

### ISSUE THREAD

**Issue by czy-0326** [open-mmlab/OpenPCDet#585]
In readme ,there is a command 'sh scripts/slurm_train.sh ${PARTITION} ${JOB_NAME} ${NUM_GPUS} --cfg_file ${CONFIG_FILE}'  .What's the meaning of 'PARTITION' and 'JOB_NAME' ? How can I run this command?

**Comment by jihanyang** [comment]
This command only works for slurm. Do your servers use slurm?

**Comment by czy-0326** [comment]
No, I just have two desktop computer @jihanyang
