### ISSUE TITLE
Command to resume training from alst saved epoch

### ISSUE THREAD

**Issue by chowkamlee81** [open-mmlab/OpenPCDet#586]
Hi @MartinHahner @sshaoshuai 
My training needs to be resumed from previous checkpoints. 
Is there are any extra arguments needs to be passed for training?
Kindly help

**Comment by MartinHahner** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/tools/train.py#L29

**Comment by 441599828** [comment]
but it seems the learnig rate are set to start from the begaining instead of where the ckpt is

**Comment by yang-jiaye** [comment]
> but it seems the learnig rate are set to start from the begaining instead of where the ckpt is

same problem
