### ISSUE TITLE
point range and voxel size

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/OpenPCDet#587]
hi,@open-mmlab team
I custom and train my own data, but I got low recall and AP. None of them are more than 40 percent accurate.
I reanalyzed my own point cloud data and found that his XYZ coordinates exceeded the point cloud range in YAML, and many of my X coordinates were negative numbers.I would like to ask if the point cloud scope in YAML should be changed in this case to train again? or some other advice to help me sovle this problem? It means a lot to me .Looking forward to your reply! Thanks again!

**Comment by jihanyang** [comment]
Try to follow the dataset_cfg of waymo and nus https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/tools/cfgs/dataset_configs/waymo_dataset.yaml#L5
