### ISSUE TITLE
About the number of classes

### ISSUE THREAD

**Issue by Tu1016** [open-mmlab/OpenPCDet#588]
Does a model predicts three kinds of object simultaneously if I train it with CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']? Can I get higher performance when I train a model which only predicts Car?

**Comment by jihanyang** [comment]
Yes. You can try it, but I remember that their performance are similar.

**Comment by Tu1016** [comment]
> Yes. You can try it, but I remember that their performance are similar.

But I saw there is a difference in mmdetection3d.
