### ISSUE TITLE
The difference of Voxelrcnn

### ISSUE THREAD

**Issue by chenxyyy** [open-mmlab/OpenPCDet#589]
Hi @sshaoshuai .

I noticed that the voxelrcnn in Openpcdet is a little different from the official implementation.

1.  theBACKBONE_2D layer num. your implementation is [5, 5], but official implementation is [4, 4]
2.  the ROI_GRID_POOL. your implementation is FEATURES_SOURCE: ['x_conv2', 'x_conv3', 'x_conv4']. but official implementation is ['x_conv3', 'x_conv4']. 

I want to know why do you make these changes.

**Comment by jihanyang** [comment]
@djiajunustc

**Comment by djiajunustc** [comment]
Hi @chenxyyy,

The codes of Voxel R-CNN in this repository are also implemented by me.
Voxel R-CNN is not sensitive to these trivial differences.
Thanks for your attention.

Best Regards,
Jiajun Deng

**Comment by chenxyyy** [comment]
Okay, okay, I get it. Thank you very much.

While achieving better results, it is also very fast.
