### ISSUE TITLE
nvcc fatal : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by Nightmare-n** [open-mmlab/OpenPCDet#591]
PC environment:
  RTX 3070Ti
  Driver Version: 460.84
docker environment:
  pytorch: 1.7.0
  cuda: 11.0
  cudnn: 8
When compiling openpcdet, it occurs.

**Comment by HuangVictorAuto** [comment]
hey，I got the same problem， have you solved the issue？

**Comment by Nightmare-n** [comment]
> hey，I got the same problem， have you solved the issue？

export TORCH_CUDA_ARCH_LIST="8.0"

**Comment by HuangVictorAuto** [comment]
thanks, it worked.

**Comment by dylanqy** [comment]
> 
> 
> > hey，I got the same problem， have you solved the issue？
> 
> export TORCH_CUDA_ARCH_LIST="8.0"

thanks, it works!!!!
