### ISSUE TITLE
how can I get standard output format in demo.py?

### ISSUE THREAD

**Issue by preordinary** [open-mmlab/OpenPCDet#595]
Dear author. First, thanks for your outstanding work on OpenPCDet. It's very convenient and helpful, and I have run the demo.py successfully on my own dataset!

But now I have a confusion: when I run demo.py, would be the detection results saved in a file followed the format of the KITTI 3D Object Detection Challenge? If yes, where can I find this file?

Thanks a lot!

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/blob/26a16123cf820e29ed565f4ad53964c66f3ea030/tools/test.py#L39
