### ISSUE TITLE
Run test.py on Kitti test set, AP are all zero?

### ISSUE THREAD

**Issue by kyrie-H** [open-mmlab/OpenPCDet#597]
In project pv-rcnn,when I run test.py on Kitti test set,the values of recall are zero,I think I haven't configured it well.
![image](https://user-images.githubusercontent.com/56285242/126432496-5f337b05-7839-44e0-bc3d-b50d8f34dcab.png)
I only set the python file kitti_dataset.py like that:
![image](https://user-images.githubusercontent.com/56285242/126432742-cd8d95e0-3534-4e22-a57a-e4e51a011923.png)
How can I do the right test?
please give me a hand!best whishes!

**Comment by clytze0216** [comment]
@kyrie-H
 I met the same error.

**Comment by jihanyang** [comment]
This does not stands for errors.  Gts are not given in the test set, so these metrics can not be calculated. You need to submit to the kitti website to obtain results.

**Comment by kyrie-H** [comment]
> 这并不代表错误。测试集中没有给出 Gts，因此无法计算这些指标。您需要提交到kitti网站才能获得结果。

Thanks a lot！I think you are right,One more question，what should I submit？Are the well-trained pth and the eval result enough?

**Comment by jihanyang** [comment]
You should set --save_to_file when inference, and re-zip all those generated .txt files to another zip file.

**Comment by mqm-slice** [comment]
What should I do? I tried to use my own program to convert the results in the result.pkl file to the specified format. However, the result was 0 on the 3D index.
