### ISSUE TITLE
Questions about axes and origin of coordinates for training and testing data  

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/OpenPCDet#600]
hi @open-mmlab team
  I used my own data set for training and testing. My training data was based on radar coordinates, and my test data came from the same data set with good results.  But when I tested it with other data sets (different coordinate origins), the results were poor.  So I would like to ask whether the origin of the coordinates of the data used for testing should be strictly consistent with the origin of the coordinates of the training data?  Is there any way to increase the generality of the model so that it can be tested using data from different coordinates? 
  I am looking forward to your reply, which is very important to me. Thank you in advance!

**Comment by MartinHahner** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/599#issuecomment-886656943
