### ISSUE TITLE
about SECOND VFE part

### ISSUE THREAD

**Issue by yngseokkim** [open-mmlab/OpenPCDet#604]
VFE of SECOND is 'mean_vfe' which outputs mean vector of voxel points.
I think this is different from the explanation in paper 'SECOND: Sparsely Embedded Convolutional Detection'.
Could you tell me the reason please?

**Comment by EmiyaNing** [comment]
About this question, you could see the SECOND official repo. The latest version SECOND is using the mean_vfe. And it works very well...

**Comment by yngseokkim** [comment]
Thank you for your reply!
