### ISSUE TITLE
question about "calculate_iou_partly" function

### ISSUE THREAD

**Issue by AndyYu2021** [open-mmlab/OpenPCDet#608]
function declaration is like this:
def calculate_iou_partly(**gt_annos**, **dt_annos**, metric, num_parts=50):
however when invoke this function use 
rets = calculate_iou_partly(**dt_annos**, **gt_annos**, metric, num_parts)

**Comment by MartinHahner** [comment]
see https://github.com/open-mmlab/OpenPCDet/issues/139#issuecomment-655893164

**Comment by AndyYu2021** [comment]
Thank you
