### ISSUE TITLE
About the range of prediction's confidence

### ISSUE THREAD

**Issue by deepmeng** [open-mmlab/OpenPCDet#613]
What is the range of detection scores predicted by pointRCNN and PVRCNN? I noticed some work (https://github.com/xinshuoweng/AB3DMOT) used the detection results of pointRCNN and PVRCNN. But I feel the confidence values are strange, e.g., the confidence is negative or much larger than 1. In my impression, the confidence values in many methods are in a range of 0-1. How can I map these weird values to 0-1? @djiajunustc @sshaoshuai 

![image](https://user-images.githubusercontent.com/8176780/129242900-9a84af0f-2164-465e-b1ea-8f573f6e61b1.png)

**Comment by djiajunustc** [comment]
Hi @deepmeng ,

Have you fed the output of the FC layer into the Sigmoid function?
The output range of the Sigmoid function should be 0~1.

**Comment by deepmeng** [comment]
> Hi @deepmeng ,
> 
> Have you fed the output of the FC layer into the Sigmoid function?
> The output range of the Sigmoid function should be 0~1.

I have found the reason. Many thanks for your kind reply!

**Comment by amsvenkat** [comment]
HI @deepmeng 
What was the reason? Could you please let me know?

**Comment by deepmeng** [comment]
> Hi @deepmeng ,
> 
> Have you fed the output of the FC layer into the Sigmoid function? The output range of the Sigmoid function should be 0~1.

@amsvenkat 
You can try this solution.
