### ISSUE TITLE
Usage of the wrong variable 'dist' for loading parameters in train.py

### ISSUE THREAD

**Issue by Nopileos2** [open-mmlab/OpenPCDet#622]
While resuming a training I noticed the output on the command line saying that the weights I am loading in are loaded to the CPU. After further inspection I found that in train.py line 129 the _to_cpu parameter is assigned dist.

https://github.com/open-mmlab/OpenPCDet/blob/8e055f02df245b1f0675e874792dd708fb84c04b/tools/train.py#L126

This seems wrong and I would assume `dist_train `should be used here, since `dist` is just an alias for the imported package import `torch.distributed`. Using `dist `leads to always loading the weights to the CPU.

I created a pull request (https://github.com/open-mmlab/OpenPCDet/pull/621) changing this.

**Comment by jihanyang** [comment]
Merged
