### ISSUE TITLE
Version of waymo-open-dataset tools

### ISSUE THREAD

**Issue by tdzdog** [open-mmlab/OpenPCDet#626]
I used to use tf-2.4.0 and the corresponding waymo-open-dataset tools. However, I found the trained model get very low mAP (10% on Vehicle). I notice that it is recommended to modify the version in (https://github.com/open-mmlab/OpenPCDet/issues/370). I am confused why the version has so much influence on the model performance. Is there any efficient methods to check the processed data? It is time-consuming to train on waymo.

**Comment by jihanyang** [comment]
You can just visualize the point cloud with gts.

**Comment by dkoguciuk** [comment]
@tdzdog , the crucial part here is [THIS](https://github.com/open-mmlab/OpenPCDet/issues/370#issuecomment-736683423) comment. If you have different numbers you have to use a different tf / waymo libs version. This is what worked for me:

```
tensorflow-cpu                           2.1.0
tensorflow-gpu                           2.1.0
waymo-open-dataset-tf-2-1-0              1.2.0
```
