### ISSUE TITLE
Traning time on Waymo

### ISSUE THREAD

**Issue by tdzdog** [open-mmlab/OpenPCDet#627]
I am traning second on Waymo, with 5 3090 RTX and 6 sample on each gpu. However, I find it requires 20+ hours to train even with only 20% training set. Is such training speed normal? Or something is wrong?

**Comment by MartinHahner** [comment]
I think the time estimate you state sounds reasonable. The Waymo dataset is huge.

**Comment by tdzdog** [comment]
> > I am traning second on Waymo, with 5 3090 RTX and 6 sample on each gpu. However, I find it requires 20+ hours to train even with only 20% training set. Is such training speed normal? Or something is wrong?
> 
> How did you config the parameters of 'pin_memory' and 'num_workers' for your training in waymo dataset?

I use the default settings with 'pin_memory=True' and 'num_workers=8'

**Comment by deepmeng** [comment]
I think your configurations and the training speed are pretty good. These configurations make great use of the CPU, memory and GPUs. Besides the model and some intermediate processes, the amount of dataset is definitely a major factor.

**Comment by mqm-slice** [comment]
> I am traning second on Waymo, with 5 3090 RTX and 6 sample on each gpu. However, I find it requires 20+ hours to train even with only 20% training set. Is such training speed normal? Or something is wrong?

I have some problems when using the new 3090 server. Do you have docker images for 3090

**Comment by roylu307** [comment]
Hi @MartinHahner  @tdzdog @jihanyang,
How did you get 20% of the training set? is it a default setting?

I noticed the two places to specify the sample interval:
https://github.com/open-mmlab/OpenPCDet/blob/8e055f02df245b1f0675e874792dd708fb84c04b/pcdet/datasets/waymo/waymo_dataset.py#L327 and
https://github.com/open-mmlab/OpenPCDet/blob/8e055f02df245b1f0675e874792dd708fb84c04b/tools/cfgs/dataset_configs/waymo_dataset.yaml#L13

Which takes the priority? I also noticed the generated processed data has a tag 'sampled_1', does it mean it is the full training set? If so, do I need to regenerate the data for the 20% set or is there a way to select 20% from the processed data? Thanks in advance

**Comment by roylu307** [comment]
> How did you get 20% of the training set? is it a default setting?
> 
> I noticed the two places to specify the sample interval:
> 
> https://github.com/open-mmlab/OpenPCDet/blob/8e055f02df245b1f0675e874792dd708fb84c04b/pcdet/datasets/waymo/waymo_dataset.py#L327
> 
> and
> https://github.com/open-mmlab/OpenPCDet/blob/5861246c31c876f0e5a3e125086ed2b0be7bc9da/tools/cfgs/dataset_configs/waymo_dataset.yaml#L13
> 
> Which takes the priority? I also noticed the generated processed data has a tag 'sampled_1', does it mean it is the full training set? If so, do I need to regenerate the data for the 20% set or is there a way to select 20% from the processed data? Thanks in advance

The first setting controls the data preprocessing, the second setting in the yaml file controls the sampling for the actual training? 
If I set the sample interval in the yaml file to 1, it trains on all processed data if I am guessing correctly.

**Comment by jihanyang** [comment]
Yes.
