### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Fungungun** [open-mmlab/OpenPCDet#628]
Hi 

Just wondering if you have any plan to support multi modalities (e.g. point cloud + RGB) 3d detection in the future?

Thanks

**Comment by jihanyang** [comment]
Not yet.

**Comment by Fungungun** [comment]
Solved

**Comment by crypto-g245** [comment]
Hello, @Fungungun @jihanyang 
was this functionality added? Does it support - point cloud + RGB -  3d detection
