### ISSUE TITLE
Is it possible to place datasets in a different directory?

### ISSUE THREAD

**Issue by quan-dao** [open-mmlab/OpenPCDet#630]
Hello,

Thank you for sharing this great repo.

I am using your repo on a remote machine which has two disk partitions `home` and `data`. Their volume are 40GB and 1TB respectively, so datasets can't be placed in `home`. The `data` requires `sudo` to create new files or directories. I don't have the `sudo` password and I have to ask somebody to input it any time I want to make change to `data`. This makes it inconvenient for training. 

My question is: is it possible to place the dataset in `data` and OpenPCDet repo in `home`? 

Thank you in advance.

**Comment by jihanyang** [comment]
Sure. Try `ln -s`

**Comment by MartinHahner** [comment]
https://www.cyberciti.biz/faq/creating-soft-link-or-symbolic-link/
