### ISSUE TITLE
How to visualize detection result?

### ISSUE THREAD

**Issue by journey-wang** [open-mmlab/OpenPCDet#631]
Hello everyone,

Thanks very much for your effort!.

Now I am using the v0.1 branch, since there's no demo.py, I cannot directly visualize the detection result.
So is there anyone kindly provide such tools to visualize the result? with the input cfg and ckpt,  pcd file,.

Best regards.

**Comment by MartinHahner** [comment]
Maybe you can have a look at my [repo](https://github.com/MartinHahner/LiDAR_fog_sim) and [pointcloud_viewer.py](https://github.com/MartinHahner/LiDAR_fog_sim/blob/main/pointcloud_viewer.py) in particular.
There are [code snippets](https://github.com/MartinHahner/LiDAR_fog_sim/blob/ef7703754826723aca6504f27339063dd1735e11/pointcloud_viewer.py#L1282-L1346) on how to visualize the stored pickle files from disk after training.
