### ISSUE TITLE
num training epochs from model zoo

### ISSUE THREAD

**Issue by darrenjkt** [open-mmlab/OpenPCDet#632]
Hi, thanks for your repo. 

I got a question about the number of epochs used in the model zoo. When downloading the .pth files, it says "second_7862.pth". Whereas in the model cfgs for SECOND, it says EPOCHS: 80. 

These numbers (e.g. 7862) are tagged on most .pth files I've clicked onto which I initially thought that you trained SECOND for 7862 epochs (seeing as that's what appears in the evaluation test python logging). Is this number referring to the number of epochs or if not, are they just arbitrary?

**Comment by jihanyang** [comment]
The 7862 just refer to its AP@R11 on Car: 78.62.

**Comment by darrenjkt** [comment]
Thanks for clarifying that makes sense!
