### ISSUE TITLE
about the conversion between coordinate systems in kitti

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/OpenPCDet#637]
I don’t understand the calculation process of the coordinate transformation in kitti dataset.
may add more comment for calibration_kitti.py?
or share me with helpful web/tutorials to learn knowledge.
in addiation, about calcuation process of lidar2camera, do be calculation process in the func of <lidar_to_rect> different from the paper?
thank you!

**Comment by Petros626** [comment]
@zhjw0927 the web has a lot of visualization examples, sites etc. to fully understand the transformation from a camera frame to a lidar frame and vice versa.
