### ISSUE TITLE
Hardcoded LR in optim for Adam_onecycle ptimizer

### ISSUE THREAD

**Issue by aastha3** [open-mmlab/OpenPCDet#643]
The package internally resets the LR and doesn't use the LR given using the config because of this. 

 optimizer = OptimWrapper.create(
            optimizer_func, 3e-3, get_layer_groups(model), wd=optim_cfg.WEIGHT_DECAY, true_wd=True, bn_wd=True  #wtf, weight is hardcoded here! 
        )

**Comment by jihanyang** [comment]
Actually, that hardcoded LR will not influence the exact LR at all, so we tend to just place a magic number there rather than optim_cfg.LR
