### ISSUE TITLE
How to get the Waymo [0-30)[30-50)[50-inf) type results using OpenPCDet?

### ISSUE THREAD

**Issue by Cc-Hy** [open-mmlab/OpenPCDet#648]
I notice there is another metric in Waymo by splitting the distance into [0-30) [30-50) [50 - ∞）
How to get the results in this form using OpenPCDet?

**Comment by jihanyang** [comment]
Hello, you can subsample infos and predicted results according to range before evaluation.

**Comment by aalmuzairee** [comment]
Not sure if you're still looking for this, but one simple way would be to go to this line:
https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_eval.py#L89

and changing it from:

breakdown_generator_ids: OBJECT_TYPE

to

breakdown_generator_ids: RANGE


When you run test again, it should change the results to be split into distances.

**Comment by Cc-Hy** [comment]
> 
@aalmuzairee 
I tried and it worked, THANK YOU a lot!

**Comment by jwma0725** [comment]
@aalmuzairee @sshaoshuai  Hi, I have change OBHECT_TYPE to RANGE, but i do not get "Overall" and only get "[0,30]","[30,50]","[50,inf]". Could u tell me how to get? Thank u very much!!

**Comment by Feidashen1** [comment]
> Not sure if you're still looking for this, but one simple way would be to go to this line: https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_eval.py#L89
> 
> and changing it from:
> 
> breakdown_generator_ids: OBJECT_TYPE
> 
> to
> 
> breakdown_generator_ids: RANGE
> 
> When you run test again, it should change the results to be split into distances.

Similarly, How to get the KITTTI[0-20)[20-40)[40-inf) type results using OpenPCDet? 
Can you give me some suggestions?
Thank you!

**Comment by Harry710887048** [comment]
> > 不确定您是否仍在寻找这个，但一种简单的方法是转到这一行：https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_eval.py#L89
> > 并将其从以下位置更改：
> > breakdown_generator_ids：OBJECT_TYPE
> > 自
> > breakdown_generator_ids：范围
> > 再次运行测试时，它应该将结果更改为拆分的距离。
> 
> 同样，如何使用 OpenPCDet 获得 KITTTI[0-20）[20-40）[40-inf） 类型的结果？能给我一些建议吗？ 谢谢！

[https://github.com/waymo-research/waymo-open-dataset/tree/master/src/waymo_open_dataset/metrics/python
/config_util_py](https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/metrics/python/config_util_py.py)

<img width="528" height="198" alt="Image" src="https://github.com/user-attachments/assets/067cfc6b-29d1-4034-b8fe-cedf11589605" />
