### ISSUE TITLE
ImportError: /home/ruidong/workplace/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

### ISSUE THREAD

**Issue by DipDipPotatoChips** [open-mmlab/OpenPCDet#655]
ImportError: /home/ruidong/workplace/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

What‘s wrong？

**Comment by chapa17** [comment]
Hello @DipDipPotatoChips 
Did you find any solution to this error? I am also facing the same error.

**Comment by DipDipPotatoChips** [comment]
> Hello @DipDipPotatoChips Did you find any solution to this error? I am also facing the same error.

I browsed some websites and did some tests,I can't explain but  it seems that the problem is because of the version of python.
Example for me，it works with python3.6 but py3.7 py3.8 py3.9 can't. I don't know why

**Comment by pablobots** [comment]
Hi! Anyone find any solution to this error?

**Comment by sharifinjf** [comment]
hi
Does anyone find the solution to this error?

**Comment by DipDipPotatoChips** [comment]
> hi Does anyone find the solution to this error?

use python3.6

**Comment by Nirvana-fsociety** [comment]
It may be happenned when some components associate to C++ .so compile file was modified by yourself.
Try `python setup.py develop` again to update your .so file, so that making it works for me.

**Comment by rencongzhi** [comment]
Try `python setup.py develop`  didn't work for me.
But I figure out that somehow `python setup.py develop`  didn't replace the old .so files in `Openpcdet/pcdet/ops/`  with new ones(don't know if this only happents to me)

So I tried to replace those files by myself and solved this problem.

1. do `python setup.py develop`  again
2. Copy every `.so` file from `OpenPCDet/build/lib.linux-x86_64-3.7/pcdet/ops/` to `Openpcdet/pcdet/ops/` 
(don't change the relative path, and different python version might cause folder and file name a litttle bit different)

e.g. 
copy 
`/OpenPCDet/build/lib.linux-x86_64-3.7/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-37m-x86_64-linux-gnu.so`
to
`/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-37m-x86_64-linux-gnu.so`
