### ISSUE TITLE
Error when creating info files on custom datasets

### ISSUE THREAD

**Issue by curiousboy20** [open-mmlab/OpenPCDet#663]
Hi, I got the error when I want to generate info files on my custom dataset. Error message:

/home/yonas/anaconda3/envs/spconv12/lib/python3.8/runpy.py:127: RuntimeWarning: 'pcdet.datasets.kitti.kitti_dataset' found in sys.modules after import of package 'pcdet.datasets.kitti', but prior to execution of 'pcdet.datasets.kitti.kitti_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
---------------Start to generate data infos---------------
train sample_idx: 000000
train sample_idx: 000001
train sample_idx: 000002
train sample_idx: 000003
train sample_idx: 000004
train sample_idx: 000005
train sample_idx: 000006
train sample_idx: 000007
train sample_idx: 000008
train sample_idx: 000009
train sample_idx: 000010
train sample_idx: 000011
train sample_idx: 000012
train sample_idx: 000013
train sample_idx: 000014
train sample_idx: 000015
train sample_idx: 000016
train sample_idx: 000017
train sample_idx: 000018
train sample_idx: 000019
train sample_idx: 000020
train sample_idx: 000021
train sample_idx: 000022
train sample_idx: 000023
train sample_idx: 000024
train sample_idx: 000025
train sample_idx: 000026
train sample_idx: 000027
train sample_idx: 000028
train sample_idx: 000029
train sample_idx: 000030
train sample_idx: 000031
train sample_idx: 000032
train sample_idx: 000033
train sample_idx: 000034
train sample_idx: 000035
train sample_idx: 000036
train sample_idx: 000037
train sample_idx: 000038
train sample_idx: 000039
train sample_idx: 000040
train sample_idx: 000041
train sample_idx: 000042
train sample_idx: 000043
train sample_idx: 000044
train sample_idx: 000045
train sample_idx: 000046
train sample_idx: 000047
train sample_idx: 000048
train sample_idx: 000049
train sample_idx: 000050
train sample_idx: 000051
train sample_idx: 000052
train sample_idx: 000053
train sample_idx: 000054
train sample_idx: 000055
train sample_idx: 000056
train sample_idx: 000057
train sample_idx: 000058
train sample_idx: 000059
train sample_idx: 000060
train sample_idx: 000061
train sample_idx: 000062
train sample_idx: 000063
train sample_idx: 000064
train sample_idx: 000065
train sample_idx: 000066
train sample_idx: 000067
train sample_idx: 000068
train sample_idx: 000069
train sample_idx: 000070
train sample_idx: 000071
train sample_idx: 000072
train sample_idx: 000073
train sample_idx: 000074
train sample_idx: 000075
train sample_idx: 000076
train sample_idx: 000077
train sample_idx: 000078
train sample_idx: 000079
train sample_idx: 000080
train sample_idx: 000081
train sample_idx: 000082
train sample_idx: 000083
train sample_idx: 000084
train sample_idx: 000085
train sample_idx: 000086
train sample_idx: 000087
train sample_idx: 000088
train sample_idx: 000089
train sample_idx: 000090
train sample_idx: 000091
train sample_idx: 000092
train sample_idx: 000093
train sample_idx: 000094
train sample_idx: 000095
train sample_idx: 000096
train sample_idx: 000097
train sample_idx: 000098
train sample_idx: 000099
train sample_idx: 000100
train sample_idx: 000101
train sample_idx: 000102
train sample_idx: 000103
train sample_idx: 000104
train sample_idx: 000105
train sample_idx: 000106
train sample_idx: 000107
train sample_idx: 000108
train sample_idx: 000109
train sample_idx: 000110
train sample_idx: 000111
train sample_idx: 000112
train sample_idx: 000113
train sample_idx: 000114
train sample_idx: 000115
train sample_idx: 000116
train sample_idx: 000117
train sample_idx: 000118
train sample_idx: 000119
train sample_idx: 000120
train sample_idx: 000121
train sample_idx: 000122
train sample_idx: 000123
train sample_idx: 000124
train sample_idx: 000125
train sample_idx: 000126
train sample_idx: 000127
train sample_idx: 000128
train sample_idx: 000129
train sample_idx: 000130
train sample_idx: 000131
train sample_idx: 000132
train sample_idx: 000133
train sample_idx: 000134
train sample_idx: 000135
train sample_idx: 000136
train sample_idx: 000137
train sample_idx: 000138
train sample_idx: 000139
train sample_idx: 000140
train sample_idx: 000141
train sample_idx: 000142
train sample_idx: 000143
train sample_idx: 000144
train sample_idx: 000145
train sample_idx: 000146
train sample_idx: 000147
train sample_idx: 000148
train sample_idx: 000149
train sample_idx: 000150
train sample_idx: 000151
train sample_idx: 000152
train sample_idx: 000153
train sample_idx: 000154
train sample_idx: 000155
train sample_idx: 000156
train sample_idx: 000157
train sample_idx: 000158
train sample_idx: 000159
train sample_idx: 000160
train sample_idx: 000161
train sample_idx: 000162
train sample_idx: 000163
train sample_idx: 000164
train sample_idx: 000165
train sample_idx: 000166
train sample_idx: 000167
train sample_idx: 000168
train sample_idx: 000169
train sample_idx: 000170
train sample_idx: 000171
train sample_idx: 000172
train sample_idx: 000173
train sample_idx: 000174
train sample_idx: 000175
train sample_idx: 000176
train sample_idx: 000177
train sample_idx: 000178
train sample_idx: 000179
train sample_idx: 000180
train sample_idx: 000181
train sample_idx: 000182
train sample_idx: 000183
train sample_idx: 000184
train sample_idx: 000185
train sample_idx: 000186
train sample_idx: 000187
train sample_idx: 000188
train sample_idx: 000189
train sample_idx: 000190
train sample_idx: 000191
train sample_idx: 000192
train sample_idx: 000193
train sample_idx: 000194
train sample_idx: 000195
train sample_idx: 000196
train sample_idx: 000197
Traceback (most recent call last):
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yonas/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 478, in <module>
    create_kitti_infos(
  File "/home/yonas/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 442, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/home/yonas/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 222, in get_infos
    return list(infos)
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/yonas/anaconda3/envs/spconv12/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yonas/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 213, in process_single_scene
    flag = box_utils.in_hull(pts_fov[:, 0:3], corners_lidar[k])
  File "/home/yonas/OpenPCDet/pcdet/utils/box_utils.py", line 19, in in_hull
    hull = Delaunay(hull)
  File "qhull.pyx", line 1840, in scipy.spatial.qhull.Delaunay.__init__
  File "qhull.pyx", line 283, in scipy.spatial.qhull._Qhull.__init__
ValueError: Points cannot contain NaN

I have 198 files and I have edited the split data in ImageSet folder. All of the data has images, label, calib files, and velodyne.

Any help appreciated

**Comment by Petros626** [comment]
like it says here your data contain NaN values, maybe you can the pre-processing methods in OpenPCDet so filter the cloud.
