### ISSUE TITLE
Zero AP when train custom dataset

### ISSUE THREAD

**Issue by curiousboy20** [open-mmlab/OpenPCDet#668]
Hi, I trained my custom dataset consisting of 199 lidar, calib, and label files. I specifically train for Pedestrian detection. I have followed all guide regarding custom dataset such as x, y, z conversion, shifting center height to around 1.7 meter, check my bin generated from  `python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml tools/cfgs/dataset_configs/kitti_dataset.yaml
` , changing FOV in cfgs to False to detect all surrounding points and labels. Everything is okay. But the result of training is 0 AP. This is the last output of the training:

epochs:  99%|████████████▊| 79/80 [24:08<00:18, 18.58s/it, loss=nan, lr=3.13e-8]WARNING:root:NaN or Inf found in input tensor.8<00:00,  3.09it/s, total_it=4000]
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
train: 100%|█████████████████████| 50/50 [00:18<00:00,  2.66it/s, total_it=4000]
epochs: 100%|█████████████| 80/80 [24:08<00:00, 18.11s/it, loss=nan, lr=3.13e-8]
2021-11-10 00:19:26,591   INFO  **********************End training kitti_models/pointpillar(default)**********************

INFO:pcdet.utils.common_utils:**********************End training kitti_models/pointpillar(default)**********************

INFO:pcdet.utils.common_utils:*************** EPOCH 80 EVALUATION *****************
eval: 100%|███████████| 50/50 [00:05<00:00,  8.97it/s, recall_0.3=(0, 0) / 1173]
2021-11-10 00:20:37,044   INFO  *************** Performance of EPOCH 80 *****************
INFO:pcdet.utils.common_utils:*************** Performance of EPOCH 80 *****************
2021-11-10 00:20:37,044   INFO  Generate label finished(sec_per_example: 0.0281 second).
INFO:pcdet.utils.common_utils:Generate label finished(sec_per_example: 0.0281 second).
2021-11-10 00:20:37,044   INFO  recall_roi_0.3: 0.000000
INFO:pcdet.utils.common_utils:recall_roi_0.3: 0.000000
2021-11-10 00:20:37,044   INFO  recall_rcnn_0.3: 0.000000
INFO:pcdet.utils.common_utils:recall_rcnn_0.3: 0.000000
2021-11-10 00:20:37,044   INFO  recall_roi_0.5: 0.000000
INFO:pcdet.utils.common_utils:recall_roi_0.5: 0.000000
2021-11-10 00:20:37,044   INFO  recall_rcnn_0.5: 0.000000
INFO:pcdet.utils.common_utils:recall_rcnn_0.5: 0.000000
2021-11-10 00:20:37,044   INFO  recall_roi_0.7: 0.000000
INFO:pcdet.utils.common_utils:recall_roi_0.7: 0.000000
2021-11-10 00:20:37,044   INFO  recall_rcnn_0.7: 0.000000
INFO:pcdet.utils.common_utils:recall_rcnn_0.7: 0.000000
2021-11-10 00:20:37,044   INFO  Average predicted number of objects(198 samples): 0.000
INFO:pcdet.utils.common_utils:Average predicted number of objects(198 samples): 0.000
2021-11-10 00:20:37,157   INFO  Pedestrian AP@5.00, 5.00, 5.00:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP_R40@5.00, 5.00, 5.00:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000

INFO:pcdet.utils.common_utils:Pedestrian AP@5.00, 5.00, 5.00:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP_R40@5.00, 5.00, 5.00:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000

2021-11-10 00:20:37,157   INFO  Result is save to /home/yonas/OpenPCDet/output/kitti_models/pointpillar/default/eval/eval_with_train/epoch_80/val
INFO:pcdet.utils.common_utils:Result is save to /home/yonas/OpenPCDet/output/kitti_models/pointpillar/default/eval/eval_with_train/epoch_80/val
2021-11-10 00:20:37,158   INFO  ****************Evaluation done.*****************
INFO:pcdet.utils.common_utils:****************Evaluation done.*****************
2021-11-10 00:20:37,160   INFO  Epoch 80 has been evaluated
INFO:pcdet.utils.common_utils:Epoch 80 has been evaluated
Wait 30 seconds for next check (progress: 0.0 / 0 minutes): /home/yonas/OpenPCDe2021-11-10 00:21:07,189   INFO  **********************End evaluation kitti_models/pointpillar(default)**********************
INFO:pcdet.utils.common_utils:**********************End evaluation kitti_models/pointpillar(default)**********************

Is there something wrong in my dataset? or should I train with more epocs? Any help is appreciated.
Thanks

**Comment by ferrari700** [comment]
Hello, have you found the reason?

**Comment by zjr-bit** [comment]
Hi! have you solved the problem? I meet the same problem with you. Please give me some clue! Thank you!

**Comment by giangdip2410** [comment]
I have the same problem, have you find a solution yet?

**Comment by liyn69sysu** [comment]
hello,do you find a solution?Thanks

**Comment by AJAY31797** [comment]
Hi @liyn69sysu @giangdip2410 @zjr-bit @curiousboy20 @ferrari700 ,

I am facing the same issue with my custom dataset. Could you figure out the reason for this? 

Thanks.

**Comment by NurbekkWARTO** [comment]
@AJAY31797 Did you find a solution?
