### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by kx-Z** [open-mmlab/OpenPCDet#669]
When I use 1 gpu，It takes up 12.5g of memory，but when I use 2 gpus，why is there not enough memory，my machine has a total of 33.6g of memory.I used spconv2.0.

**Comment by jihanyang** [comment]
Try to disable pin_memory in dataloader

**Comment by kx-Z** [comment]
Thank you，but it‘s not work.The terminal will still reportdied with <Signals.SIGKILL: 9>，and after termination, the memory of my machine is still full.
![1](https://user-images.githubusercontent.com/84176922/141668374-6d139aee-5568-46b3-9d87-17ad0e338829.png)

**Comment by kx-Z** [comment]
I reduced num_workers,that's working!Thankyou!
