### ISSUE TITLE
Questions about using your own data set visualization

### ISSUE THREAD

**Issue by ferrari700** [open-mmlab/OpenPCDet#671]
Hello, OpenPCDet team! Thank you so much for your code! I used your voxel-rcnn pretained model to test my own data set, and adjusted the POINT_CLOUD_RANGE in kitti_dataset.yaml, but the point cloud image is incomplete and the coordinate system is still problematic. How can I solve it? Very grateful for your help！！
![Screenshot from 2021-11-14 20-55-59](https://user-images.githubusercontent.com/72401926/141682216-9b2f3514-16bd-41c4-badc-c53a9b9adb93.png)

**Comment by DavidWZX** [comment]
Hello @ferrari700 ! Have you solved the problem? I also met lots of problem when I run demo and test file on my own dataset. Can you share some tricks, please? Thanks a lot!

**Comment by MartinHahner** [comment]
Maybe you two can leverage my own [pointcloud_viewer.py](https://github.com/MartinHahner/LiDAR_fog_sim/blob/main/pointcloud_viewer.py).
