### ISSUE TITLE
Question about evaluation in custom dataset (Car vs Pedestrian)

### ISSUE THREAD

**Issue by curiousboy20** [open-mmlab/OpenPCDet#674]
Hi, I want to ask about the differences of evaluation in Car vs Pedestrian. I have my own custom dataset and the label. I tested it using:
`python test.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --batch_size 1 --ckpt model/pv_rcnn_8369.pth --save_to_file 
`

The results were 0 mAP in all classes. Then, I copied the output files from --save_to_ file to my label so it should be 100% mAP. But the result is only 100% mAP in Car but 0 mAP in Pedestrian. The output label generated is something like this:
```
Pedestrian -1 -1 -6.7963 1241.0000 0.0000 1241.0000 0.0000 1.6828 0.5327 0.7725 2.6077 -17.7760 1.4987 -6.9550 0.5029
Pedestrian -1 -1 -7.8842 675.3266 0.0000 1136.6663 0.0000 1.8199 0.7329 0.7306 0.5253 -23.6597 1.6412 -7.9219 0.4360
Pedestrian -1 -1 -4.8361 330.5197 0.0000 644.5231 0.0000 1.7578 0.6122 0.5559 -0.3213 -23.2970 1.6719 -4.8383 0.3672
Pedestrian -1 -1 -4.0165 1241.0000 0.0000 1241.0000 0.0000 1.8136 0.6502 0.8962 3.6396 -15.2092 1.4286 -4.2622 0.2633
Car -1 -1 -5.6926 0.0000 0.0000 1241.0000 374.0000 1.6205 1.6608 3.8050 -5.2442 5.7485 1.0911 -3.3373 0.1324
```

I use default pv_rcnn.yaml configuration file with detail like this:
https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/pv_rcnn.yaml

Why is the result different between Car vs Pedestrian?

I have try to change the matched_threshold and unmatched_threshold in configuration file:
matched_threshold = from 0.5 to 0.35
unmatched_threshold = from 0.35 to 0.2

but the result is still 0 mAP for Pedestrian class. Any help is appreciated. Thanks

**Comment by DJNing** [comment]
I am facing the same problem here
