### ISSUE TITLE
Can I see AP during training?

### ISSUE THREAD

**Issue by kx-Z** [open-mmlab/OpenPCDet#678]

**Comment by MartinHahner** [comment]
Not as of right now. Would be nice to have though.

**Comment by kx-Z** [comment]
> Not as of right now. Would be nice to have though.
Oh, thank you. That's a pity.

**Comment by sshaoshuai** [comment]
We do not support this since it will greatly slow down the training process.  

A potential strategy is to run a `test.py` with `--eval_all` simultaneously and you could see the AP curve from tensorboard.

**Comment by kx-Z** [comment]
> We do not support this since it will greatly slow down the training process.
> 
> A potential strategy is to run a `test.py` with `--eval_all` simultaneously and you could see the AP curve from tensorboard.

Thank you，got it. That‘s different from using a small val set when i was training a 2D model.

**Comment by MartinHahner** [comment]
> We do not support this since it will greatly slow down the training process.
> 
> A potential strategy is to run a `test.py` with `--eval_all` simultaneously and you could see the AP curve from tensorboard.

I forgot about that option. I think this approach is enough to track the process **while** training and no further coding is required.
