### ISSUE TITLE
I trained PV_RCNN on my GPU, but it failed to reach the test accuracy in the paper

### ISSUE THREAD

**Issue by mqm-slice** [open-mmlab/OpenPCDet#680]
I trained PV_RCNN on my GPU, but it failed to reach the test accuracy in the paper. There's a 3 percent difference in AP_R11.How should I train to be as close to the paper level as possible?

**Comment by xiazhongyv** [comment]
Maybe you should use the test code to test for every epoch and see the tensorboard curve. Because there always be sharp change of val performance on KITTI.
You can see the relevant discussion at #189 #314
