### ISSUE TITLE
no module named "pcdet.utils"

### ISSUE THREAD

**Issue by saurtone** [open-mmlab/OpenPCDet#692]
Finished processing dependencies for pcdet==0.5.0+0
python demo.py --cfg_file cfgs / kitti_models / pv_rcnn.yaml --ckpt pv_rcnn__8369.pth --data_path ${POINT_CLOUD_DATA}
from pcdet.utils import common_utils ModuleNotFoundError: no module named "pcdet.utils"

**Comment by sshaoshuai** [comment]
Maybe you also have the enviroment problem, please refer to https://github.com/open-mmlab/OpenPCDet/issues/699.

**Comment by saurtone** [comment]
邮件我已收到。辛苦了。

**Comment by Pddp-edg** [comment]
> 邮件我已收到。辛苦了。

请问这个问题您解决了吗？我也遇到了同样的问题

**Comment by saurtone** [comment]
邮件我已收到。辛苦了。

**Comment by luigifaticoso** [comment]
Hello, did you solve this problem? @saurtone
