### ISSUE TITLE
How to train CaDDN on 1080Ti GPU?

### ISSUE THREAD

**Issue by dk-liang** [open-mmlab/OpenPCDet#701]
I think it will out of memory, but the README.md describes that "All models are trained with 8 GTX 1080Ti GPUs".

**Comment by sshaoshuai** [comment]
The model of CaDDN is merged by the author of CaDDN (may not use GTX 1080Ti), and all the LiDAR-only models are trained with GTX 1080Ti.

**Comment by pankongpc** [comment]
Same question, any solution?
