### ISSUE TITLE
AttributeError: 'DataBaseSampler' object has no attribute 'use_shared_memory' for multiple-gpu.

### ISSUE THREAD

**Issue by tdzdog** [open-mmlab/OpenPCDet#702]
I have recently transferred to pcdet 0.5. However, I met the above problem for multiple-gpu training (single GPU works fine). It is weird.  What is the reason?

**Comment by MartinHahner** [comment]
See https://github.com/open-mmlab/OpenPCDet/issues/699

**Comment by tdzdog** [comment]
> See #699

Thank for replying, Martion. But I have tried to re-build pcdet as mentioned in #699 but it does not work.

**Comment by sshaoshuai** [comment]
You could re-try it carefully (create a new conda enviroment for it or remove all the previous pcdet versions), since I am pretty sure it is a problem of environment.

**Comment by hz3014** [comment]
> > See #699
> 
> Thank for replying, Martion. But I have tried to re-build pcdet as mentioned in #699 but it does not work.

Simple walk around is just to comment def __del__(self): function in database_sampler.py
