### ISSUE TITLE
Can not use the visualize utils on the remote Linux server.

### ISSUE THREAD

**Issue by Cc-Hy** [open-mmlab/OpenPCDet#703]
Can not use the visualize utils on the remote Linux server. There is no GUI.
I tried a lot of things but it didn't work out.
Any advice?
Thanks.

**Comment by MartinHahner** [comment]
Maybe have a look at my point cloud viewer: https://github.com/MartinHahner/LiDAR_fog_sim/blob/main/pointcloud_viewer.py
You can fork the repo and adjust it to your needs.
