### ISSUE TITLE
AttributeError: type object 'spconv.core_cc.csrc.sparse.all.SpconvOps' has no attribute 'generate_subm_conv_inds'

### ISSUE THREAD

**Issue by Karthikeyanc2** [open-mmlab/OpenPCDet#704]
Hi,

Thanks for the great repo. 
I am facing some issues while training pv_rcnn model (with Kitti dataset)

![image](https://user-images.githubusercontent.com/53954194/145237597-5861016b-fc99-4727-a97a-5412bb6e8f2c.png)

Spcov version: 2.1.20
pcdet version: 0.5
torch version: 1.10
cuda version: 11.3

I do not know if the error is from spconv side or from pcdet side.
Note: Pointpillars network runs perfectly.

Thanks,
Karthik

**Comment by Karthikeyanc2** [comment]
Sorry, wrong spconv installation.

**Comment by LegendSun0** [comment]
> 抱歉，spconv 安装错误。

麻烦问一下，应该安装Spcov什么版本？

**Comment by Stone-sy** [comment]
我遇到了和你一样的问题，请问你解决了吗？

**Comment by KyleYueye** [comment]
> 我遇到了和你一样的问题，请问你解决了吗？

一样的问题……

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！

**Comment by brillint** [comment]
> 我遇到了和你一样的问题，请问你解决了吗？
你安装的是cpu版本，gpu版本应该这样： pip install spconv-cu113 -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by Xavier-wa** [comment]
my device is jetson nx xavier and ubuntu ,spconv:v2.3.6 cu114,but I got the error:from spconv.core_cc.csrc.sparse.all import SpconvOps
ModuleNotFoundError: No module named 'spconv.core_cc'

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！

**Comment by swaggywilliam** [comment]
> > 我遇到了和你一样的问题，请问你解决了吗？
> > 你安装的是cpu版本，gpu版本应该这样： pip install spconv-cu113 -i https://pypi.tuna.tsinghua.edu.cn/simple/

I installed spconv1.2.1 as [follows](https://github.com/traveller59/spconv/tree/v1.2.1):

1. Use git clone xxx.git --recursive to clone this repo.

2. Install boost headers to your system include path, you can use either sudo apt-get install libboost-all-dev or download compressed files from boost official website and copy headers to include path.

3. Download cmake >= 3.13.2, then add cmake executables to PATH.

4. Ensure you have installed pytorch 1.0+ in your environment, **run python setup.py bdist_wheel (don't use python setup.py install).**

5. Run cd ./dist, use pip to install generated whl file.

and I change the version.txt from 2.3.6 to 1.2.1, then I get the only one wheel file in 
![image](https://github.com/open-mmlab/OpenPCDet/assets/56567411/b1fa4def-8ec4-4bc3-a2a3-562fed965adb)

as you can see, what I got maybe was a CPU version spconv,  and how can I get a GPU version?
The version of spconv installed with the command you suggested is the newest version or others?
