### ISSUE TITLE
Syntax error in setup.py

### ISSUE THREAD

**Issue by chapa17** [open-mmlab/OpenPCDet#708]
Hello,

I want to install **pcdet v0.5** but when I run python setup.py develop I get a runtime error for version mismatch between CUDA and pytorch.  I tried different cuda and pytorch versions but the mismatch error still persists.

<img width="925" alt="Screenshot from 2021-12-10 12-43-03" src="https://user-images.githubusercontent.com/74726040/145570341-c4f9ae7e-9a8a-4c76-a051-179d9aa1aa5a.png">

I would be very thankful if I can get some hint to this error.

Thank you

**Comment by alinutzal** [comment]
You need to do two things:
-setup your CUDA as 11.3
-install pytorch with cudatoolkit 11.3 (conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch())
