### ISSUE TITLE
my own dataset

### ISSUE THREAD

**Issue by ChunmianLin** [open-mmlab/OpenPCDet#709]
Hi, everyone, there are some questions confused me, could you please give me some helps?
My own dataset is lidar-only file on roadside scene:
1. How do I modify the data config file and dataloader, such as based on kitti dataset. The direction of zero orientation is long the x-axis, but it increase in clockwise manner. And the orientation is presented as angle, not the radian. 
2. How to set the range of point cloud and anchor? I have calculate the height, width, length, x, y and z value for each category, but the 'anchor_bottom_height' parameter still confuses me.
Any helps would be appreciated a lot.

**Comment by jihanyang** [comment]
#253
