### ISSUE TITLE
Hi，a question about nms_thresh in post_processing

### ISSUE THREAD

**Issue by Ultra11nstinct** [open-mmlab/OpenPCDet#713]
i found that the nms_thresh in SECOND is 0.01 and in other approches like pv-rcnn is 0.1.

i wonder why the configuration is different in different approaches. Is there a reason？

if i want to submit results to official servers，is there a performance gap between the two thresholds？

**Comment by sshaoshuai** [comment]
Generally it doesn't matter much for the performance of the validation set. For the test submission I think it will also not matter much.
