### ISSUE TITLE
Is this config PV-RCNN++?

### ISSUE THREAD

**Issue by MartinHahner** [open-mmlab/OpenPCDet#714]
https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/waymo_models/pv_rcnn_with_centerhead_rpn.yaml

**Comment by sshaoshuai** [comment]
No, it just replaced the anchor-based head of PV-RCNN by center-based head. 

I haven't integrated PV-RCNN++ to this repo yet. It still needs some time.

**Comment by sshaoshuai** [comment]
Hi, the codes of PV-RCNN++ has been released just now.
