### ISSUE TITLE
Large memory footprint for version 0.5

### ISSUE THREAD

**Issue by tdzdog** [open-mmlab/OpenPCDet#716]
Recently, I have updated into pcdet v0.5. However, when I am training on waymo, I have noticed larger memory footprint compared with the old version (0.3). On the same machine, I have to use a smaller number of workers for v0.5. Is this normal?

**Comment by jihanyang** [comment]
Hello, it seems that the default sampled interval for gt database in openpcdet before v0_3_1 is 10. So, if you have regenerate the gt database, the larger memory footprint might caused by the larger gt database.

**Comment by tdzdog** [comment]
That makes sense. I guess a smaller sampling interval is adopted for better precision? Is there any quantitative result?
