### ISSUE TITLE
Database sampler NuScenes: Sampling of consecutive (object) points even when training on single sweep 

### ISSUE THREAD

**Issue by chreisinger** [open-mmlab/OpenPCDet#718]
The NuScenes dataset provides the training/detection on max. 10 consecutive LiDAR sweeps. OpenPCDet considers this while data extraction and gt_database generation with the flag MAX_SWEEPS. However, all sweeps may not always be required/wanted while training/inference.  Hence, if you train on less than 10 sweeps (e.g. 1 sweep), you have to extract the data with the exact number of sweeps you want. Otherwise, the data loader provides the correct point cloud (with e.g. 1 sweep), but the gt_sampler still considers all 10 sweeps and thus provides inconsistent information.

**Comment by chreisinger** [comment]
I would provide a quick fix for this one, but I am not able to contribute.

**Comment by MartinHahner** [comment]
@chreisinger: You can always create a pull request.
