### ISSUE TITLE
找不到Predicted Keypoint Weighting这个模块的代码

### ISSUE THREAD

**Issue by chenzhengfang** [open-mmlab/OpenPCDet#723]
作者您好，我在您公布的代码中并没有找到Predicted Keypoint Weighting这个模块的代码，我将所有代码都找遍了也没发现，您能告诉我一下这个模块的代码具体的位置吗，谢谢。

**Comment by sshaoshuai** [comment]
Close it since it is duplicate with https://github.com/open-mmlab/OpenPCDet/issues/722
