### ISSUE TITLE
Questions about training custom data sets

### ISSUE THREAD

**Issue by ferrari700** [open-mmlab/OpenPCDet#727]
Hello, if I need to train a custom data set (only point cloud data), do I need to convert the coordinates of the 3D bounding box in the label's txt file to the camera coordinate system like kitti ? Thanks!

**Comment by OrangeSodahub** [comment]
Hello, you can refer to my successful example using kitti format custom dataset. README describes how to label, train, inference it including transformation of coordinates. It may solve your problems!
https://github.com/OrangeSodahub/CRLFnet#lid-cam-fusion
https://github.com/OrangeSodahub/CRLFnet/blob/master/src/site_model/src/LidCamFusion/OpenPCDet/pcdet/datasets/custom/README.md
