### ISSUE TITLE
How to set the POINT_CLOUD_RANGE during training?

### ISSUE THREAD

**Issue by speshowBUAA** [open-mmlab/OpenPCDet#730]
I wanted to train pointpillars in nuscenes within limited range of point cloud. When I set the POINT_CLOUD_RANGE parameters in nuscenes_dataset.yaml and cbgs_pp_multihead.yaml from [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0] to [-11.2, -11.2, -5.0, 11.2, 11.2, 3.0], I got that the training result AP was very low. Did I make some mistakes?
[https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/nuscenes_models/cbgs_pp_multihead.yaml](url)
`POINT_CLOUD_RANGE: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]`
[https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/nuscenes_dataset.yaml](url)
`POINT_CLOUD_RANGE: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]`

**Comment by jihanyang** [comment]
Sorry, I cannot open the provided hypelink, but I think this is normal. Since you decrease the point cloud range, the detected boxes will be fewer, but the number of gt boxes will not change, which harm the AP.
