### ISSUE TITLE
Does the point_head support nuScenes?

### ISSUE THREAD

**Issue by xiazhongyv** [open-mmlab/OpenPCDet#733]
Hi, I'm trying to train my point_head model on nuScenes dataset.
I found in [point_head_template.py](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/models/dense_heads/point_head_template.py#L69) there is an assert that limits gt_box[2] to 8. 
When I using nuScenes dataset,  input_dict['gt_boxes'].shape is (B, M, 10). So I got an AssertionError.

And I noticed that in archor_head, there's no similar assert, but gt_box is commented (B, M, 8). 
When I training with nuscenes_models/cbgs_pp_multihead.yaml and nuscenes_models/cbgs_second_multihead.yaml, gt_box is (B, M, 10) too. Because there is no assertion, the training proceeds normally.

Therefore, I would like to ask what's the format of gt_box(B, M, 8) and gt_box(B, M, 10). And are they identical in the first eight dimensions? Is point_head's assertion unnecessary, or is archor_head missing assertions and buggy, or is archor_head compatible for different gt_box formats but point_head isn't?

Thanks!

**Comment by daeunni** [comment]
same here. did you solved this problem?
