### ISSUE TITLE
RuntimeError: Cannot install on Python version 3.6.13

### ISSUE THREAD

**Issue by RonaldYuren** [open-mmlab/OpenPCDet#745]
1.as mentioned, I can't run the " python setup.py develop "  mentioned in the INSTALL.md by python3.6.13
*** I tried to update anaconda to 3.7, and run again, but it still showed the message as following.
//
  File "/tmp/easy_install-f_n523a3/scipy-1.8.0rc2/setup.py", line 31, in <module>
    version = '0.5.2+%s' % get_git_commit_number()
RuntimeError: Python version >= 3.8 required.

//

2. I am using the CUDA 9.1 and Pytorch1.1 in UBUNTU , I think that the sponcv V2.x would not come up any errors, right ?

3. I just want to use the version for the condition mentioned on the above, thanks!

**Comment by jihanyang** [comment]
spconv v2.x don't not support CUDA 9.1.

**Comment by RonaldYuren** [comment]
> spconv v2.x don't not support CUDA 9.1.

then how to download the former version of spconv?

**Comment by jihanyang** [comment]
You should raise this issue in Spconv.

**Comment by HenryJunW** [comment]
I am using Python 3.6.13 and spconv 1.2, and face the similar #1 problem. Solved by 'conda install numba==0.49.1'. Since default 'numba-0.55.0' requires python 3.7. Hope that helps.
