### ISSUE TITLE
I want to find the OpenPCDet former version

### ISSUE THREAD

**Issue by RonaldYuren** [open-mmlab/OpenPCDet#746]
I want to find the oldder version for python3.7 or 3.6
INSTALL.md will have to use the python3.8

my CUDA is 9.1, i want to use pytorch 1.1 , so it need python to <3.8

Or somebody can tell me which pytorch is suitable for CUDA 9.1

**Comment by jihanyang** [comment]
OpenPCDet can support python3.6+

**Comment by RonaldYuren** [comment]
what i mean is that, with CUDA 9.1, INSTALL.md have to use the python3.8 to run " python setup.py develop "
but pytorch 1.1 can't support python3.8
