### ISSUE TITLE
Typo in train.py?

### ISSUE THREAD

**Issue by JenWei0312** [open-mmlab/OpenPCDet#752]
thought 
#L189     args.start_epoch = max(args.epochs - 0, 0)
should be 'args.epochs - 0'?
Thanks

**Comment by LouisSF** [comment]
If you want to evaluate the last 10epochs, as implied by the comment following this line, then this is a type and should be replaced with  args.start_epoch = max(args.epochs - 10, 0)``

**Comment by sshaoshuai** [comment]
Thanks. 
Fixed in https://github.com/open-mmlab/OpenPCDet/pull/770.
