### ISSUE TITLE
How does the refinement network of PVRCNN++ work when there is no valid ROI?

### ISSUE THREAD

**Issue by Kemo-Huang** [open-mmlab/OpenPCDet#764]
When there is few ROI from the RPN, "vector pool local interpolate" module will fail due to no support xyz or support feature.

However, it is very likely that there is no vehicle in the test data so that the RPN won't generate enough foreground ROI for refinement.

Specific error:
`
File "/home/kemo/Github/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/pointnet2_modules.py", line 230, in forward
    near_known_xyz = support_xyz[idx.view(-1, 3).long()].view(-1, 3, 3)  # ( (M1 + M2 ...)*num_total_grids, 3)
IndexError: index is out of bounds for dimension with size 0
`

How to fix it?

**Comment by sshaoshuai** [comment]
Generally we will have several faked RoIs from proposal_layer, the RCNN heads will predict low confidence for these faked RoIs. 

For your case, is it the problem of empty keypoints? I didn't meet this error before, maybe the SPC layer didn't find any points within the neighboring regions of RoIs. So you get empty support_xyz tensor. 

You need to check whether the following warning is printed and maybe you need to fake some keypoints in this place to skip this error: 

https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/models/backbones_3d/pfe/voxel_set_abstraction.py#L109-L119
