### ISSUE TITLE
About evaluating waymo datasets.

### ISSUE THREAD

**Issue by kx-Z** [open-mmlab/OpenPCDet#767]
I0120 23:13:53.815790 30010 detection_metrics_ops.cc:157] Computing detection metrics for 1026059 predicted boxes.
I0120 23:13:53.815812 30010 detection_metrics_ops.cc:159] Parsing prediction [1026059,7][1026059]
I0120 23:13:54.045742 30010 detection_metrics_ops.cc:168] Parsing ground truth [1123373,7][1123373]
I0120 23:14:19.839358 30010 detection_metrics_ops.cc:221] Done with computing detection metrics.

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7637 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7584 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6738 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6690 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APH: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.0000 

I just want to experiment with the vehicle class, but it seems to take a lot of time to calculate other classes. How to get rid of them?

**Comment by sshaoshuai** [comment]
If the prediction dict does not have any predicted pedestrian/cyclist, I guess it will not spend lots of time on calculating the metric of pedestrian./cyclist.
