### ISSUE TITLE
how to convert coordinates with own data?

### ISSUE THREAD

**Issue by dengting-web** [open-mmlab/OpenPCDet#768]
724706.21999979 5649433.59000015 275.16000366 0.0
724706.21999979 5649433.27000046 275.16000366 0.0
724706.21999979 5649432.88999939 275.19000244 0.0
724706.21999979 5649432.56999969 275.17999268 0.0
724706.23000002 5649432.22000122 275.23001099 0.0
724706.23000002 5649431.87999916 275.20999146 0.0

this is how my points look like, its x, y, z and intensity value, in .npy is like 
[[724706.21999979 5649433.59000015 275.16000366 0.0]
 [724706.21999979 5649433.27000046 275.16000366 0.0]
 [724706.21999979 5649432.88999939 275.19000244 0.0]
 ...
 [724706.21999979 5649432.56999969 275.17999268 0.0]
 [724706.23000002 5649432.22000122 275.23001099 0.0]
 [724706.23000002 5649431.87999916 275.20999146 0.0]]

is it good conversion?

_Originally posted by @kamillasak in https://github.com/open-mmlab/OpenPCDet/issues/176#issuecomment-669183390_

**Comment by OrangeSodahub** [comment]
Hello, you can refer to my successful example using kitti format custom dataset. README describes how to label, train, inference it including transformation of coordinates. It may solve your problems!
https://github.com/OrangeSodahub/CRLFnet#lid-cam-fusion
https://github.com/OrangeSodahub/CRLFnet/blob/master/src/site_model/src/LidCamFusion/OpenPCDet/pcdet/datasets/custom/README.md
