### ISSUE TITLE
demo.py problem on latest pcdet-0.5.2

### ISSUE THREAD

**Issue by xuf2** [open-mmlab/OpenPCDet#776]
Use latest version pcdet v0.5.2. All installation process w/o any problem, but when running demo.py with one frame KITTI data which occurred below error:

**RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from pcdet.datasets import DatasetTemplate
  File "/home/u_xuf2/OpenPCDet/pcdet/datasets/__init__.py", line 5, in <module>
    from pcdet.utils import common_utils
  File "/home/u_xuf2/OpenPCDet/pcdet/utils/common_utils.py", line 7, in <module>
    import SharedArray
ImportError: numpy.core.multiarray failed to import**

Follow below environment:
Ubuntu18.04
Python 3.8
miniconda-4.10.3
PyTorch 1.9
CUDA11.1+cuDNN8.0.5
spconv1.2
pcdet v0.5.2(latest)
open3d-0.14.1/mayavi-4.8.0
numpy-1.20.0

For error notice, try to update higher numpy version, but other error occurred.

Also try the same above configuration environment for older pcdet_v0.3.0 installation on another PC, all process have no problem and the demo.py worked well as expected.

**Comment by sshaoshuai** [comment]
Please just try to re-install 'SharedArray'.

**Comment by xuf2** [comment]
Thanks for the reply, I try to reinstall lower version SharedArray==3.1 and solve this problem
