### ISSUE TITLE
about second_iou

### ISSUE THREAD

**Issue by mc171819** [open-mmlab/OpenPCDet#781]
Hi, thank you for your code. I don't really understand the function roi_grid_pool in the roi head of second, especially why you sample the original 2d feature to a 7x7 size. Can you explain it to me?

**Comment by jihanyang** [comment]
That just a rotated version of roi_grid_pooling in FasterRCNN.

**Comment by russellyq** [comment]
@jihanyang hi I have similar question and is confused about your ROI-HEAD of "SECONDHead". Can you give more explanation ?
