### ISSUE TITLE
performance of SECOND on Waymo

### ISSUE THREAD

**Issue by pigtigger** [open-mmlab/OpenPCDet#785]
I trained second (8GPUs) with config from pcdet  but got much worse performance than the results reported in README.  Will the version of spconv  be the reason?  I  use spconv 2 in my experiment and here is the results of 30 epoch.  
![image](https://user-images.githubusercontent.com/39974202/152292716-9ba965ea-c50d-4056-9fea-f0d6aae9cea2.png)

**Comment by sshaoshuai** [comment]
Have you generated the new data info with pcdet v0.5+?

**Comment by pigtigger** [comment]
@sshaoshuai Not yet, I created the data with pcdet 0.3, so the new version of data can improve performance?

**Comment by pigtigger** [comment]
@sshaoshuai, I generated the new waymo data and train SECOND (cfgs/waymo_models/second.yaml) again with the latest code,  but I met a strange bug: every thing was good at the beginning, but after some epochs the loss became nan and finally the evaluated mAP is zero. I did not change any code, did you meet this problem before?
![image](https://user-images.githubusercontent.com/39974202/152664985-b8fd976d-e3c3-4ad6-966d-2416c65f046d.png)
![image](https://user-images.githubusercontent.com/39974202/152664987-a4e8a977-dabf-497b-8877-46bfca324cb0.png)

**Comment by jihanyang** [comment]
@pigtigger Please just re-run the experiment again. This is a known issue, but will not take place frequently.

**Comment by pigtigger** [comment]
@jihanyang Thank you, I will have a try, btw, do you know why this problem occurs frequently? I meet this nan bug in my own model but can not figure out what causes it.

**Comment by jihanyang** [comment]
Actually, we are still not clear about the reason, since this is problem not easy to trace and hard to reproduce. From my experience, even the same code, this error could take place frequently in some machines while not appear at all in other machines. If you have any suggestion to solve this, feel free to let us know.

**Comment by pigtigger** [comment]
Thank you :) @jihanyang , re-run the experiment does work, I will share my solution if find it.
