### ISSUE TITLE
Question about subm conv and sparse conv.

### ISSUE THREAD

**Issue by tdzdog** [open-mmlab/OpenPCDet#788]
There are both subm conv and sparse conv in the backbone (VoxelBackBone8x).  But I noticed that sparse conv is only used for downsampling (stride=2). Hence I replace the sparse conv with a subm conv and a maxpooling layer. However, I got -1.5 mAP on second (KITTI).  I am confused about the role of sparse conv. Why it cannot be replaced with subm conv?

**Comment by sshaoshuai** [comment]
Sparse conv can generate more dense voxels than subm conv and may achieve better performance, while subm conv is much efficient. So that's a trade-off between these two convs.
