### ISSUE TITLE
Tools to visualize the detection result.

### ISSUE THREAD

**Issue by LZDSJTU** [open-mmlab/OpenPCDet#79]
Hi, I want to ask which tools can visualize the detection result.

Additionally, if I train the network in server and want to visualize in the windows10, is there any tool recommended?

If anyone has recommended tools, comment in this topic. Thank you very much.

**Comment by penghao1990** [comment]
kittiviewer  in  traveller59 /second.pytorch. (html+css+js+flask)     :)

**Comment by ltphy** [comment]
You can use [http://www.open3d.org/docs/release/tutorial/Advanced/customized_visualization.html](url) and self implemented your own visualization with pickle file.

**Comment by MartinHahner88** [comment]
@sshaoshuai: Do you still plan to release/integrate your visualization code to this repository?

**Comment by sshaoshuai** [comment]
@MartinHahner88 ，ok，I will prepare a simple visualization codes to `PCDet` soon.

**Comment by sshaoshuai** [comment]
Hi all, a simple visualization tool and [quick demo](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md) is available now.

**Comment by Petros626** [comment]
<img width="1919" height="1000" alt="Image" src="https://github.com/user-attachments/assets/d6b2c883-a842-4e74-bb97-464678c6cf33" />
