### ISSUE TITLE
Batch size in "voxels", "voxel_coords", "voxel_num_points" after collate_batch() method

### ISSUE THREAD

**Issue by skprot** [open-mmlab/OpenPCDet#794]
Why do we not use the dimension of the batch size when forming the tensor for the following quantities "voxels", "voxel_coords", "voxel_num_points", but simply concatenate them in collate_batch() method in KITTI dataset class?

**Comment by sshaoshuai** [comment]
Because different scenes may have different number of voxels and you need to pad many zeros if you want to use the batch size dimension.

**Comment by skprot** [comment]
Thanks for your quick response! Now it is clear
