### ISSUE TITLE
NumbaDeprecationWarning: Eager compilation of device functions is deprecated (this occurs when a signature is provided)

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/OpenPCDet#810]
Hi, 
Why this kind of Numba error occurred?
This warning occurred in valid prediction part. 

![image](https://user-images.githubusercontent.com/62705839/154244911-f6ace3d5-130e-47ec-bfbd-2eb07794be58.png)

I'd really appreciate it if someone helped me.
Best,

**Comment by jihanyang** [comment]
Sorry, I never meet this numba error. Hope some other researchers can help you.

**Comment by LouisSF** [comment]
I think this is due to type inference issues, you may find more details on the official [Numba deprecation page](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html)

A workaround I used to suppress these warnings was to use the following code:
```
from numba.core.errors import (NumbaDeprecationWarning, 
                                    NumbaPendingDeprecationWarning,
                                    NumbaPerformanceWarning)
import warnings
warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaPendingDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaPerformanceWarning)
```

You have to be careful where you place the following block of code, generally in the same python file as the called numba functions.

**Comment by daeunni** [comment]
> I think this is due to type inference issues, you may find more details on the official [Numba deprecation page](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html)
> 
> A workaround I used to suppress these warnings was to use the following code:
> 
> ```
> from numba.core.errors import (NumbaDeprecationWarning, 
>                                     NumbaPendingDeprecationWarning,
>                                     NumbaPerformanceWarning)
> import warnings
> warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
> warnings.simplefilter('ignore', category=NumbaPendingDeprecationWarning)
> warnings.simplefilter('ignore', category=NumbaPerformanceWarning)
> ```
> 
> You have to be careful where you place the following block of code, generally in the same python file as the called numba functions.

Thanks for reply :)
