### ISSUE TITLE
A question about the objects confidence of the output.

### ISSUE THREAD

**Issue by mmmmaomao** [open-mmlab/OpenPCDet#814]
Hello!

I only detect vehicle, pedestrian and cyclist in Kitti. If count the background class, there are four classes. Then the score corresponding to the largest class generated by softmax in the classification stage should not be less than 0.25, but during visualization, I found that the score corresponding to some bbox is 0.11. So is this score the probability of softmax's output? 

And is the thresh in the post-processing filtering the score of the softmax?
`
POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False
`
Thank you！

**Comment by mmmmaomao** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/55339200/154801001-e237f218-84d7-413e-bf42-3554615cdaec.png">
For example, the score of one car in this result is 0.11. Is this score processed by raw softmax score?

**Comment by jihanyang** [comment]
No. That's score after sigmoid.

**Comment by Leozyc-waseda** [comment]
![image](https://user-images.githubusercontent.com/52599722/168770640-223d1ffb-8416-4a98-9eae-bcdd4f739797.png)
If this is the output of the sigmoid function, what's the meaning in these numbers?

It doesn't look like a binary classification problem.
