### ISSUE TITLE
CUDA error in boxes_iou3d_gpu

### ISSUE THREAD

**Issue by Guoxs** [open-mmlab/OpenPCDet#816]
I trained PointPillars on KITTI datasets using multi-gpu on single machine using this command:
`bash ./scripts/dist_train.sh 4 --cfg_file cfgs/kitti_models/pointpillar.yaml`

when I finished training and started evaluation, error happened. 
CUDA version 10.2, ubuntu 18.04, pcdet+0.5.2+70857b8
![image](https://user-images.githubusercontent.com/11255550/154935033-ce87a654-a039-4bad-ad89-c2bb231ef6a4.png)

**Comment by MartinHahner** [comment]
Which GPU do you use? Is it an RTX 30..?

Maybe this thread helps:
https://github.com/open-mmlab/OpenPCDet/issues/273

**Comment by Guoxs** [comment]
my GPUs are RTX 2080. I have install spconv-cu102==2.1.12

**Comment by Guoxs** [comment]
> Which GPU do you use? Is it an RTX 30..?
> 
> Maybe this thread helps: #273

 I rebuild pcdet after update cumm-cu102  to 0.2.8 and spconv-cu102 to 2.1.21, but this problem remains.

**Comment by Guoxs** [comment]
when I run `python demo.py` , "Error!" also occurs, I can not find where it was printed.

![image](https://user-images.githubusercontent.com/11255550/154955201-104bb213-59d2-4a41-9d50-12fdd49f2e71.png)

**Comment by MartinHahner** [comment]
> when I run `python demo.py` , "Error!" also occurs, I can not find where it was printed.

https://github.com/open-mmlab/OpenPCDet/blob/e1bfcecbf4966fe417bf56fa60d6e177a1909724/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp#L133

https://github.com/open-mmlab/OpenPCDet/blob/e1bfcecbf4966fe417bf56fa60d6e177a1909724/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp#L183

**Comment by Guoxs** [comment]
Thank you! So how can I fix this? @MartinHahner

**Comment by MartinHahner** [comment]
The `Error!` printouts indicate that CUDA is not working properly on your machine. 
Try to use a different / newer CUDA version and rebuild pcdet.

**Comment by Guoxs** [comment]
I found my CUDA version (10.0) is not matched with nvidia driver (10.2), and when I update CUDA to 10.2 and rebuild pcdet, it was solved. Thank you for your kindness help!
