### ISSUE TITLE
About the support of PV-RCNN++

### ISSUE THREAD

**Issue by Orbis36** [open-mmlab/OpenPCDet#829]
The corresponding .ymal file can't be found when I want to use it in the KITTI dataset.
So does it mean I can use or modified the 'PV_RCNN.yaml' directly to train the PV_RCNN++?
Or it has not been supported yet by OpenPCDet?

Thanks for any help.

**Comment by sshaoshuai** [comment]
The KITTI config of PV-RCNN++ is not supported yet since the codes have been refactored and most experiments are conducted on Waymo. 

We do not tune much parameters in KITTI so one thing you can try is to modify the PV_RCNN++ config of Waymo to KITTI dataset.

**Comment by MartinHahner** [comment]
@sshaoshuai: I tried doing that and unfortunately could not succeed.
That is why I opened issue https://github.com/open-mmlab/OpenPCDet/issues/747.

**Comment by sshaoshuai** [comment]
Ok, I will find time to look into it recently. 
Note that the performance is not expected to be much better than PV-RCNN in KITTI dataset since the KITTI dataset is small and the performance is also unstable (that's also why I did most experiments on Waymo Dataset). But it should be more memory-efficient than PV-RCNN.

**Comment by sshaoshuai** [comment]
I wrote of PV-RCNN++ config for KITTI dataset by slightly modifying the config of WOD. 
(Use AnchorHead, keypoint:2048, and we can train PV-RCNN++ with larger batch_size=4 on 11GB GPUs)

The results and config are as follows:  

Here is a result from my side: 
```
022-03-11 02:13:05,193   INFO  recall_roi_0.3: 0.968314
2022-03-11 02:13:05,193   INFO  recall_rcnn_0.3: 0.968940
2022-03-11 02:13:05,193   INFO  recall_roi_0.5: 0.927925
2022-03-11 02:13:05,193   INFO  recall_rcnn_0.5: 0.931452
2022-03-11 02:13:05,193   INFO  recall_roi_0.7: 0.706752
2022-03-11 02:13:05,193   INFO  recall_rcnn_0.7: 0.750839
2022-03-11 02:13:05,195   INFO  Average predicted number of objects(3769 samples): 9.499
2022-03-11 02:13:30,316   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:90.6572, 89.6768, 89.2032
bev  AP:89.8610, 87.9713, 87.3142
3d   AP:88.8617, 83.6246, 78.6445
aos  AP:90.64, 89.56, 88.98
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:96.1084, 94.7267, 94.2113
bev  AP:92.8120, 90.6260, 88.4745
3d   AP:91.5264, 84.5111, 82.2970
aos  AP:96.08, 94.56, 93.93
Car AP@0.70, 0.50, 0.50:
bbox AP:90.6572, 89.6768, 89.2032
bev  AP:90.5914, 94.7703, 89.2633
3d   AP:90.5914, 94.7173, 89.2181
aos  AP:90.64, 89.56, 88.98
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:96.1084, 94.7267, 94.2113
bev  AP:96.0526, 96.5511, 94.4686
3d   AP:96.0423, 96.1660, 94.3803
aos  AP:96.08, 94.56, 93.93
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:77.6912, 72.7228, 68.9964
bev  AP:66.5163, 62.0834, 56.8533
3d   AP:64.0408, 58.5153, 53.9799
aos  AP:73.21, 68.18, 63.99
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:78.3331, 73.7831, 70.3085
bev  AP:67.2273, 61.2886, 56.8762
3d   AP:63.5890, 57.5630, 52.1814
aos  AP:73.52, 68.67, 64.79
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:77.6912, 72.7228, 68.9964
bev  AP:80.2445, 77.0728, 74.7157
3d   AP:80.2238, 76.9786, 74.6168
aos  AP:73.21, 68.18, 63.99
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:78.3331, 73.7831, 70.3085
bev  AP:82.9161, 79.2863, 75.9079
3d   AP:82.8934, 79.1893, 75.7954
aos  AP:73.52, 68.67, 64.79
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:90.0376, 83.0204, 78.0418
bev  AP:88.5554, 75.9622, 73.4186
3d   AP:87.6325, 74.5702, 70.9378
aos  AP:89.95, 82.57, 77.58
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:95.9116, 84.1527, 80.9133
bev  AP:94.1572, 78.4721, 73.8510
3d   AP:93.0001, 75.5205, 70.9390
aos  AP:95.77, 83.69, 80.36
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:90.0376, 83.0204, 78.0418
bev  AP:88.8730, 80.0251, 75.3880
3d   AP:88.8730, 80.0251, 75.3880
aos  AP:89.95, 82.57, 77.58
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:95.9116, 84.1527, 80.9133
bev  AP:94.5783, 81.9240, 77.6392
3d   AP:94.5783, 81.9240, 77.6392
aos  AP:95.77, 83.69, 80.36

```

Here is the config of PV-RCNN++ for KITTI dataset:
```
CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml


MODEL:
    NAME: PVRCNNPlusPlus

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'Car',
                'anchor_sizes': [[3.9, 1.6, 1.56]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-1.78],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.45
            },
            {
                'class_name': 'Pedestrian',
                'anchor_sizes': [[0.8, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            },
            {
                'class_name': 'Cyclist',
                'anchor_sizes': [[1.76, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    PFE:
        NAME: VoxelSetAbstraction
        POINT_SOURCE: raw_points
        NUM_KEYPOINTS: 2048
        NUM_OUTPUT_FEATURES: 90
        SAMPLE_METHOD: SPC
        SPC_SAMPLING:
            NUM_SECTORS: 6
            SAMPLE_RADIUS_WITH_ROI: 1.6

        FEATURES_SOURCE: ['bev', 'x_conv3', 'x_conv4', 'raw_points']
        SA_LAYER:
            raw_points:
                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 2
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [ 32 ]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 2.4

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [ 2, 2, 2 ]
                    MAX_NEIGHBOR_DISTANCE: 0.2
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 32, 32 ]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 0.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 32, 32 ]

            x_conv3:
                DOWNSAMPLE_FACTOR: 4
                INPUT_CHANNELS: 64

                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 32
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [128]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 4.0

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [3, 3, 3]
                    MAX_NEIGHBOR_DISTANCE: 1.2
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [64, 64]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 2.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]

            x_conv4:
                DOWNSAMPLE_FACTOR: 8
                INPUT_CHANNELS: 64

                NAME: VectorPoolAggregationModuleMSG
                NUM_GROUPS: 2
                LOCAL_AGGREGATION_TYPE: local_interpolation
                NUM_REDUCED_CHANNELS: 32
                NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
                MSG_POST_MLPS: [ 128 ]
                FILTER_NEIGHBOR_WITH_ROI: True
                RADIUS_OF_NEIGHBOR_WITH_ROI: 6.4

                GROUP_CFG_0:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 2.4
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]
                GROUP_CFG_1:
                    NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                    MAX_NEIGHBOR_DISTANCE: 4.8
                    NEIGHBOR_NSAMPLE: -1
                    POST_MLPS: [ 64, 64 ]


    POINT_HEAD:
        NAME: PointHeadSimple
        CLS_FC: [256, 256]
        CLASS_AGNOSTIC: True
        USE_POINT_FEATURES_BEFORE_FUSION: True
        TARGET_CONFIG:
            GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
        LOSS_CONFIG:
            LOSS_REG: smooth-l1
            LOSS_WEIGHTS: {
                'point_cls_weight': 1.0,
            }

    ROI_HEAD:
        NAME: PVRCNNHead
        CLASS_AGNOSTIC: True

        SHARED_FC: [256, 256]
        CLS_FC: [256, 256]
        REG_FC: [256, 256]
        DP_RATIO: 0.3

        NMS_CONFIG:
            TRAIN:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 9000
                NMS_POST_MAXSIZE: 512
                NMS_THRESH: 0.8
            TEST:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 1024
                NMS_POST_MAXSIZE: 100
                NMS_THRESH: 0.7
                SCORE_THRESH: 0.1

        ROI_GRID_POOL:
            GRID_SIZE: 6

            NAME: VectorPoolAggregationModuleMSG
            NUM_GROUPS: 2
            LOCAL_AGGREGATION_TYPE: voxel_random_choice
            NUM_REDUCED_CHANNELS: 30
            NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
            MSG_POST_MLPS: [ 128 ]

            GROUP_CFG_0:
                NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                MAX_NEIGHBOR_DISTANCE: 0.8
                NEIGHBOR_NSAMPLE: 32
                POST_MLPS: [ 64, 64 ]
            GROUP_CFG_1:
                NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
                MAX_NEIGHBOR_DISTANCE: 1.6
                NEIGHBOR_NSAMPLE: 32
                POST_MLPS: [ 64, 64 ]

        TARGET_CONFIG:
            BOX_CODER: ResidualCoder
            ROI_PER_IMAGE: 128
            FG_RATIO: 0.5

            SAMPLE_ROI_BY_EACH_CLASS: True
            CLS_SCORE_TYPE: roi_iou

            CLS_FG_THRESH: 0.75
            CLS_BG_THRESH: 0.25
            CLS_BG_THRESH_LO: 0.1
            HARD_BG_RATIO: 0.8

            REG_FG_THRESH: 0.55

        LOSS_CONFIG:
            CLS_LOSS: BinaryCrossEntropy
            REG_LOSS: smooth-l1
            CORNER_LOSS_REGULARIZATION: True
            LOSS_WEIGHTS: {
                'rcnn_cls_weight': 1.0,
                'rcnn_reg_weight': 1.0,
                'rcnn_corner_weight': 1.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: waymo

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.1
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 4
    NUM_EPOCHS: 80

    OPTIMIZER: adam_onecycle
    LR: 0.01
    WEIGHT_DECAY: 0.001
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
```

**Comment by Orbis36** [comment]
Thanks for your work. The output looks similar to mine. So is that mean on the validation set of KITTI, PV-RCNN++ does not perform better than PV-RCNN? @sshaoshuai

**Comment by sshaoshuai** [comment]
From this run, you can see that PV-RCNN++ achieves better performance on Cyclist category, and for the vehicle category, previously and I got better and stable performance (84.5%~85% mAP@R11) than PV-RCNN in my initial codebase, but now I do not have much time to tune it on KITTI dataset based on current codebase. 
Also, if you run the same configs for several times, you can also observe that the performance fluctuates during different runs, so I think we can not get stable conclusion on KITTI dataset. 

However, as I mentioned before, for KITTI dataset (also Waymo Dataset), we can still know that PV-RCNN++ consumes much less GPU memory and also is faster than PV-RCNN. (e.g., PV-RCNN++ can be trained with batch_size=4 on 11GB GPUs while PV-RCNN can not). 

I think this should be great for others to build more modifications based on PV-RCNN/PV-RCNN++ frameworks.

**Comment by Orbis36** [comment]
Thank you so much for your patience, I think that can solve my question perfectly.

**Comment by MartinHahner** [comment]
> Here is the config of PV-RCNN++ for KITTI dataset:
> 
> ```
> CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']
> 
> DATA_CONFIG:
>     _BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml
> 
> 
> MODEL:
>     NAME: PVRCNNPlusPlus
> 
>     VFE:
>         NAME: MeanVFE
> 
>     BACKBONE_3D:
>         NAME: VoxelBackBone8x
> 
>     MAP_TO_BEV:
>         NAME: HeightCompression
>         NUM_BEV_FEATURES: 256
> 
>     BACKBONE_2D:
>         NAME: BaseBEVBackbone
> 
>         LAYER_NUMS: [5, 5]
>         LAYER_STRIDES: [1, 2]
>         NUM_FILTERS: [128, 256]
>         UPSAMPLE_STRIDES: [1, 2]
>         NUM_UPSAMPLE_FILTERS: [256, 256]
> 
>     DENSE_HEAD:
>         NAME: AnchorHeadSingle
>         CLASS_AGNOSTIC: False
> 
>         USE_DIRECTION_CLASSIFIER: True
>         DIR_OFFSET: 0.78539
>         DIR_LIMIT_OFFSET: 0.0
>         NUM_DIR_BINS: 2
> 
>         ANCHOR_GENERATOR_CONFIG: [
>             {
>                 'class_name': 'Car',
>                 'anchor_sizes': [[3.9, 1.6, 1.56]],
>                 'anchor_rotations': [0, 1.57],
>                 'anchor_bottom_heights': [-1.78],
>                 'align_center': False,
>                 'feature_map_stride': 8,
>                 'matched_threshold': 0.6,
>                 'unmatched_threshold': 0.45
>             },
>             {
>                 'class_name': 'Pedestrian',
>                 'anchor_sizes': [[0.8, 0.6, 1.73]],
>                 'anchor_rotations': [0, 1.57],
>                 'anchor_bottom_heights': [-0.6],
>                 'align_center': False,
>                 'feature_map_stride': 8,
>                 'matched_threshold': 0.5,
>                 'unmatched_threshold': 0.35
>             },
>             {
>                 'class_name': 'Cyclist',
>                 'anchor_sizes': [[1.76, 0.6, 1.73]],
>                 'anchor_rotations': [0, 1.57],
>                 'anchor_bottom_heights': [-0.6],
>                 'align_center': False,
>                 'feature_map_stride': 8,
>                 'matched_threshold': 0.5,
>                 'unmatched_threshold': 0.35
>             }
>         ]
> 
>         TARGET_ASSIGNER_CONFIG:
>             NAME: AxisAlignedTargetAssigner
>             POS_FRACTION: -1.0
>             SAMPLE_SIZE: 512
>             NORM_BY_NUM_EXAMPLES: False
>             MATCH_HEIGHT: False
>             BOX_CODER: ResidualCoder
> 
>         LOSS_CONFIG:
>             LOSS_WEIGHTS: {
>                 'cls_weight': 1.0,
>                 'loc_weight': 2.0,
>                 'dir_weight': 0.2,
>                 'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
>             }
> 
>     PFE:
>         NAME: VoxelSetAbstraction
>         POINT_SOURCE: raw_points
>         NUM_KEYPOINTS: 2048
>         NUM_OUTPUT_FEATURES: 90
>         SAMPLE_METHOD: SPC
>         SPC_SAMPLING:
>             NUM_SECTORS: 6
>             SAMPLE_RADIUS_WITH_ROI: 1.6
> 
>         FEATURES_SOURCE: ['bev', 'x_conv3', 'x_conv4', 'raw_points']
>         SA_LAYER:
>             raw_points:
>                 NAME: VectorPoolAggregationModuleMSG
>                 NUM_GROUPS: 2
>                 LOCAL_AGGREGATION_TYPE: local_interpolation
>                 NUM_REDUCED_CHANNELS: 2
>                 NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
>                 MSG_POST_MLPS: [ 32 ]
>                 FILTER_NEIGHBOR_WITH_ROI: True
>                 RADIUS_OF_NEIGHBOR_WITH_ROI: 2.4
> 
>                 GROUP_CFG_0:
>                     NUM_LOCAL_VOXEL: [ 2, 2, 2 ]
>                     MAX_NEIGHBOR_DISTANCE: 0.2
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [ 32, 32 ]
>                 GROUP_CFG_1:
>                     NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                     MAX_NEIGHBOR_DISTANCE: 0.4
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [ 32, 32 ]
> 
>             x_conv3:
>                 DOWNSAMPLE_FACTOR: 4
>                 INPUT_CHANNELS: 64
> 
>                 NAME: VectorPoolAggregationModuleMSG
>                 NUM_GROUPS: 2
>                 LOCAL_AGGREGATION_TYPE: local_interpolation
>                 NUM_REDUCED_CHANNELS: 32
>                 NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
>                 MSG_POST_MLPS: [128]
>                 FILTER_NEIGHBOR_WITH_ROI: True
>                 RADIUS_OF_NEIGHBOR_WITH_ROI: 4.0
> 
>                 GROUP_CFG_0:
>                     NUM_LOCAL_VOXEL: [3, 3, 3]
>                     MAX_NEIGHBOR_DISTANCE: 1.2
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [64, 64]
>                 GROUP_CFG_1:
>                     NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                     MAX_NEIGHBOR_DISTANCE: 2.4
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [ 64, 64 ]
> 
>             x_conv4:
>                 DOWNSAMPLE_FACTOR: 8
>                 INPUT_CHANNELS: 64
> 
>                 NAME: VectorPoolAggregationModuleMSG
>                 NUM_GROUPS: 2
>                 LOCAL_AGGREGATION_TYPE: local_interpolation
>                 NUM_REDUCED_CHANNELS: 32
>                 NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
>                 MSG_POST_MLPS: [ 128 ]
>                 FILTER_NEIGHBOR_WITH_ROI: True
>                 RADIUS_OF_NEIGHBOR_WITH_ROI: 6.4
> 
>                 GROUP_CFG_0:
>                     NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                     MAX_NEIGHBOR_DISTANCE: 2.4
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [ 64, 64 ]
>                 GROUP_CFG_1:
>                     NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                     MAX_NEIGHBOR_DISTANCE: 4.8
>                     NEIGHBOR_NSAMPLE: -1
>                     POST_MLPS: [ 64, 64 ]
> 
> 
>     POINT_HEAD:
>         NAME: PointHeadSimple
>         CLS_FC: [256, 256]
>         CLASS_AGNOSTIC: True
>         USE_POINT_FEATURES_BEFORE_FUSION: True
>         TARGET_CONFIG:
>             GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
>         LOSS_CONFIG:
>             LOSS_REG: smooth-l1
>             LOSS_WEIGHTS: {
>                 'point_cls_weight': 1.0,
>             }
> 
>     ROI_HEAD:
>         NAME: PVRCNNHead
>         CLASS_AGNOSTIC: True
> 
>         SHARED_FC: [256, 256]
>         CLS_FC: [256, 256]
>         REG_FC: [256, 256]
>         DP_RATIO: 0.3
> 
>         NMS_CONFIG:
>             TRAIN:
>                 NMS_TYPE: nms_gpu
>                 MULTI_CLASSES_NMS: False
>                 NMS_PRE_MAXSIZE: 9000
>                 NMS_POST_MAXSIZE: 512
>                 NMS_THRESH: 0.8
>             TEST:
>                 NMS_TYPE: nms_gpu
>                 MULTI_CLASSES_NMS: False
>                 NMS_PRE_MAXSIZE: 1024
>                 NMS_POST_MAXSIZE: 100
>                 NMS_THRESH: 0.7
>                 SCORE_THRESH: 0.1
> 
>         ROI_GRID_POOL:
>             GRID_SIZE: 6
> 
>             NAME: VectorPoolAggregationModuleMSG
>             NUM_GROUPS: 2
>             LOCAL_AGGREGATION_TYPE: voxel_random_choice
>             NUM_REDUCED_CHANNELS: 30
>             NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
>             MSG_POST_MLPS: [ 128 ]
> 
>             GROUP_CFG_0:
>                 NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                 MAX_NEIGHBOR_DISTANCE: 0.8
>                 NEIGHBOR_NSAMPLE: 32
>                 POST_MLPS: [ 64, 64 ]
>             GROUP_CFG_1:
>                 NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
>                 MAX_NEIGHBOR_DISTANCE: 1.6
>                 NEIGHBOR_NSAMPLE: 32
>                 POST_MLPS: [ 64, 64 ]
> 
>         TARGET_CONFIG:
>             BOX_CODER: ResidualCoder
>             ROI_PER_IMAGE: 128
>             FG_RATIO: 0.5
> 
>             SAMPLE_ROI_BY_EACH_CLASS: True
>             CLS_SCORE_TYPE: roi_iou
> 
>             CLS_FG_THRESH: 0.75
>             CLS_BG_THRESH: 0.25
>             CLS_BG_THRESH_LO: 0.1
>             HARD_BG_RATIO: 0.8
> 
>             REG_FG_THRESH: 0.55
> 
>         LOSS_CONFIG:
>             CLS_LOSS: BinaryCrossEntropy
>             REG_LOSS: smooth-l1
>             CORNER_LOSS_REGULARIZATION: True
>             LOSS_WEIGHTS: {
>                 'rcnn_cls_weight': 1.0,
>                 'rcnn_reg_weight': 1.0,
>                 'rcnn_corner_weight': 1.0,
>                 'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
>             }
> 
>     POST_PROCESSING:
>         RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
>         SCORE_THRESH: 0.1
>         OUTPUT_RAW_SCORE: False
> 
>         EVAL_METRIC: waymo
> 
>         NMS_CONFIG:
>             MULTI_CLASSES_NMS: False
>             NMS_TYPE: nms_gpu
>             NMS_THRESH: 0.1
>             NMS_PRE_MAXSIZE: 4096
>             NMS_POST_MAXSIZE: 500
> 
> 
> OPTIMIZATION:
>     BATCH_SIZE_PER_GPU: 4
>     NUM_EPOCHS: 80
> 
>     OPTIMIZER: adam_onecycle
>     LR: 0.01
>     WEIGHT_DECAY: 0.001
>     MOMENTUM: 0.9
> 
>     MOMS: [0.95, 0.85]
>     PCT_START: 0.4
>     DIV_FACTOR: 10
>     DECAY_STEP_LIST: [35, 45]
>     LR_DECAY: 0.1
>     LR_CLIP: 0.0000001
> 
>     LR_WARMUP: False
>     WARMUP_EPOCH: 1
> 
>     GRAD_NORM_CLIP: 10
> ```

When I use this config as is, I get the following error:
```bash
2022-03-22 17:41:20,446   INFO  **********************start of training**********************
epochs:   0% 0/80 [00:00<?, ?it/s]
epochs:   0% 0/80 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/home/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 165, in train_model
    accumulated_iter, n_errors = train_one_epoch(model, optimizer, train_loader, model_func,
  File "/home/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 79, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/models/__init__.py", line 44, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/mhahner/anaconda3/envs/spconv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/models/detectors/pv_rcnn_plusplus.py", line 28, in forward
    batch_dict = self.pfe(batch_dict)
  File "/home/mhahner/anaconda3/envs/spconv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/models/backbones_3d/pfe/voxel_set_abstraction.py", line 372, in forward
    pooled_features = self.aggregate_keypoint_features_from_one_source(
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/models/backbones_3d/pfe/voxel_set_abstraction.py", line 325, in aggregate_keypoint_features_from_one_source
    pooled_points, pooled_features = aggregate_func(
  File "/home/mhahner/anaconda3/envs/spconv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/ops/pointnet2/pointnet2_stack/pointnet2_modules.py", line 462, in forward
    cur_xyz, cur_features = self.__getattr__(f'layer_{k}')(**kwargs)
  File "/home/mhahner/anaconda3/envs/spconv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mhahner/repositories/PCDet/tools/../pcdet/ops/pointnet2/pointnet2_stack/pointnet2_modules.py", line 396, in forward
    assert C % self.num_reduced_channels == 0, \
AssertionError: the input channels (1) should be an integral multiple of num_reduced_channels (2)
python-BaseException
```

**Comment by sshaoshuai** [comment]
@MartinHahner , 
Sorry, I forget one thing. You need to change a value of the config as here:
```
MODEL.PFE.SA_LAYER.raw_points.NUM_REDUCED_CHANNELS: 2 --> 1
```
Since KITTI dataset only has one extra point-wise feature channel for intensity.

**Comment by MartinHahner** [comment]
With your suggested change, it does not crash anymore. 
I also noticed and changed `EVAL_METRIC: waymo` to `EVAL_METRIC: kitti`.

**Comment by sshaoshuai** [comment]
Great, thank you! 
I have also updated the config in my answer.

**Comment by krauwu** [comment]
hello！could I know some tricks in train a pvrcnn++ net, or some set of hyperparam?

**Comment by r-gthb** [comment]
Hello, would I like to know about pandaset dataset training on PV RCNN model, have been trying to perform it but unsuccessful? any help would be appreciated.
