### ISSUE TITLE
using pillar vfe instead of Mean vfe and sparse conv gets a bad result?

### ISSUE THREAD

**Issue by leidahhh** [open-mmlab/OpenPCDet#832]
When I want to use pillar vfe in stead of mean vfe and sparse conv for deploying programs with tensorrt, I  did not get a desired results. And for VoxelSetAbstraction module, I gived up for 'x_conv3', 'x_conv4'. The trained loss is  Stable at around 9 and get a very bad precision. Also, the points within the key points could be rare sometimes. Could please tell me the reason of this? Thanks for your excellent work and I am forward to get your reply.

**Comment by umairkhawaja** [comment]
Hi, can you share if you were able to get desired results using Dynamic Pillar VFE in TensorRT?
