### ISSUE TITLE
KITTE trainning on entire dataset

### ISSUE THREAD

**Issue by vehxianfish** [open-mmlab/OpenPCDet#834]
I want to use the entire Kitti dataset which contains both train an validation dataset to training. And Using model evaluate the result on validation dataset to validate result. And this tests the effect of my improved model and then submits it to the server for testing. So I make changes on `kitti_datset_yaml`:
```
INFO_PATH: {
    'train': [kitti_infos_trainval.pkl],
    'test': [kitti_infos_val.pkl],
}
```
 In other words, I just replace `kitti_infos_train.pkl` with `kitti_infos_trainval.pkl`. But the results after training are not even as good as using only the results on the train set. 
Does anyone know why? Thank you very much for your help!

**Comment by MLbeginner2** [comment]
I encountered the same problem, did you solve it?
