### ISSUE TITLE
Inference on custom data

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/OpenPCDet#836]
I trained a model using WOD. But when i use it for inference on data from my own lidar(128 channel), I get inaccurate/useless outputs. I basically take the raw PointCloud data, put intensity of points through tanh, then pass it to VFE. However when I pass WOD data to model (straight from WOD .tfrecords to Pointcloud using OpenPCdet [functions](https://github.com/open-mmlab/OpenPCDet/blob/a9c66fee5348dcfb5f73ccca71becc2871ce3a78/pcdet/datasets/waymo/waymo_utils.py#L64) then to model) model works perfect. Is this a data distribution mismatch issue or am i missing something WOD SDK or OpenPCDet does while converting from .tfrecord to np array points.

**Comment by OrangeSodahub** [comment]
Hello, you can refer to my successful example using kitti format custom dataset. README describes how to label, train, inference it including transformation of coordinates. It may solve your problems!
https://github.com/OrangeSodahub/CRLFnet#lid-cam-fusion
https://github.com/OrangeSodahub/CRLFnet/blob/master/src/site_model/src/LidCamFusion/OpenPCDet/pcdet/datasets/custom/README.md
