### ISSUE TITLE
What does 'ref_from_car' mean?

### ISSUE THREAD

**Issue by WayneMao** [open-mmlab/OpenPCDet#838]
code:
https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/nuscenes/nuscenes_utils.py#L275
![image](https://user-images.githubusercontent.com/35285052/156490349-b67d11e8-a532-4e5d-aad0-9e508c0c9ef6.png)

I'm not sure if it means converting from the ego to the lidar coordinate system?

**Comment by Gsivap** [comment]
It is where the ego pose is in the lidar coordinate system. It is used here: https://github.com/open-mmlab/OpenPCDet/blob/9c8e583e28e45582565175f848b7a2538eb6acf6/pcdet/datasets/nuscenes/nuscenes_utils.py#L327
where we go from the lidar_frame to the car frame to the global frame then go from global frame to car frame to key lidar frame(ref_frame). I think it is to accumulate sweeps in the key lidar frame.
