### ISSUE TITLE
OpenPCDet PointPillars NuScenes velocity results

### ISSUE THREAD

**Issue by ahmedius2** [open-mmlab/OpenPCDet#841]
Hello,

In the accuracy results reported in PointPillar-MultiHead, the mAVE is 28.74. The AVE is defined by nuScenes as follows:
> Average Velocity Error (AVE): Absolute velocity error in m/s. Velocity error for barriers and cones are ignored.

I assume the mAVE is the mean of all AVE's for all classes. If I understand correctly, the mAVE result of your model appears not much useful for predicting the velocity of the objects (28.74 meters/second error), especially if you compare the results with the [nuScenes paper](https://arxiv.org/pdf/1903.11027.pdf):
![image](https://user-images.githubusercontent.com/6460689/156843636-9e28de97-51dc-4987-8367-4202bb0bf795.png)

On the other hand, the nuScenes paper says the following:
> Since mAVE, mAOE, and mATE can be larger than 1, we bound each metric between 0 and 1 in (3).

I couldn't understand this as well because the mAVE results in the table can be larger than 1.

My question is, for your model, is the velocity information is not useful due to some implementation issues that need to be fixed, or am I interpreting the numbers wrong?

I really appreciate this wonderful project and going to site it in our (hopefully) upcoming paper.

**Comment by sshaoshuai** [comment]
I guess it is just a format difference. 
28.74 indicates 28.74%=0.2874 instead of 28.74m/s.
