### ISSUE TITLE
Typo in augmentor_utils.py?

### ISSUE THREAD

**Issue by JenWei0312** [open-mmlab/OpenPCDet#843]
For random_flip_along_x, 
should L17 be gt_boxes[:, 0] = -gt_boxes[:, 0]?

Similarly, should L36 be gt_boxes[:, 1] = -gt_boxes[:, 1]?

Thanks

**Comment by MartinHahner** [comment]
No, I think both lines are correct. 

When you use the x-z-plane as a mirror ("along the x-axis") you need to flip the y-values:
https://github.com/open-mmlab/OpenPCDet/blob/a9c66fee5348dcfb5f73ccca71becc2871ce3a78/pcdet/datasets/augmentor/augmentor_utils.py#L17

When you use the y-z-plane as a mirror ("along the y-axis") you need to flip the x-values:
https://github.com/open-mmlab/OpenPCDet/blob/a9c66fee5348dcfb5f73ccca71becc2871ce3a78/pcdet/datasets/augmentor/augmentor_utils.py#L36
