### ISSUE TITLE
test.py has confilict with PYTHON 3.9 's test module

### ISSUE THREAD

**Issue by AlexWang1900** [open-mmlab/OpenPCDet#853]
when excuting line 7 in train.py
from test import repeat_eval_ckpt

output:
ImportError: cannot import name 'repeat_eval_ckpt' from 'test' (/home/alex/anaconda3/lib/python3.9/test/__init__.py)

solved by rename test.py in OpenPCDet to test_mm.py

**Comment by MartinHahner** [comment]
I use python 3.9 as well without a problem, so it is not a general, but rather a specific problem in your code environment.
