### ISSUE TITLE
Is anyone working on implementing a CARLA dataset in OpenPCDet for use of simulation data in training?

### ISSUE THREAD

**Issue by Javier-DlaP** [open-mmlab/OpenPCDet#854]
I have been trying to create an implementation for a CARLA dataset by recording the data given by this simulator.Then I have been trying to emulate the simulator data through the KITTI dataset so that I don't have to create a new implementation of this dataset in OpenPCDet.

Has anyone tried to implement a similar dataset using the CARLA simulation data in this project?

**Comment by LouisSF** [comment]
Hi, I might work one day on implementing Carla-like datasets in the future, such as [KITTI-CARLA dataset](https://npm3d.fr/kitti-carla) the style of KITTI. I will keep you informed if I start this.

**Comment by AOOOOOA** [comment]
> Hi, I might work one day on implementing Carla-like datasets in the future, such as [KITTI-CARLA dataset](https://npm3d.fr/kitti-carla) the style of KITTI. I will keep you informed if I start this.

Hi, have you started the work yet? If yes, maybe we can discuss some problems with it.

**Comment by makaveli10** [comment]
@AOOOOOA Can you please tell what problems are you facing?
