### ISSUE TITLE
Can we use gcc version 7.5.0

### ISSUE THREAD

**Issue by SaMeEr9597** [open-mmlab/OpenPCDet#864]
I am getting error while using gcc version 7.5.0, is there a necessity to have the version gcc 10 or will gcc 7.5.0 also work, 
I am also not able to change the version even after sudo apt-get install gcc-10, the gcc version 10 is installing but is not changing when is check using gcc --version

<img width="536" alt="image" src="https://user-images.githubusercontent.com/96261162/158032193-b51865af-ae6d-4d72-87ff-a26b58f6ebcf.png">

**Comment by curiousboy20** [comment]
I run the program on gcc 7.5.0 and it runs well. What kind of error message did you get?
