### ISSUE TITLE
Can we use spconv 2.x with pytorch 1.1 ? 

### ISSUE THREAD

**Issue by SaMeEr9597** [open-mmlab/OpenPCDet#866]
Can we use spconv 2.x with pytorch 1.1 ? or should we should we shift to another pytroch version

**Comment by jihanyang** [comment]
The main issue is that spconv2.x can only work on CUDA >= 10.2. You can refer spconv for more details

**Comment by SaMeEr9597** [comment]
> The main issue is that spconv2.x can only work on CUDA >= 10.2. You can refer spconv for more details

I'm currently using this version, so it should be fine right ? 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/96261162/158104978-9dc46457-1645-4e53-bed3-a4a27836b91b.png">

pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
