### ISSUE TITLE
explanation for some parameters in dataset and model's yaml file 

### ISSUE THREAD

**Issue by YCAyca** [open-mmlab/OpenPCDet#868]
Hello, there are some parameters that I dont understand and maybe a simple documentation would be useful for everyone. Spesifically I would like to ask what is exactly 

PREPARE: {
             filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
             filter_by_difficulty: [-1],
          }

SAMPLE_GROUPS: ['Car:20','Pedestrian:15', 'Cyclist:15']

and USE_ROAD_PLANE: True

parts in a dataset's yaml (eg kitti_dataset.yaml) file??

or 

MULTI_CLASSES_NMS = False
NMS_PRE_MAXSIZE: 4096
NMS_POST_MAXSIZE: 500

in a models yaml file like second.yaml
I know the logic of NMS but these 3 parameters I couldnt understand their functions

**Comment by YCAyca** [comment]
Thank you for your answer!

**Comment by MartinHahner** [comment]
> filter_by_difficulty: [-1]
this line means: filter annotations with "unknown" difficulty
