### ISSUE TITLE
A subset split of waymo to verify the idea quickly.

### ISSUE THREAD

**Issue by DapengFeng** [open-mmlab/OpenPCDet#87]
Hi, @sshaoshuai could you give a subset split of waymo for training and validation quickly?

**Comment by sshaoshuai** [comment]
I will prepare it soon.

**Comment by LZDSJTU** [comment]
Hi, shaoshuai. Is there any update on the training config of the waymo dataset?

**Comment by sshaoshuai** [comment]
The Waymo Open Dataset has been supported with state-of-the-art results just now.
