### ISSUE TITLE
How to turn the single frame of the demo into a video to view？

### ISSUE THREAD

**Issue by Leozyc-waseda** [open-mmlab/OpenPCDet#872]
I have a continuous frame and I want to see the output as a video, can someone please give me some advice?

> Your transformed custom data with a directory to test with multiple point cloud data.

```
python demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml \
    --ckpt pv_rcnn_8369.pth \
    --data_path ${POINT_CLOUD_DATA}
```
change  ${POINT_CLOUD_DATA}  to data/  and add --ext .npy
its not working.
Just one display after another, not continuous display.

**Comment by LouisSF** [comment]
Hi, you will have to do modifications with Open3D to modify the code, using this [StackOverflow issue](https://stackoverflow.com/questions/62912397/open3d-visualizing-multiple-point-clouds-as-a-video-animation) and the [Open3D page relative to non-blocking visualization](http://www.open3d.org/docs/0.8.0/tutorial/Advanced/non_blocking_visualization.html)

Then, either use an external recording software or search the Open3D docs, I know you can save individual images of point clouds but I'm not sure you can do the same for videos.

**Comment by Leozyc-waseda** [comment]
@LouisSF 
Thank you for your reply,
Do you mean to modify the Open3D display code, change data from 1 frame display to video display?

**Comment by maayanYa** [comment]
@Leozyc-waseda  Hi , did you understand how to render the bounding boxes in each frame ?
The mentioned examples are related only to the point cloud .
