### ISSUE TITLE
How to download Nuscenes dataset easily ? 

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/OpenPCDet#873]
Hi, 
I want to download **Nuscence dataset**, 
but I found that the file on the official site(https://www.nuscenes.org/download) was too large. 

If there's anyone who knows how to download this easily, please let me know!

Best,

**Comment by LouisSF** [comment]
Hi, what are you downloading exactly on the page? Nuscenes is already divided into chunks to download on the page. You could also download the mini subset of the dataset if you just want to do some manipulations with the data and not train a model.

**Comment by daeunni** [comment]
Thx for reply. :) 

Im trying to download **Full dataset (v1.0) Trainval** because i want to make fully trained model. 
btw, I couldn't find a **separate link** to download Full dataset (v1.0) (including train/val NOT mini dataset). 
It just exists together in a formal download official link(https://www.nuscenes.org/download) that collects many kinds of other data.

If there are separate links to download **Full dataset (v1.0) Trainval** , I think I can download it using `wget.` 
Let me know where this is!

**Comment by daeunni** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/62705839/158377389-32dcd42a-e9fc-464e-8026-82743bf8082a.png">

i want download this file

**Comment by LouisSF** [comment]
Isn't it possible to download the individual file blobs and then remove the data modalities (such as images) that you don't want ?

**Comment by daeunni** [comment]
um.. it might be possible. 
btw individual file's memory is tooo big, so i wanna know how to download it **easier**. 

do you know the Linux command that efficiently downloads files on all pages?

**Comment by hygxy** [comment]
> um.. it might be possible. btw individual file's memory is tooo big, so i wanna know how to download it **easier**.
> 
> do you know the Linux command that efficiently downloads files on all pages?

Did you figure out how to download the full v1.0 dataset using the "wget" Linux command?

**Comment by dthuremella** [comment]
I'm also looking for the answer to this

**Comment by daeunni** [comment]
@dthuremella  you can use "wget" command

**Comment by li-xl** [comment]
I just wrote a Python script that makes it easier to download the current dataset. You can give it a try here: [https://github.com/li-xl/nuscenes-download](https://github.com/li-xl/nuscenes-download).

**Comment by AshDrift98** [comment]
i want to download the training dataset of nuScenes in colab.

will this work?

!wget https://www.nuscenes.org/data/v1.0-trainval.tgz```

!tar -xzf v1.0-trainval.tgz

**Comment by rajeshthamarana** [comment]
is above commands worked

**Comment by iampujan** [comment]
I created a trainval blob downloader and test blob downloader using a bash script. It can be helpful. 
This is for nuscenes v1.0 full dataset.
Follow the readme here: https://github.com/iampujan/download_nuscenes_dataset

**Comment by CrusarAppy** [comment]
Had you guys downlaoded the nuscenes datasets , through wget, what is the correct url . Help me on this. Thank you!

**Comment by ChanHaoHao** [comment]
This works, so I suppose you will just have to change the filename in the url
```    
wget https://www.nuscenes.org/data/v1.0-mini.tgz
```
