### ISSUE TITLE
Multihead

### ISSUE THREAD

**Issue by YCAyca** [open-mmlab/OpenPCDet#874]
IHello,  just realized only multihead models have multiple anchor head and the default ones has single. Is that mean when it comes to the detection part after feature extraction, we create anchor boxes and detect classes one by one? and for multihead the detection part is applied at the same time for all the classes? For multihead the loss function is calculated by the sum of all these classes loss and in the single separetely?

I was simply wondering what is the main difference between multihead and single head models because actually we can train multiple classes with single head too

**Comment by Gsivap** [comment]
quoting from this paper: https://arxiv.org/pdf/1908.09492.pdf:
 if we put classes of discrepant shapes or sizes together, regression target will have bigger inter-class variances, which will make classes of different shapes interfere with each other. 
 
Section 2.3 in the linked paper explains in more detail.

**Comment by XiaoyanQian** [comment]
> IHello, just realized only multihead models have multiple anchor head and the default ones has single. Is that mean when it comes to the detection part after feature extraction, we create anchor boxes and detect classes one by one? and for multihead the detection part is applied at the same time for all the classes? For multihead the loss function is calculated by the sum of all these classes loss and in the single separetely?
> 
> I was simply wondering what is the main difference between multihead and single head models because actually we can train multiple classes with single head too

I also have this question. If we need to use multiple heads to detect different classes, does it mean our model is not enough for generalization? Hi YCAyca, do you think one single head can handle with this inter-class variance?
