### ISSUE TITLE
numpy.random leads to the same randomness between workers in one dataloader

### ISSUE THREAD

**Issue by zachluo** [open-mmlab/OpenPCDet#886]
Hi, I see the randomness in data augmentation uses random in NumPy. But this will lead to the same randomness between different workers in the same dataloader when it forks multiple processes. The solution goes to the replacement by random in python or random in torch, or usage of worker_init_fn to set the seed by worker_id. Do I miss something in codes?

**Comment by sshaoshuai** [comment]
Thanks for pointing out this problem. 

I remember that I have tried to use worker_init_fn to set some seeds for different workers (long long ago), and I did not remember that it affects the performance at that time.

Have you tried to solve this problem in our latest codebase? How about the peformance comparison? 
And I am happy to accept a PR if it does affect the performance. 

Thank you!
