### ISSUE TITLE
how to run test.py on the /testing dataset

### ISSUE THREAD

**Issue by Royaler** [open-mmlab/OpenPCDet#89]
@sshaoshuai

**Comment by Royaler** [comment]
and how to submit the test result to kitti website

**Comment by sshaoshuai** [comment]
In the latest code, you could set `DATA_SPLIT['test'] = 'test'`, and also set the `INFO_PATH['test']=[kitti_infos_test.pkl]` to generate the predictions for test split. 
To submit to kitti website, you could run `test.py` with `--save_to_file` parameter to save the required prediction results to files.

**Comment by sgrrlll** [comment]
> In the latest code, you could set `DATA_SPLIT['test'] = 'test'`, and also set the `INFO_PATH['test']=[kitti_infos_test.pkl]` to generate the predictions for test split. To submit to kitti website, you could run `test.py` with `--save_to_file` parameter to save the required prediction results to files.

Hello, I set --save_to_file default to true, but there is still no result in the txt file, do i have to get the test results on the kitti official website
![image](https://github.com/open-mmlab/OpenPCDet/assets/133968396/245d0857-8b36-42d7-8194-165da7e34386)
It also generates a result.pkl file, what does this do?

**Comment by Royaler** [comment]
黄佳遥已收到你的来信。
