### ISSUE TITLE
what does "anchor_bottom_heights" mean?

### ISSUE THREAD

**Issue by slayerlpj** [open-mmlab/OpenPCDet#895]
what does "anchor_bottom_heights" mean?
How should I set this value？
for example:
   'class_name': 'Car',
                'anchor_sizes': [[3.9, 1.6, 1.56]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-1.78],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.45
Why anchor_bottom_heights is -1.78?

**Comment by MartinHahner** [comment]
Because KITTI's LiDAR sensor is located 1.78m above the ground. See [here](http://www.cvlibs.net/datasets/kitti/setup.php).

![image](https://user-images.githubusercontent.com/14181188/159718320-db6f5265-1182-4939-8c7b-6c9be07eaa8d.png)

**Comment by slayerlpj** [comment]
> Because KITTI's LiDAR sensor is located 1.78m above the ground. See [here](http://www.cvlibs.net/datasets/kitti/setup.php).
> 
> ![image](https://user-images.githubusercontent.com/14181188/159718320-db6f5265-1182-4939-8c7b-6c9be07eaa8d.png)


Thank you for your reply！！！

  'class_name': 'Pedestrian',
                'anchor_sizes': [[0.8, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
'class_name': 'Cyclist',
                'anchor_sizes': [[1.76, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35

Why pedestrian  and cyclist anchor_bottom_heights is -0.6?

**Comment by MartinHahner** [comment]
> Why pedestrian and cyclist anchor_bottom_heights is -0.6?

Good question, no idea. 
Maybe my initial answer was wrong, perhaps try to search in the code where `anchor_bottom_heights` is used.

**Comment by jinhuilin97** [comment]
There is a question.
if I got the pre-train model by Waymo datasets, and I want to fine-tune in Kitti or other datasets,
what should I do with these part?
