### ISSUE TITLE
Install error with PyTorch 1.11

### ISSUE THREAD

**Issue by itskyf** [open-mmlab/OpenPCDet#900]
Seem PyTorch 1.11 has removed **THC.h** headers, so when I install pcdet it showed **THC/THC.h: No such file or directory**

To build successfully I have to delete these lines in all C++ operators, but I tbh don't know their functions (caching for something)?
```cpp
#include <THC/THC.h>
extern THCState *state;
```

**Comment by sshaoshuai** [comment]
You can simply comment these two lines (in pcdet/ops/pointnet2) or use a lower version pytorch.

**Comment by donkeyofking** [comment]
PyTorch 1.11.0+ removed the TH and THC part, just install PyTorch 1.9.0 with Cuda 11.x .
