### ISSUE TITLE
Why cbgs_pp_multihead.yaml doesn't use direction loss in PointPillar? 

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/OpenPCDet#905]
Hi, 
I found that one of nuScenes dataset model's config files 
'cbgs_pp_multihead.yaml' doesn't use **direction loss** in Pointpillar model. 

When i evaluate my own trained model, i got this message. 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/62705839/160072545-943d3292-dbac-44ae-b03e-f209047e2656.png">

so I think this part should be added to the config file. (because Pointpillar uses 3 losses included direction loss) 

`USE_DIRECTION_CLASSIFIER: True      `

am i right? 
Best,

**Comment by Anutlet** [comment]
I have the same question, have you solved it?

**Comment by Anutlet** [comment]
@daeunni
