### ISSUE TITLE
error output for function roiaware_pool3d_utils.points_in_boxes_gpu

### ISSUE THREAD

**Issue by DJNing** [open-mmlab/OpenPCDet#910]
Hi, I just found a weird result for function points_in_boxes_gpu when I tried to test PointRCNN-IOU

Different from problems shown here: https://github.com/open-mmlab/mmdetection3d/issues/315, which is caused by the wrong angle direction.

This function also gives error outputs for a simple test. Details can be seen on the screenshot

<img width="976" alt="debug_output" src="https://user-images.githubusercontent.com/29802444/160287150-67962a83-9028-4199-b024-f9fc8dca520b.png">

The bounding box parameters are formatted as (cx, cy, cz, lx, ly, lz, rot), with origin at (0.5, 0.5, 0.5). I wonder if this matters?

Besides, is this function synced with the one in mmdet3d?

**Comment by Devoe-97** [comment]
> Hi, I just found a weird result for function points_in_boxes_gpu when I tried to test PointRCNN-IOU
> 
> Different from problems shown here: [open-mmlab/mmdetection3d#315](https://github.com/open-mmlab/mmdetection3d/issues/315), which is caused by the wrong angle direction.
> 
> This function also gives error outputs for a simple test. Details can be seen on the screenshot
> 
> <img alt="debug_output" width="976" src="https://user-images.githubusercontent.com/29802444/160287150-67962a83-9028-4199-b024-f9fc8dca520b.png">
> 
> The bounding box parameters are formatted as (cx, cy, cz, lx, ly, lz, rot), with origin at (0.5, 0.5, 0.5). I wonder if this matters?
> 
> Besides, is this function synced with the one in mmdet3d?

I encountered the same problem, did you solve it?
