### ISSUE TITLE
How to get nuScenes test data results? (not v1.0-trainval)

### ISSUE THREAD

**Issue by daeunni** [open-mmlab/OpenPCDet#912]
does anyone know how to get nuScenes **test** data's results? (not valid data)

**Comment by zbaishancha** [comment]
@daeunni Hi, I'm having the same problem, do you know how to solve it? I want to use my own model to get the prediction result in nuscenes test dataset and save it, then submit it to nuscenes official website, do you know how to do it?

**Comment by daeunni** [comment]
I think you should submit your results to nuScenes websites(like kaggle)
