### ISSUE TITLE
The second stage of Centerpoint.

### ISSUE THREAD

**Issue by Cc-Hy** [open-mmlab/OpenPCDet#914]
Hello, it seems there is only the first stage of Centerpoint.
But the method in the paper uses a second stage which brings remarkable gains.

**Comment by sshaoshuai** [comment]
I think that the core contribution of CenterPoint is the high performance of RPN for all categories (especially the small objects), and its second stage is a simplified version of PV-RCNN/PV-RCNN++ head (only use the BEV features) that have already been supported by OpenPCDet. 
If you need exactly the same RCNN head, you can easily support it by modifying a small part of codes in OpenPCDet.

**Comment by Cc-Hy** [comment]
OK, thank you.
