### ISSUE TITLE
How to use the KITTI test_set to evaluate model?

### ISSUE THREAD

**Issue by zhangwanjingjj** [open-mmlab/OpenPCDet#917]
Thanks for your greate work! I want to use KITTI test set to evaluate the model. I modified DATA_SPLIT and INFO_PATH in the kitti_dataset.yaml, but the result shows that all the recalls are 0, and the mAP is not displayed.
![image](https://user-images.githubusercontent.com/97749065/161573843-d5d01828-1906-463d-a2c9-840e70ecaa09.png)
![image](https://user-images.githubusercontent.com/97749065/161574823-a1b336e9-db7d-40d8-9537-48b9f397e8f8.png)

**Comment by jihanyang** [comment]
Existing similar issues.

**Comment by hhhmrcscs** [comment]
Since there is no KITTI test set label, you should submit the results to KITTI's official website to get the map.

**Comment by sgrrlll** [comment]
I am also having the same problem, have you found a solution and I would appreciate it if you could tell me
