### ISSUE TITLE
Using docker with scripts/dist_train.sh

### ISSUE THREAD

**Issue by DeclK** [open-mmlab/OpenPCDet#918]
Hi, I just installed OpenPCDet with docker which is incredibly convenient!!!
But when I run with scripts/dist_train.sh, there is an error occurred `launch.py: error: unrecognized arguments: --rdzv_endpoint=localhost:xxxxx`
I think it's the problem of pytorch version (1.6.0)...

**Comment by DeclK** [comment]
Just simply remove `--rdzv_endpoint=localhost:xxxxx` would work

**Comment by ibdhan** [comment]
Great, thank you for your fast response
