### ISSUE TITLE
The test result is more different from the paper's result

### ISSUE THREAD

**Issue by xuxiaoxxxx** [open-mmlab/OpenPCDet#921]
when I test the pointpillar in the kitti Benchmark, compared with the paper's result, it is more diffrenet. Can you tell me why?
the pre is paper's result, and the last one is which I test by myself.
![1649572963(1)](https://user-images.githubusercontent.com/55653936/162605919-874a15a7-317a-413b-a2c8-48769d4c1bf1.jpg)
![1649572993(1)](https://user-images.githubusercontent.com/55653936/162605921-584d1f7e-3c94-4526-86f2-b8848d9a7c1a.jpg)

**Comment by lunhengsheng** [comment]
Can you tell us more about your test configuration and test commands?
