### ISSUE TITLE
Inconsistent coordinate system when assigning targets in CenterHead

### ISSUE THREAD

**Issue by Feng-HC** [open-mmlab/OpenPCDet#922]
Before we train model, our point cloud and labels have been converted to a unified coordinate system. 
1. Why do you need to transform the x-axis and y-axis in ** /pcdet/models/dense_heads/center_head.py **. The <???> represents the code which is causing my doubts.
```
       def assign_targets(self, gt_boxes, feature_map_size=None, **kwargs):
          
           feature_map_size = feature_map_size[::-1]  # [H, W] ==> [x, y]   <???>
```
2. Why do you need to transform the x-axis and y-axis when drawing gaussian to heatmap in ** pcdet/models/model_utils/centernet_util.py **.
```
       def draw_gaussian_to_heatmap(heatmap, center, radius, k=1, valid_mask=None):
          diameter = 2 * radius + 1
          gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
      
          x, y = int(center[0]), int(center[1])
      
          height, width = heatmap.shape[0:2]
      
          left, right = min(x, radius), min(width - x, radius + 1)
          top, bottom = min(y, radius), min(height - y, radius + 1)
      
          masked_heatmap = heatmap[y - top:y + bottom, x - left:x + right]   # <???>
          masked_gaussian = torch.from_numpy(
              gaussian[radius - top:radius + bottom, radius - left:radius + right]
          ).to(heatmap.device).float()
```
I suspect that the above operations will results in a mismatch between predictions and targets.

**Comment by jihanyang** [comment]
That is due to the definition of x and y in voxelization stage. You can refer to here to check the coordinate of feature map. https://github.com/open-mmlab/OpenPCDet/blob/878ad2e0016f3a5c4b3c4d5c86c9e9eebb230a62/pcdet/models/backbones_3d/vfe/dynamic_pillar_vfe.py#L133-L137
