### ISSUE TITLE
Are the lidar points and gt boxes in Waymo in vehicle coords?

### ISSUE THREAD

**Issue by Cc-Hy** [open-mmlab/OpenPCDet#936]

**Comment by sshaoshuai** [comment]
I think the answer is yes. 

To double check it, please refer to the following figure for the unified coordinate definition of OpenPCDet :

![image](https://user-images.githubusercontent.com/8805870/163832429-a250c8e1-a207-4958-a17a-1bd0e7d508e2.png)

**Comment by Cc-Hy** [comment]
Thanks, but what I concern is not the axis(lidar coords and vehicle coords share the same axis directions, juts as the fig upside), but the origin, that is, a point of (X,Y,Z), is the X,Y,Z in vehicle coords or lidar coords?
By reading the codes from both pcdet and Waymo, I think the points are in vehicle coords.
