### ISSUE TITLE
how  to train the pure lidar point dataset?

### ISSUE THREAD

**Issue by ccsself** [open-mmlab/OpenPCDet#940]
thanks for  your open project,  now  i  have only lidar point data, not image,calib  data.  can i use your  open project   to train my own dataset?   how to close the function of  calib,  image  parameters, using the only  lidar -point data

**Comment by OrangeSodahub** [comment]
Hello, you can refer to my successful example using kitti format custom dataset (pure lidar point). README describes how to label, train, inference it including transformation of coordinates. It may solve your problems!
https://github.com/OrangeSodahub/CRLFnet#lid-cam-fusion
https://github.com/OrangeSodahub/CRLFnet/blob/master/src/site_model/src/LidCamFusion/OpenPCDet/pcdet/datasets/custom/README.md
