### ISSUE TITLE
train  custom dataset  ,occur this error 

### ISSUE THREAD

**Issue by ccsself** [open-mmlab/OpenPCDet#945]
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

**Comment by OrangeSodahub** [comment]
Hello, I occurred this now, too. Have you solved the problem?

**Comment by rikardlegge-einride** [comment]
Also encountered this issue, one of the culprits I found was `transform_points_to_voxels` in `data_processor.py` producing voxels with 0 points in them, later triggering the assertion.

My hypothesis, which I have not confirmed yet, is that augmentations and sampling sometimes thins out the point cloud enough to cause this invalid state. The hypothesis is based on bumping into this issue when trying to train some of the models using lower resolution point clouds than can be found in the KITTI dataset. 

In my case this was triggered around once every 10000 samples and I therefore added two points of semi-random data (which I would not recommend). It at least fixed the assertion without having to dig into the internals of the voxel generator or the rest of the system.

If someone else has a better solution, I would love to hear about it!

**Comment by ccsself** [comment]
> Hello, I occurred this now, too. Have you solved the problem?

it hasn't been solved yet,  i   don't konw  how to adjust the parameter
