### ISSUE TITLE
Visulization seems not right

### ISSUE THREAD

**Issue by mc171819** [open-mmlab/OpenPCDet#946]
Hi, I use demo.py to visulise the result predicted by centerpoint, it seems not right, some cars is not detected but i think they are not so difficult to detect, some boxes seems produced without NMS:
![image](https://user-images.githubusercontent.com/81420309/164591958-3ac9c6dd-a082-4ebd-bacb-302f8fbfe47b.png)
![image](https://user-images.githubusercontent.com/81420309/164644355-3335b03f-b4cc-4568-8122-b71308e8ee7a.png)

The accuracy I get is:
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7142 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7090 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6327 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6280 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.7284 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.6672 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.6437 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.5884 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APH: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7053 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.6931 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.6795 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.6677 

How can this happen?

**Comment by mc171819** [comment]
By the way, the sequece i use for vis is segment-1005081002024129653_5313_150_5333_150_with_camera_labels

**Comment by sshaoshuai** [comment]
I guess it's the problem of visualization: 
https://github.com/open-mmlab/OpenPCDet/blob/846cf3ed21c274f95f041e7e21fd039ca5c99a1f/tools/visual_utils/visualize_utils.py#L163-L168

By default we only show 100 boxes at most by considering efficiency, and you can increase this number by yourself.

**Comment by mc171819** [comment]
Solved

**Comment by bigsheep2012** [comment]
Hello @mc171819,

May I know how you sovle it? and are u suing the default configuration(centerpoint.yaml) to train center point for 30 epoch(interval=5) on waymo dataset?

**Comment by bigsheep2012** [comment]
hi @mc171819,
use the author's implementation of WaymoDataset solve the issue. Thanks.

**Comment by 717770780** [comment]
> 
May I know how you sovle it? Did you just replace DemoDataset with WaymoDataset? Thanks.

**Comment by 717770780** [comment]
> hi @mc171819, use the author's implementation of WaymoDataset solve the issue. Thanks.

May I know how you sovle it? Did you just replace DemoDataset with WaymoDataset? Thanks.

**Comment by CaiFuyao** [comment]
> > hi @mc171819, use the author's implementation of WaymoDataset solve the issue. Thanks.
> 
> May I know how you sovle it? Did you just replace DemoDataset with WaymoDataset? Thanks.
Have you ever sovled this problem？Thanks!

**Comment by CaiFuyao** [comment]
May I know how you solve it? I change the __getitem__() method but it dosen't work. Could you show me your code? Thanks!!!
