### ISSUE TITLE
Explanation points_in_boxes_kernel Function

### ISSUE THREAD

**Issue by antoniosilva9116** [open-mmlab/OpenPCDet#954]
I have a question regarding cuda function in file roiaware_pool3d_kernel.cu. In this function, we have the following code:
```
__global__ void points_in_boxes_kernel(int batch_size, int boxes_num, int pts_num, const float *boxes,
    const float *pts, int *box_idx_of_points){

      int bs_idx = blockIdx.y;
      (...)
      
      boxes += bs_idx * boxes_num * 7;
      (...)
}
```
So, my question is how can we make an operation (summing) with an array (boxes: (B, N, 7) [x, y, z, dx, dy, dz, heading]) and an int value (even if it was a float value)? 
@sshaoshuai

**Comment by sshaoshuai** [comment]
Here the boxes is a pointer (point to some memory address) and the "+=" operation aims to shift the pointer to some new position for this sample (bs_idx).

**Comment by antoniosilva9116** [comment]
How could I translate this shift into python? do you have any idea?
