### ISSUE TITLE
Optimizer neglection when using nn.Parameter and 'adam_one_cycle' 

### ISSUE THREAD

**Issue by xiaoxin83121** [open-mmlab/OpenPCDet#960]
Hi, thanks to your great work!
I have noticed when building optimizer in 'adam_one_cycle' manner, only parameters in the leaf module are added to the optimizer parameter groups. I have tried a `nn.Parameter()`  in a non-leaf module, but it is not optimized since the building implementation in [line 26~32](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/train_utils/optimization/__init__.py)

I have solve it by adding a wrap module. Is there any fix plan about that or better solution?

**Comment by huixiancheng** [comment]
Same problem. Would you like to share your resolution. Thanks a lot.

**Comment by xiaoxin83121** [comment]
> Same problem. Would you like to share your resolution. Thanks a lot.

hi, just wrap `nn.Parameters` with a Subclass of `nn.Module`, and return it in `forward`
