### ISSUE TITLE
Can you explain exactly the meaning of voxels, coordinates, num_points ?

### ISSUE THREAD

**Issue by JaydencoolCC** [open-mmlab/OpenPCDet#968]
Can you explain exactly the meaning of voxels, coordinates, num_points ?

**Comment by ObsisMc** [comment]
1. `voxels`: the code will incise ponits into many voxels and every voxel has several points 
2. `voxel_coords`: records coordinates of corresponding voxels, it is used to tell voxels' position
3. `num_points`: code will extract the fixed number of points from a range to generate a voxel, if the number of points in the range is less than the fixed number, some padding points like (0,0,0) will be put into the voxel. `num_points`  stands for the number of actual points in a voxel.
