### ISSUE TITLE
 NVIDIA has updated its signing keys as of April 27, 2022

### ISSUE THREAD

**Issue by luigifaticoso** [open-mmlab/OpenPCDet#971]
As of Aprile 27, 2022 Nvidia has updated its signing keys making it impossible to run `apt-get update -y` in the docker file. 

```
#6 36.02 Reading package lists...
#6 36.81 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#6 36.81 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
``` 

I have fixed the problem by adding the new key to the docker file before the update command

`apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub`

Will it be updated in the docker image or it is requested to update the dockerfile? 

In case anyone finding the issue you can find the solution here

**Comment by KarstenVogt** [comment]
Dear Luigi,

thank you so much for this. It solved my problem just fine. Greetings to beautiful Italy. :)
