### ISSUE TITLE
How to use the demo.py script with CenterPoint trained in NuScenes

### ISSUE THREAD

**Issue by mikelgarciafonseca** [open-mmlab/OpenPCDet#974]
Hello, I've been able to follow the demo.py script to visualize the detections with KITTI .bin files and my own Lidar data in .npy format using PV-RCNN ( with the same config and pretrained model as in the DEMO.md).

Now I want to test the CenterPoint model of your model zoo trained in NuScenes with my own .npy files, but I get the following error:

![error_nuscenes](https://user-images.githubusercontent.com/17387057/169271661-246a5ac7-060f-47db-90a4-f561252ccc27.PNG)

Could you provide me with some instructions or documentation in how to test this model with my own data? 

Thanks in advance.

**Comment by jihanyang** [comment]
There is a very easy method: just put the visualization code to here when evaluation
https://github.com/open-mmlab/OpenPCDet/blob/846cf3ed21c274f95f041e7e21fd039ca5c99a1f/tools/eval_utils/eval_utils.py#L59
