### ISSUE TITLE
pcdet install

### ISSUE THREAD

**Issue by VsionQing** [open-mmlab/OpenPCDet#977]
(Open) llq@3090:/media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1$ python setup.py develop

/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/setuptools/dist.py:531: UserWarning: Normalizing '0.5.0+0000000' to '0.5.0+0'
  warnings.warn(tmpl.format(**locals()))
running develop
/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing pcdet.egg-info/PKG-INFO
writing dependency_links to pcdet.egg-info/dependency_links.txt
writing requirements to pcdet.egg-info/requires.txt
writing top-level names to pcdet.egg-info/top_level.txt
reading manifest file 'pcdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pcdet.egg-info/SOURCES.txt'
running build_ext
/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.2) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
Emitting ninja build file /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -B /home/llq/miniconda3/envs/Open/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_cpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -L/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/iou3d_nms_cuda.cpython-38-x86_64-linux-gnu.so
building 'pcdet.ops.roiaware_pool3d.roiaware_pool3d_cuda' extension
Emitting ninja build file /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -B /home/llq/miniconda3/envs/Open/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/roiaware_pool3d/src/roiaware_pool3d.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/roiaware_pool3d/src/roiaware_pool3d_kernel.o -L/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/pcdet/ops/roiaware_pool3d/roiaware_pool3d_cuda.cpython-38-x86_64-linux-gnu.so
building 'pcdet.ops.roipoint_pool3d.roipoint_pool3d_cuda' extension
Emitting ninja build file /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -B /home/llq/miniconda3/envs/Open/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/roipoint_pool3d/src/roipoint_pool3d.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/roipoint_pool3d/src/roipoint_pool3d_kernel.o -L/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/pcdet/ops/roipoint_pool3d/roipoint_pool3d_cuda.cpython-38-x86_64-linux-gnu.so
building 'pcdet.ops.pointnet2.pointnet2_stack.pointnet2_stack_cuda' extension
Emitting ninja build file /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -B /home/llq/miniconda3/envs/Open/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/llq/miniconda3/envs/Open/lib -Wl,-rpath-link,/home/llq/miniconda3/envs/Open/lib -L/home/llq/miniconda3/envs/Open/lib /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query_gpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points_gpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate_gpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/pointnet2_api.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/sampling.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/sampling_gpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/vector_pool.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/vector_pool_gpu.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query_gpu.o -L/home/llq/miniconda3/envs/Open/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/pointnet2_stack_cuda.cpython-38-x86_64-linux-gnu.so
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o: 没有那个文件或目录
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o: 没有那个文件或目录
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o: 没有那个文件或目录
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/sampling.o: 没有那个文件或目录
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/vector_pool.o: 没有那个文件或目录
g++: error: /media/llq/DCF8DE2DF8DE0624/OPEN/OpenPCDet-master1/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1

**Comment by leducnguyen21** [comment]
What CUDA and Pytorch have you installed? I also have problem with installment in VSCode
