### ISSUE TITLE
PVRCNN tested on my dataset, got a lot of false postive

### ISSUE THREAD

**Issue by Leozyc-waseda** [open-mmlab/OpenPCDet#982]
How to fix this problem?

I am using PVRCNN to test on my 32 beam dataset, pretrained by Pandaset 64 beam.

![image](https://user-images.githubusercontent.com/52599722/170453506-666081f5-b002-4ddb-b48b-52c728f2a550.png)

**Comment by udacityyy** [comment]
Hello, sorry to ask this, but could you tell me which tool did you use to visualize the results?

**Comment by luminous33** [comment]
> How to fix this problem?
> 
> I am using PVRCNN to test on my 32 beam dataset, pretrained by Pandaset 64 beam.
> 
> ![image](https://user-images.githubusercontent.com/52599722/170453506-666081f5-b002-4ddb-b48b-52c728f2a550.png)

Hello if you are ok, Could i get pretrained by Pandaset 64 beam?
zmfkvlzk@gmail.com -> this is my email address.

I tried train own my dataset. But it keeps failing.
If you can help me, it will be a great help to me :)

Thk

**Comment by OrangeSodahub** [comment]
Not so sure about what problem you may have. But can refer to my successful achievement on training my own dataset and inference correctly https://github.com/OrangeSodahub/CRLFnet
