### ISSUE TITLE
CaDDN visualization

### ISSUE THREAD

**Issue by ESONG1999** [open-mmlab/OpenPCDet#985]
Hello!
When I am using the demo.py to get the visualization result of the CaDDN. I got this error
![截屏2022-05-29 下午3 03 29](https://user-images.githubusercontent.com/100745711/170892983-f88bfdc4-bad4-43ad-b05a-6a43fc44bcc8.png)
Did anyone know how to solve this problem? And did anyone successfully visualize the result of CaDDN?
Very big thanks!

**Comment by jihanyang** [comment]
This is caused by different pytorch version when dump and load checkpoint. Just google it.
