### ISSUE TITLE
confused about the function "limit_period"

### ISSUE THREAD

**Issue by zxduan90** [open-mmlab/OpenPCDet#99]
There are two parameters (offset and period) in function "limit_period". Cloud you please explain more in details about these two parameters ?

**Comment by sshaoshuai** [comment]
It is used to transfer an unbounded angle to a bounded angle with a specific period, and the offset is within 0-1 to specify the position of angle==0. This function is borrowed from the code of SECOND.

**Comment by buaaJeremyduan** [comment]
Take this function " limit_period(angle, offset=0.5, period=2*np.pi)" as example. This is used to transfer an unbounded angle to -pi(-offset*period) ~ pi(offset*period) by add or minus (2*np.pi)*n. Is that right?

**Comment by sshaoshuai** [comment]
For your case, I think it is right.
