### ISSUE TITLE
ONNX export failure: ONNX export failed: Couldn't export Python operator FarthestPointSampling

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/OpenPCDet#992]
pth convert to onnx.
how to solve...

**Comment by gzchenjiajun** [comment]
solved

**Comment by csstuer** [comment]
Hi, I have also encountered this problem. I would like to ask how did you solve it at that time?

**Comment by ccsself** [comment]
> solved
hello   how to solve?   now  i want to change pth  to onnx  ,could u share me the solved shell?

**Comment by yBeOne** [comment]
how to convert spconv to onnx?

**Comment by Kabidoye-17** [comment]
> solved

Hi, How did you solve it?
