### ISSUE TITLE
How to obtain inference speed？

### ISSUE THREAD

**Issue by VsionQing** [open-mmlab/OpenPCDet#997]
How to calculate the inference speed FPs in this paper?
PV-RCNN and so on

**Comment by Jane-QinJ** [comment]
Have the same question

**Comment by Jane-QinJ** [comment]
> We use `time.time()` with `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'`

Thank u for your gentle reply! But I'm not familiar enough to your great work. So could u gentlely tell me in detail how to write this code and use it in your OpenPCDet framework? I'll be very appreciated to your instruction.

**Comment by strugglingguoguo** [comment]
I Have the same question.I don't know where to put the time module.

**Comment by jihanyang** [comment]
Put `time.time()` here to calculate the forward time: 
https://github.com/open-mmlab/OpenPCDet/blob/c233477a4a4bf2861a978794d6b9c047f64641f7/tools/eval_utils/eval_utils.py#L56-L57

**Comment by jihanyang** [comment]
Supported in the latest verison with `--infer_time` keyword

**Comment by ammaryasirnaich** [comment]
Is there a difference between --infer_time and FPS ?
